### ISSUE TITLE
Failed to create experiment: invalid experiment: invalid experiment configuration: error unmarshaling JSON: while decoding JSON: json: unknown field "max_length"

### ISSUE THREAD

**Issue by luisoutomaior** [determined-ai/determined#1057]
I get into this issue when running the examples/official/trial/mnist_gan_pytorch with the command:
`det experiment create distributed.yaml .`

The fix is changing the max_length field in distributed.yaml from:

```
  max_length:
    batches: 40000

```
to:

```
 max_steps: 4000
```

**Comment by neilconway** [comment]
@luisoutomaior Thank you for reporting this issue! The example config file you posted that uses `max_length` is intended for use with the next release of Determined. With Determined <= 0.12.13, I'd recommend using the examples that are distributed with the product, or else looking at the `0.12.13` tag on GitHub: e.g., https://github.com/determined-ai/determined/tree/0.12.13/examples/official/trial/mnist_gan_pytorch
