### ISSUE TITLE
mnist_gan_pytorch example errors "'PyTorchTrialContext' object has no attribute 'wrap_model'`"

### ISSUE THREAD

**Issue by luisoutomaior** [determined-ai/determined#1074]
`315f8025 [RUNNING] ||  Wed Aug 12 22:48:22 2020[1]<stderr>:AttributeError: 'PyTorchTrialContext' object has no attribute 'wrap_model'`

I get this error while running the 0.12.13 version of the mnist_gan_pytorch example under examples/official/trial/mnist_gan_pytorch.

Seems to be related to lines `85` and `86` on `model_def.py`:
```python
        self.generator = self.context.wrap_model(Generator(latent_dim=self.context.get_hparam("latent_dim"), img_shape=mnist_shape))
        self.discriminator = self.context.wrap_model(Discriminator(img_shape=mnist_shape))

```

**Comment by neilconway** [comment]
@luisoutomaior Hi Luis -- I wasn't able to reproduce this: the `mnist_gan_pytorch` example runs for me using the 0.12.13 release. Can you double-check that you are using Determined 0.12.13 on the master and all the agents? The `wrap_model` API was introduced recently (in 0.12.13), so if you're using an old version someone that might be the cause of the problem.

**Comment by luisoutomaior** [comment]
Thanks @neilconway ! Indeed I had the 0.12.12 installed instead of the .13.
