### ISSUE TITLE
det-deploy is not recognized

### ISSUE THREAD

**Issue by demongolem** [determined-ai/determined#1407]
I did the pip install and I get the above when I am looking to deploy.  Can this run on Windows or that something that is not happening?

**Comment by vishnu2kmohan** [comment]
@demongolem To clarify, did you run `pip install determined-deploy==0.13.5` and then trying to invoke `det-deploy` on Windows?

**Comment by rb-determined-ai** [comment]
@demongolem would you mind sharing more information, like a copy/paste of the command you ran and the exact result that you got, where you are trying to deploy to, etc?

**Comment by demongolem** [comment]
> @demongolem To clarify, did you run `pip install determined-deploy==0.13.5` and then try to invoke `det-deploy` on Windows?

Yes.  Initially I did not put the ==0.13.5, but that is the sequence of steps I tried, as specified at https://docs.determined.ai/latest/how-to/installation/deploy.html

**Comment by vishnu2kmohan** [comment]
@demongolem Are you attempting to install/deploy Determined on Windows? Or to use the `det-deploy` (and/or `det`) CLI to deploy to AWS/GCP?
Note: We don't support deploying Determined on Windows, and we haven't explicitly tested `det-deploy` on Windows)
(There is a possibility that it _could_ work via Windows Services for Linux 2 (WSL2) but we haven't tested it ourselves.)

**Comment by demongolem** [comment]
Ok thanks that answers my query.  Will try for another environment
