### ISSUE TITLE
Update buf.yaml with version and update deprecated commands/flags

### ISSUE THREAD

**Issue by bufdev** [determined-ai/determined#1578]
https://docs.buf.build/faq

You want to add a `version` to the top of `buf.yaml`:

```yaml
version: v1beta1
```

The flag `buf check breaking --against-input` is now `--against`, and `buf image build` is now `buf build as well.

Note that right now, everything continues to work, which is why you haven't had any issues, but we will likely enforce the `version` key for `buf.yaml` at v1.0.

It may be an opportune time to check out `buf generate` as well :-) https://docs.buf.build/generate-usage Let us know if you have any questions!

**Comment by rb-determined-ai** [comment]
@hamidzr do you know what this is all about?

**Comment by hamidzr** [comment]
Created DET-4627

**Comment by vishnu2kmohan** [comment]
@hamidzr Is this issue resolved, and if so, might we please close it out?

**Comment by hamidzr** [comment]
no, I don't think so the ticket is still open. let's reopen we pick that up.
