### ISSUE TITLE
optional timeout for idle notebooks and shells

### ISSUE THREAD

**Issue by zjorgensenbits** [determined-ai/determined#1585]
It would be very helpful to be able to configure an optional timeout for idle notebooks and shells, similarly to the timeout option available for tensorboards. This would help prevent team members from accidentally leaving shells and notebooks running and taking up GPU resources without using them.

**Comment by vishnu2kmohan** [comment]
@zjorgensenbits Agreed on this as well. We'll add support for this and I'll update this issue once it's released.

**Comment by vishnu2kmohan** [comment]
Just a note that we're going to start working on this effort soon @zjorgensenbits, and will update this issue when it's ready.

**Comment by vishnu2kmohan** [comment]
Update: We landed idle timeout support in 0.17.0

cc @shiyuann
