### ISSUE TITLE
archive/delete terminated tasks in dashboard

### ISSUE THREAD

**Issue by zjorgensenbits** [determined-ai/determined#1652]
it doesn't appear that it's possible to archive or delete terminated tasks so that they no longer show up in the dashboard. This leads to a lot of visual clutter.

**Comment by hkang1** [comment]
Hey @zjorgensenbits,

Thanks for submitting this issue!

The tasks that have terminated will naturally go away (removed from master's memory) after 24 hours (I believe), so we don't explicitly provide the ability to archive or delete. Could you help us understand by describing a little bit of how you are currently using the dashboard page and what your workflow looks like?

**Comment by zjorgensenbits** [comment]
ahh, I didn't realized they were cleared out after 24hrs. If that's the case, we're good.

**Comment by hkang1** [comment]
It's understandable since there's no indications of if and when the clearing of stale tasks occurs.
