### ISSUE TITLE
tensorboard can't open

### ISSUE THREAD

**Issue by scotthuang1989** [determined-ai/determined#1743]
After run the example [pytorch minist tutorial](http://192.168.8.200:8080/docs/tutorials/pytorch-mnist-tutorial.html#pytorch-mnist-tutorial). I try to open tensorbaord but failed.

I try 2 methods.

1. web GUI:  

> the web page show:  "Service State: PENDING Waiting for service.." . 

2. det command:  det tensorboard start 14 

the output is: 

> Scheduling TensorBoard (typically-harmless-ox) (id: cbf3a135-083c-47c2-83b4-ad875fa6414c)...

**Comment by vishnu2kmohan** [comment]
@scotthuang1989 Which version of Determined are you running?

**Comment by vishnu2kmohan** [comment]
@scotthuang1989 Following up here, did you manage to get TensorBoards to load?

**Comment by scotthuang1989** [comment]
@vishnu2kmohan  I resintall whole thing on another machine. tensorboard can open it. I am comparing the version, configuration between them. not sure what's going wrong.

**Comment by vishnu2kmohan** [comment]
@scotthuang1989 You may have a firewall rule that blocks the required connectivity, as part of your Docker Engine configuration - see https://github.com/determined-ai/determined/issues/906#issuecomment-664958000 for details, and a possible solution.

**Comment by scotthuang1989** [comment]
@vishnu2kmohan It's a network issue, turning off firewall works.

**Comment by DeriZSY** [comment]
Hi, would you mind mentioning how did you make it work? Met a similar problem as mentioned here
