### ISSUE TITLE
Integration with other experiments tracker (Comet ML, Weights and Biases)

### ISSUE THREAD

**Issue by MatthieuTPHR** [determined-ai/determined#1754]
Is it possible to use determined ai with other experiment tracker such as Comet ML, or Weights and Biases ? 

The feature that I am interested the most in determined ai is the distributed training mechanism. However it seems that it is not yet possible to couple this feature with existing experiments trackers as mentioned above.

**Comment by neilconway** [comment]
@MatthieuTPHR Thanks for the question! It should be possible to use other experiment trackers with Determined. You can't currently disable Determined's built-in experiment tracking, but you should be able to also use other experiment tracking tools just as you would outside of Determined. We don't have any experience doing this, however -- if you try it, please let us know how it goes!

BTW if there are specific experiment tracking features you're interested in that we don't currently support, that would be really useful feedback. Thanks!

**Comment by vishnu2kmohan** [comment]
@MatthieuTPHR FWIW we have other users who have successfully integrated W&B into their Trials. Have you been able to integrate? If so, may we please close out this issue?

**Comment by vishnu2kmohan** [comment]
Closing out this issue @MatthieuTPHR, please re-open, if needed.
