### ISSUE TITLE
Typo in release date

### ISSUE THREAD

**Issue by mullerrwd** [determined-ai/determined#1804]
A minor heads-up, the below release dates reflects the previous year instead of 2021.
![image](https://user-images.githubusercontent.com/44808485/104917183-5c632c80-5993-11eb-953c-9318045ccdfb.png)

**Comment by neilconway** [comment]
@mullerrwd Thank you for noticing this! I opened #1812 with the fix for this.

**Comment by neilconway** [comment]
Fixed.
