### ISSUE TITLE
Training and Validation times in Summary are inaccurate--continue to accumulate after experiment is over

### ISSUE THREAD

**Issue by wbwatkinson** [determined-ai/determined#1806]
Something is not right with the training time as depicted in this image. Note that the actual difference between the start and end time in this image is a little less than 5 minutes. Most of this time was the spin up of an agent to support the experiment. Although the experiment is over, every time I return to this page, the experiment time is increased. The same is true of the validating time, though the time does not increase at the same rate.

![image](https://user-images.githubusercontent.com/10328572/104942700-cb845500-5982-11eb-9f0c-cb94717b7508.png)

**Comment by neilconway** [comment]
> Although the experiment is over, every time I return to this page, the experiment time is increased.

Can you clarify which times continue to increase? e.g., is it specifically the validation duration or other values as well?

**Comment by wbwatkinson** [comment]
Specifically, the "Training" and "Validating" durations continue to increase after the job is complete.

**Comment by hamidzr** [comment]
Hi @wbwatkinson could you please share what version are you running?

**Comment by hkang1** [comment]
Hi @wbwatkinson, thanks for reporting this issue. We just recently fixed this issue, and it is part of the [0.13.12 release](https://github.com/determined-ai/determined/releases/tag/0.13.12). If you upgrade to this version the duration should match up. One thing to note is that the total time for each workload (training, validation, checkpoint) can still be greater than `end time` - `start time` when the trial runs multiple workloads in parallel.

**Comment by wbwatkinson** [comment]
> Hi @wbwatkinson could you please share what version you are running?

So, the answer to question is interesting point that I planned to bring up as well. The master version is 0.13.11. Many command line commands present the following notice:

> Master version 0.13.11 is less than CLI version 0.13.12. Consider upgrading the master.

I attempted to upgrade with the following command line sequence:
```bash
det -m MASTER agent disable --all
pip install determined-cli
pip install determined-deploy
```

The determined-deploy notes reference 0.13.12, but the master remained at 0.13.11 and I continue getting the upgrade notifications.

**Comment by hamidzr** [comment]
currently, the WebUI is directly served by the master  and would have the same version as the master (https://docs.determined.ai/latest/rest-api/#/Cluster/Determined_GetMaster) 

> I attempted to upgrade with the following command line sequence:

those two commands would only upgrade the CLI packages which are separate from the cluster. and it looks like you've successfully upgraded them.  I think we have documentation on how to upgrade the cluster. let me find those

**Comment by eecsliu** [comment]
Hi @wbwatkinson! You should be able to upgrade the cluster using determined-deploy. There isn't an explicit upgrade command, but you can accomplish an upgrade by using determined-deploy by specifying the same cluster name and settings, as well as using the flag `--det-version 0.13.12`. It should detect that you have an existing cluster and will upgrade to 0.13.12 for you.

**Comment by wbwatkinson** [comment]
> https://docs.determined.ai/latest/how-to/installation/upgrades-troubleshoot.html?highlight=upgrade I'll see if we have more than that

Thank you for this reference... I did use that, which inspired the above command line sequence based on this note in the referenced doc:

> Upgrading an existing Determined installation requires the same steps as installing Determined for the first time. You should additionally follow the steps below to safely shut down the cluster before beginning an upgrade. 

I didn't see anything in the referenced doc that stated how to upgrade cluster apart from repeating the steps to install Determined for the first time.

**Comment by wbwatkinson** [comment]
> Hi @wbwatkinson! You should be able to upgrade the cluster using determined-deploy. There isn't an explicit upgrade command, but you can accomplish an upgrade by using determined-deploy by specifying the same cluster name and settings, as well as using the flag `--det-version 0.13.12`. It should detect that you have an existing cluster and will upgrade to 0.13.12 for you.

Thank you! I'll give this a try.

**Comment by wbwatkinson** [comment]
I was able to update the cluster using the provided command line flag.
