### ISSUE TITLE
AuthFailure.ServiceLinkedRoleCreationNotPermitted when attempting to launch EC2 Spot Instances

### ISSUE THREAD

**Issue by wbwatkinson** [determined-ai/determined#1830]
When the cluster attempts to launch EC2 spot instances, I receive the following notice and error:

```
<info> [2021-01-21, 05:20:24] AWS error while launching spot instances, AuthFailure.ServiceLinkedRoleCreationNotPermitted, The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.  id="provisioner" resource-pool="default" system="master" type="Provisioner"
<error> [2021-01-21, 05:20:24] cannot launch EC2 spot requests  error="AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.\n\tstatus code: 403, request id: d055892e-797c-46ae-8da5-b98f70638de8" id="provisioner" resource-pool="default" system="master" type="Provisioner"
```

AWS [documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#service-linked-roles-spot-instance-requests) states that in most cases, the AWSServiceRoleForEC2Spot service-linked role is automatically added on the first attempt at creating an EC2 Spot instance from the console. I assume because I have never attempted to create a spot instance from the console, this role was not added.

I added the role manually using the AWS CLI:
```bash
aws iam create-service-linked-role --aws-service-name spot.amazonaws.com
```

The AWS documentation also provides the following instructions for using the console:
1. Open the IAM console at https://console.aws.amazon.com/iam/.
2. In the navigation pane, choose Roles.
3. Choose Create role.
4. On the Select type of trusted entity page, choose EC2, EC2 - Spot Instances, Next: Permissions.
5. On the next page, choose Next: Review.
6. On the Review page, choose Create role.

These instructions work except that a new Step 5 should be inserted: "On the next page, choose Next: Tags", and the existing step 5 and step 6 should each be incremented by 1.

I recommend adding a instructions to create the service-linked role on the appropriate page of the AWS documentation: https://docs.determined.ai/latest/topic-guides/deployment/aws-spot.html#

**Comment by vishnu2kmohan** [comment]
Thank you so much @wbwatkinson, we'll make sure to add these instructions to the [AWS Spot documentation page](https://docs.determined.ai/latest/topic-guides/deployment/aws-spot.html)!
