### ISSUE TITLE
det-deploy does not operate within a multi-profile aws cli environment

### ISSUE THREAD

**Issue by wbwatkinson** [determined-ai/determined#1861]
`aws cli` allows the use of multiple profiles by adding [named profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) in the `~/.aws/config` and `~/.aws/credentials` files. It appears det-deploy simply exclusively uses the `default` profile.

Recommendation: create a `--profile` argument for the `det-deploy aws up` and `det-deploy aws down` so that det-deploy can operate within a user's multi-profile setup.

**Comment by vishnu2kmohan** [comment]
Thanks for the suggestion @wbwatkinson, we'll keep you posted.

**Comment by davetroiano** [comment]
@wbwatkinson thanks for reaching out. We do support profiles in `det-deploy` today though the argument is suppressed from docs and `det-deploy` help strings.  You can pass `--aws-profile PROFILE` to get the desired behavior. Please give that a shot and let us know how it goes. I'll close this out but please reopen if you run into any issues with this.

In the next release (~2 weeks from now), heads up on two changes around this:
1. We'll expose the arg in docs and `det-deploy` help. No reason to hide it
2. I agree with your instinct on the naming -- we'll change it from `--aws-profile` to `--profile`

**Comment by wbwatkinson** [comment]
Yes, that worked! Or at least it found the right profile. Until I can deploy to us-gov-west-1, I won't actually be able to get determined up and running.
