### ISSUE TITLE
ERROR 503: Service Unavailable on WebUI Login/Dashboard

### ISSUE THREAD

**Issue by mitsch** [determined-ai/determined#2067]
Hi,

I wanted to set up a small cluster with `det-deploy local cluster-up --master-port 8080 --no-gpu` on my laptop. All seems fine; I open via my browser the web-ui at `http://localhost:8080` and the login page appears. After entering my credentials, nothing happens apparently.

I refresh on which I'm redirected to `http://localhost/det/dashboard` where the web page keeps endlessly loading.

The debugging terminal on my browser tells me that some requests are closed by http503. On closer inspection `curl -vvv http://localhost:8080/api/v1/agents`, I get the following response:
```
...
<p>The following error was encountered while trying to retrieve the URL: <a href=":8080">:8080</a></p>
...
```

I suppose, the hostname has to be inserted, but where? Is it automatically deduced from some (environment) variable? Can I set it explicitely?

```bash
$ det-deploy --version
det-deploy 0.14.3
```

I kindly appreciate any help.

Cheers,
Michael

**Comment by vishnu2kmohan** [comment]
Hi @mitsch, I just tried the same exact command but I was unable to reproduce the issue.

Would you please share the output of:

* `docker info`
* `docker network ls`
* `docker ps -a`
* `docker images`
* `sudo iptables -nvL`

Out of curiosity, is there a reason you're explicitly passing `--master-port 8080` to `det-deploy`? It defaults to port 8080 and shouldn't be necessary.

**Comment by mitsch** [comment]
Hi @vishnu2kmohan ,

when going through the outputs to copy-paste it here, I double-checked; and found the solution: proxy configuration interfered with the network setup. I suppose that only the agent-to-master connection has to be safeguarded from proxy since master and db are in their own subnetwork and traffic there is only inbound?

Nevertheless, thank you for nudging me in the right direction with the questions :).

About the port: It was just an act of despair.
