### ISSUE TITLE
Not possible to turn off telemetry via values.yaml

### ISSUE THREAD

**Issue by PeterSulcs** [determined-ai/determined#2175]
In the latest helm chart (0.5.0) it is not possible to disable telemetry via a `values.yaml` file:

https://github.com/determined-ai/determined/blob/master/helm/charts/determined/templates/master-config.yaml#L93

```
    {{- if .Values.telemetry }}
    {{- if .Values.telemetry.enabled }}
    telemetry:
      enabled: {{ .Values.telemetry.enabled }}
    {{- end }}
    {{- end }}
```

if `.Values.telemetry.enabled` is `false` this section is not added to the config yaml at all. Removing the inner-if statement results in the desired behavior.

**Comment by vishnu2kmohan** [comment]
Thanks for the report @PeterSulcs, we'll look into this...

**Comment by vishnu2kmohan** [comment]
Thanks to @dzhu for the [quick turnaround](https://github.com/determined-ai/determined/pull/2178), the fix should make our next official release.
