### ISSUE TITLE
在window环境怎么运行起来呢

### ISSUE THREAD

**Issue by liuyahui32** [determined-ai/determined#2262]

**Comment by vishnu2kmohan** [comment]
Hi @liuyahui32 did you mean to report an issue? If not, I'll close this out soon.

**Comment by vishnu2kmohan** [comment]
Apologies @liuyahui32, one of my colleagues (thanks @dzhu) pointed out that you were asking after Windows support, which is not something we support today. 

Users have tried deploying Determined on Windows via WSL2 but I don't think they've been successful.

@shiyuann Would you please help translate :point_up: : for me?

**Comment by shiyuann** [comment]
@liuyahui32 你好，我们暂时不支持Windows，但是有人成功在windows的linux子系统安装成功过。
