### ISSUE TITLE
Add "Active Filters" count and "Clear Filters" button to tables with filtering

### ISSUE THREAD

**Issue by ahj-determined** [determined-ai/determined#2584]
We recently switched to in-column filtering for tables. Users sometimes do not know what is being filtered, because it's shown by a small arrow or sometimes off the screen. Let's make it obvious that the tables are getting filtered by adding two components to tables with filtering:

- Active Filters count
- Clear Filters button

**Comment by hamidzr** [comment]
any tables with the inline filtering mechanism eg
- experiments
- tasks
