### ISSUE TITLE
Header fonts are hard to distinguish

### ISSUE THREAD

**Issue by off99555** [determined-ai/determined#2587]
![image](https://user-images.githubusercontent.com/15215732/122655241-29f47000-d17b-11eb-83e2-384b11a99c69.png)
I think the header font should look different from header level 2 and header level 3 or something like that.
Because it can be confusing whether `Manual Deployment` is a section that follows the previous one or it's the new section.
I was thinking that I need to follow everything when in fact I just need to follow `Deploying` section. This is because I mistakenly thought `Manual Deployment` was the required continuation of `Deploying` section.

Here is example of clear difference:
# Header 1
### Header 3

The above image came from https://docs.determined.ai/latest/how-to/installation/aws.html#aws-manual-deployment

**Comment by vishnu2kmohan** [comment]
Thanks for the feedback @off99555, we'll look into this and keep you posted.

**Comment by off99555** [comment]
Looks good!
