### ISSUE TITLE
Remove `State` from Trial Information / Trial Workloads [DET-5402]

### ISSUE THREAD

**Issue by rb-determined-ai** [determined-ai/determined#2599]
_Oooh! Github says this is my first issue!_

* Remove the `State` column from the Trial Information table under trial detail page.
* Remove any references of workload state
* Rename `src/utils/steps.ts` to `src/utils/workloads.ts` (just to further move away from steps completely)

blocked by DET-5429, "Trial substate/metadata API" (backend work)

**Comment by hamidzr** [comment]
once requirements for this tickets lands the pseudo workloads that we'll get are assumed to always be in a completed state? as in we either would have all the artifacts and metrics associated with a training/validation/checkpoint work or it won't be reported or exist at all ?

**Comment by rb-determined-ai** [comment]
I believe so.  @stoksc?

**Comment by hamidzr** [comment]
would checkpoints still have a deleted state?

**Comment by stoksc** [comment]
I believe it would just not be reported. That is an interesting idea, to just gc the checkpoints themselves but leave the metadata in postgres and mark it as DELETED. Not sure if it is useful.

**Comment by hamidzr** [comment]
> That is an interesting idea, to just gc the checkpoints themselves but leave the metadata in postgres and mark it as DELETED. Not sure if it is useful.
 
 I thought that was before sprinkledapi. Not reporting it all would seem simpler 👍🏼

**Comment by hamidzr** [comment]
landed in `upstream/push`
