### ISSUE TITLE
Update trial workloads to use new `totalBatchesProcessed` field instead of calculating it on the fly [DET-5403]

### ISSUE THREAD

**Issue by rb-determined-ai** [determined-ai/determined#2600]
The current total batches processed is calculated by adding `numBatches` + `priorBatchesProcessed` on a per workload basis (training, validation and checkpoints).

Infra may just do this ticket for us since it's easy to search and replace this portion. If WebUI is doing this work, will need to make sure this work is coordinated with the API work where runId and totalBatchesProcessed fields are introduced (and numBatches + priorBatchesProcessed is removed)

**Comment by hamidzr** [comment]
this seems to be already done
