### ISSUE TITLE
Add trial substate + metadata to Trial Detail summary box [DET-5404]

### ISSUE THREAD

**Issue by rb-determined-ai** [determined-ai/determined#2601]
Since workload / step state is being removed, the trial substate will be critical to display to the user so they know what's going on with the trial.

Start with adding the following format to the Summary Info Box:`State: [trial substate badge] <additional metadata for the substate as a text>`

**Comment by hamidzr** [comment]
@stoksc regarding trial substates do we know what the possible values are?  if so could we use an enum here

```
// The metadata pertaining to the current running task for a trial.
message TrialRunnerMetadata {
  option (grpc.gateway.protoc_gen_swagger.options.openapiv2_schema) = {
    json_schema: { required: [ "state" ] }
  };
  // The state of the trial runner.
  string state = 1;
}
```

**Comment by stoksc** [comment]
@hamidzr substates are not known in advance + we are adding an API (it's in a feature branch here https://github.com/determined-ai/determined/commit/d0375988fca42f894d8f32112948b787a5af0069)

**Comment by stoksc** [comment]
Oh wait.. i forgot to add the GET. I'll add it now.

**Comment by hamidzr** [comment]
> Oh wait.. i forgot to add the GET. I'll add it now.

we'd need it for this ticket. let me know if/when there is a pr up for this one. Or we need someone to take it

**Comment by stoksc** [comment]
@hamidzr GET is in, I amended the commit that adds the API on upstream/push

**Comment by hamidzr** [comment]
I pushed a commit for the bare min changes needed to expose the runner state. 
- [] add custom handlers for unspecified (if we want to keep that as a state)
- [] come up with a better UI/UX for displaying this.

**Comment by hamidzr** [comment]
I chatted with Alex and we explored a few different ways of showing the runner state.

![substate](https://user-images.githubusercontent.com/12127420/125142759-5a219580-e0cd-11eb-86c8-05eb32890427.png)

We're gonna go with using the stat boxes for now.

**Comment by hamidzr** [comment]
this is now pushed to `upstream/push`
