### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by BlueskyFR** [determined-ai/determined#2626]
Is Python 3.9 support planned?
I could not install on 3.9 using both a classic and a conda env

**Comment by vishnu2kmohan** [comment]
@BlueskyFR This is planned but there are some known issues with the frameworks (and their deep-dependencies, specifically) that's prevented us from moving up to python 3.9.

Would python 3.8 work for you, in the interim? And would you help us understand which features of python 3.9 are require for your use-case(s)?

**Comment by BlueskyFR** [comment]
Yeah I saw h5py not being compatible for instance if I remember correctly when installing determined.
Python 3,9 introduces the dictionnary merge operator for instance but I am personally looking forward to python 3,10 as there are big changes with the typing syntax (function return types); indeed, I think supporting 3,9 is a step towards supporting 3.10 :)
