### ISSUE TITLE
Docker determined-agent:latest tag not defined

### ISSUE THREAD

**Issue by BlueskyFR** [determined-ai/determined#2630]
First of all I am very sorry for posting this here because I did not know where to put it.

In some doc pages, it is mentionned to pull `determinedai/determined-agent` using these commands:
![image](https://user-images.githubusercontent.com/25421460/123694969-474fcb00-d85a-11eb-9f73-b09d97a9cfd0.png)
![image](https://user-images.githubusercontent.com/25421460/123694990-4f0f6f80-d85a-11eb-8bff-40522cbbaa21.png)

However, these command will fail with a manifest error from Docker because the `:latest` tag (`determinedai/determined-agent:latest`) is not defined on the image.
I suggest for it to be equals to the latest stable release, so `0.16.0` as of now.

It is important IMO as Docker tries to read `:latest` by default when nothing is specified, and thus allows your customers to always run the latest version.

**Comment by BlueskyFR** [comment]
Also, please note that the command shown on the first screen:
```bash
docker run \
  -v `pwd`/agent-config.yaml:/etc/determined/agent-config.yaml \
  determinedai/determined-agent
  --config-file /etc/determined/agent-config.yaml
```
Is false for 3 reasons:

1. A backslash is missing at line 3
2. The `--config-file` option is not supported by the determined-agent in the 0.16.0 release
3. The .yaml filename should be `agent.yaml` instead of `agent.yaml`

**Comment by vishnu2kmohan** [comment]
Thanks for the report @BlueskyFR, we'll fix this up.

**Comment by BlueskyFR** [comment]
Still no news?

**Comment by vishnu2kmohan** [comment]
Thanks to @dzhu, we will have `latest` tags pushed, for convenience, starting with the 0.16.5 release, expected later this week or early next week.

Thanks for the feedback @BlueskyFR!
