### ISSUE TITLE
Table UI doesn't show boolean value

### ISSUE THREAD

**Issue by off99555** [determined-ai/determined#2670]
This is snapshot from Learning Curve visualization of an experiment.
![image](https://user-images.githubusercontent.com/15215732/124670575-60055400-dede-11eb-887b-dbb74ff59253.png)
I expected the values in the red box to be shown as "True" or "False" (or maybe checkboxes?). It's a small bug though.
Following is how I defined the parameter
![image](https://user-images.githubusercontent.com/15215732/124670697-90e58900-dede-11eb-90f2-edd188ca8675.png)

**Comment by vishnu2kmohan** [comment]
Thanks for the bug report @off99555, we'll look into fixing this up.

**Comment by hamidzr** [comment]
aah I see what's going wrong here. I'll put up a fix.
