### ISSUE TITLE
Expose trial logs to be more easily accessible in experiments

### ISSUE THREAD

**Issue by hkang1** [determined-ai/determined#2714]
Make trial logs more readily available for debugging.

ISSUE:
Trial logs are harder to access and require an extra drill down to access.

PROPOSAL:
Add overflow column to experiment trials table (multi-trial only) and add `View Logs` under the overflow menu.

https://determinedai.atlassian.net/browse/DET-5643

**Comment by hamidzr** [comment]
another alternative to an overflow could be to show the icons inline to the row maybe as a new column or mixed with checkpoint? 

![image](https://user-images.githubusercontent.com/12127420/125367103-648d9a80-e32c-11eb-91a5-92aabd32c560.png)

any thoughts @alexjdetermined ?
