### ISSUE TITLE
WebUI: Investigate and fix issue of streaming endpoints not terminating properly

### ISSUE THREAD

**Issue by hkang1** [determined-ai/determined#2715]
Currently we are using HTTP standard `AbortController` to terminate gRPC streaming endpoints. It doesn't seem like it is working. It is noticeable when viewing hp visualizations. When clicking around the various graphs in hp-viz, multiple streaming endpoints are called, but after about 4th click, the page will show a spinner. If we look at the `Network` tab on the browser, we'll observe that the latest streaming endpoint call ends up in a `Pending` state because there were about 8~12 gRPC streaming endpoints that are still open and have not terminated yet.

**Comment by hamidzr** [comment]
this would probably only recreate in active experiments correct? otherwise the stream closes

**Comment by hamidzr** [comment]
a separate issue but we can probably get these two streaming request to be closed by the server in terminal states
```
curl 'http://xyz/api/v1/trials/2692/logs/fields?follow=true' \
  --compressed \
  --insecure

curl 'http://MYSERVER/api/v1/experiments/1828/hyperparameter-importance' \
  --compressed \
  --insecure
```

**Comment by hamidzr** [comment]
the abort signal seems to work as expected. It's looking like we don't trigger it as expected in some places in the UI.

**Comment by hkang1** [comment]
> this would probably only recreate in active experiments correct? otherwise the stream should close

Yeah I that sounds right. I tried clicking around on hp-viz out on a terminal completed (multi-trial) experiment and it seems totally fine. The network tab is showing the hp-trial-metric endpoints ending as well.

**Comment by hkang1** [comment]
> https://github.com/hamidzr/determined/tree/stream-abort

I see, thanks, this was REALLY helpful. Looking again at the hp-viz section, it's possible the cleanup portion in the `useEffects` are not calling the cleanup callback properly. I'll take a look.

**Comment by hkang1** [comment]
Thanks for the thorough investigation!
