### ISSUE TITLE
Add support for experiment DELETE on the WebUI

### ISSUE THREAD

**Issue by hkang1** [determined-ai/determined#2752]
Blocked on this [PR](https://github.com/determined-ai/determined/pull/2741) landing.

**NOTE** Experiment delete is only available to Admin users.

Experiment List page
- add `Delete` option to overflow menu for each experiment row
- show modal delete confirmation and send Rest API call upon confirmation. The state should change to `DELETING` upon a successful call.

Experiment Detail page
- add `Delete` option to experiment action bar in the header (within the overflow menu).
- show modal delete confirmation and send Rest API call upon confirmation. The state should change to `DELETING` upon a successful call.

https://determinedai.atlassian.net/browse/DET-5244

**Comment by hamidzr** [comment]
this would mean that from the webui POV terminal states are no longer as terminal..

**Comment by hamidzr** [comment]
do we want this to be an admin only feature?

**Comment by hamidzr** [comment]
> this would mean that from the webui POV terminal states are no longer as terminal..

we can avoid this complexity if we just send the user out of the experiment detail page when their deletion request is received successfully

**Comment by hamidzr** [comment]
do we get asked to support a bulk action for this?

**Comment by hkang1** [comment]
> do we get asked to support a bulk action for this?

we didn't but I could see that being really convenient to have!
