### ISSUE TITLE
Dash char ("-") invalid in entrypoint module name

### ISSUE THREAD

**Issue by BlueskyFR** [determined-ai/determined#2770]
When using a file, say named `basic.yaml`:
```yaml
...
entrypoint: imagenet-determined:ImageNetTrial
...
```
The dash ("-") in the module name is not recognized as part of the module name. Indeed, the command `det experiment create basic.yaml .` gives the following error:
```
Failed to create experiment: invalid experiment: invalid experiment configuration: version 0 experiment config is invalid: config is invalid: <config>.entrypoint: entrypoint must be of the form "module.submodule:ClassName"
```

From what the [Python spec](https://packaging.python.org/specifications/entry-points/) says, it looks to me that the dashes are allowed in the module names, though I could be wrong.

**Comment by rb-determined-ai** [comment]
They are talking about an `entrypoint` that is an unrelated concept to our `entrypoint`.  That doc is talking about python packaging concepts.  Our `entrypoint` in our config is a reference to a class in a python module.  It's most similar to this phrase from the docs:

> The object reference points to a Python object. It is either in the form `importable.module`, or `importable.module:object.attr`. Each of the parts delimited by dots and the colon is a valid Python identifier.

A python identifier can't have a dash in it, or python would interpret it as subtraction of `determined` from `imagenet`.

If you try to run `import imagenet-determined` from a python interpeter you'll get a syntax error.

**Comment by BlueskyFR** [comment]
Thanks for the clarification @rb-determined-ai!
I was actually quoting the Python specs because the Determined documentation links to it.

Now closing this issue then!
