### ISSUE TITLE
Replace Save checkpoint and stop checkbox with a button

### ISSUE THREAD

**Issue by ahj-determined** [determined-ai/determined#2793]
Currently, when a user clicks "Stop", they have the option to check the checkbox of "Save checkpoint before stopping experiment". This has 2 issues: 1) the default options does not save existing work and 2) saving a checkpoint requires two click. Instead, let's replace it with a button:

- Remove  "Save checkpoint before stopping experiment" checkbox
- Add a button, so the three buttons would be 1) "Cancel" 2) "Stop Now" and 3) "Save Checkpoint and Stop"

**Comment by hkang1** [comment]
@EmilyBonar is working on this via [this PR](https://github.com/determined-ai/determined/pull/2894)
