### ISSUE TITLE
where is the determined.pytorch package on source code?

### ISSUE THREAD

**Issue by brollinli** [determined-ai/determined#2809]
If this platform was open source, but I can’t find some codes, such as pytorch or tensorflow and more , I’m need help to using the code !

**Comment by vishnu2kmohan** [comment]
The code for the PyTorch module is under [harness/determined/pytorch](https://github.com/determined-ai/determined/tree/master/harness/determined/pytorch)

Likewise you'll find the code for managing frameworks that we support under [harness/determined](https://github.com/determined-ai/determined/tree/master/harness/determined)

**Comment by vishnu2kmohan** [comment]
What kind of help are you looking for @brollinli?

We'd be happy to help out over in our [slack](https://join.slack.com/t/determined-community/shared_invite/zt-cnj7802v-KcVbaUrIzQOwmkmY7gP0Ew) channel.

**Comment by brollinli** [comment]
thanks for your msg, i got it .
