### ISSUE TITLE
WebUI doesn't plot metric when its value is zero

### ISSUE THREAD

**Issue by off99555** [determined-ai/determined#2860]
When the metric reports value=0, the web UI refuses to plot it. (But it's plotted in the top 100 visualization)
I expeced it to plot a line like what I drawn with red.
![image](https://user-images.githubusercontent.com/15215732/130206805-5e3be2d0-1b27-420e-b2f6-ef06fd20e9c7.png)

**Comment by vishnu2kmohan** [comment]
Thanks for the report @off99555, we'll look into this...

**Comment by hkang1** [comment]
[This PR](https://github.com/determined-ai/determined/pull/2863) will fix this issue. It will be part of our next release!

**Comment by off99555** [comment]
Cool!
