### ISSUE TITLE
tests: fix tasks batch action test flake

### ISSUE THREAD

**Issue by hamidzr** [determined-ai/determined#2872]
two instances
https://app.circleci.com/pipelines/github/determined-ai/determined/14918/workflows/cbe93d30-7177-443a-a9c7-eae8e80203e2/jobs/448031
https://app.circleci.com/pipelines/github/determined-ai/determined/14916/workflows/1688dda3-8f95-4fba-9a7c-7a6717d377b5/jobs/447985

circleci stats show a 16%  decrease in pass rate for it to 76%

**Comment by hkang1** [comment]
> the issue seems to be that when the test runner goes to click 'kill" dropdown action it does it fast enough that it somehow clicks through the dropdown and onto the "select all" checkbox.
> 
> 0:20 to 0:24
> 
>  Clean.Up.mp4

On the batch operations, it programmed to deselect everything upon a confirmation of the batch operation (such as Kill)

**Comment by hamidzr** [comment]
it doesn't seem to get to the confirmation though, fails to actually click on kill

**Comment by hkang1** [comment]
> it doesn't seem to get to the confirmation though, fails to actually click on kill

Ah you're right, it doesn't look like it gets to the confirmation `kill` button...
