### ISSUE TITLE
prepare for new node LTS (v16)

### ISSUE THREAD

**Issue by hamidzr** [determined-ai/determined#2919]
tracking what needs to be updated

1. webui e2e tests don't run (gauge related?)

**Comment by hkang1** [comment]
One issue I came across with `npm v7` was around `npm-force-resolutions` not working the same as before. So I remember have a really tough time resolving package security issues w/ npm v7.

**Comment by hamidzr** [comment]
IIRC this is related https://determined-community.slack.com/archives/C024Z5WELBH/p1625077270022200

**Comment by hamidzr** [comment]
moved to jira
