### ISSUE TITLE
Static type checker for Pytorch custom metric reducer

### ISSUE THREAD

**Issue by felix-schneider** [determined-ai/determined#2926]
If I use `wrap_reducer` to wrap a simple python function, I get back a `_SimpleReducer` instance, which supports the `update()` method which is not in `MetricReducer`. As a result, the static type checker complains.

![Screenshot 2021-09-08 152930](https://user-images.githubusercontent.com/208336/132518636-7bd3c56a-4b8d-46d6-aada-67373ecc798d.png)

This could be fixed by defining an overload:

```python
@overload
def wrap_reducer(
        self,
        reducer: Callable[List,Dict[str,float]],
        name: Optional[str] = None,
        for_training: bool = True,
        for_validation: bool = True,
    ) -> _SimpleReducer:
    ...
```

**Comment by vishnu2kmohan** [comment]
@rb-determined-ai have you perhaps already addressed this request, and if not would you? :pray:

**Comment by rb-determined-ai** [comment]
Better [late](https://github.com/determined-ai/determined/pull/3764) than never, right?

Sorry for the slow response on this one, @fe
