### ISSUE TITLE
Feature request: a `.finally()` method or similar for `det.Trial` class

### ISSUE THREAD

**Issue by harpone** [determined-ai/determined#3082]
I'm using the pytorch profiler with weights and biases, and would need to upload the saved profile traces to weights and biases after training. Also logging some custom stuff that's stored as attributes of the `det.PyTorchTrial` class.

It would be nice to have a `.finally()` method or similar where I could wrap up stuff like that at the end of training...

Open to ideas how to hack around this in the meantime!

**Comment by vishnu2kmohan** [comment]
Hi @harpone; welcome, and thanks for your feedback!

We'll look into this (cc @rb-determined-ai @shiyuann) and let you know.

In the meanwhile, I wanted to point out that PyTorch-native profile traces can be viewed via TensorBoard from within Determined, if that's an adequate workaround?

Out of curiosity, what kinds of visualizations or interactions or analysis are you relying on in Weights & Biases that the Determined WebUI does not provide? cc @alexjdetermined

**Comment by rb-determined-ai** [comment]
[Better late than never](https://github.com/determined-ai/determined/pull/3643), right?

@harpone Sorry for the delay on this, it is a pretty reasonable request.  It should be available in 0.17.11.
