### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by CnybTseng** [determined-ai/determined#3176]
[2021-11-09 03:04:05] 26fa7420 || INFO: Loading Trial implementation with entrypoint model:MobileViTTrial.
<info> [2021-11-09 03:04:05] 26fa7420 || Traceback (most recent call last):
<info> [2021-11-09 03:04:05] 26fa7420 ||   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
<info> [2021-11-09 03:04:05] 26fa7420 ||     return _run_code(code, main_globals, None,
<info> [2021-11-09 03:04:05] 26fa7420 ||   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
<info> [2021-11-09 03:04:05] 26fa7420 ||     exec(code, run_globals)
<info> [2021-11-09 03:04:05] 26fa7420 ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/launch_autohorovod.py", line 194, in <module>
<info> [2021-11-09 03:04:05] 26fa7420 ||     sys.exit(main())
<info> [2021-11-09 03:04:05] 26fa7420 ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/launch_autohorovod.py", line 55, in main
<info> [2021-11-09 03:04:05] 26fa7420 ||     return harness.main()
<info> [2021-11-09 03:04:05] 26fa7420 ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/harness.py", line 82, in main
<info> [2021-11-09 03:04:05] 26fa7420 ||     controller = load.prepare_controller(
<info> [2021-11-09 03:04:05] 26fa7420 ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/load/_trial.py", line 124, in prepare_controller
<info> [2021-11-09 03:04:05] 26fa7420 ||     trial_class = trial_class_from_entrypoint(env.experiment_config["entrypoint"])
<info> [2021-11-09 03:04:05] 26fa7420 ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/load/_trial.py", line 59, in trial_class_from_entrypoint
<info> [2021-11-09 03:04:05] 26fa7420 ||     check.check_issubclass(
<info> [2021-11-09 03:04:05] 26fa7420 ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/common/check.py", line 321, in check_issubclass
<info> [2021-11-09 03:04:05] 26fa7420 ||     return is_subclass(val, expected, reason)
<info> [2021-11-09 03:04:05] 26fa7420 ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/common/check.py", line 310, in is_subclass
<info> [2021-11-09 03:04:05] 26fa7420 ||     if issubclass(val, expected):
<info> [2021-11-09 03:04:05] 26fa7420 ||   File "/opt/conda/lib/python3.8/abc.py", line 102, in __subclasscheck__
<info> [2021-11-09 03:04:05] 26fa7420 ||     return _abc_subclasscheck(cls, subclass)
<info> [2021-11-09 03:04:05] 26fa7420 || TypeError: issubclass() arg 1 must be a class
<info> [2021-11-09 03:04:06] 26fa7420 || INFO: container failed with non-zero exit code: container failed with non-zero exit code: 1 (exit code 1)

**Comment by varlogtim** [comment]
@CnybTseng Could you share a cleaned copy of your `model.py` which shows the `class MobileViTTrial` definition?

**Comment by vishnu2kmohan** [comment]
@CnybTseng Ping :point_up:, or please let us know if we can close out this issue.

**Comment by rb-determined-ai** [comment]
This function was re-written a couple weeks before this ticket, and this failure is not possible anymore.

If the user passes a non-class as the entrypoint, it first checks if `istype(entrypoint_obj, type)` before checking `issubclass(entrypoint_obj, det.Trial)`.
