### ISSUE TITLE
checkpoint_storage should allow setting path in bucket

### ISSUE THREAD

**Issue by hwaxxer** [determined-ai/determined#3184]
When using `checkpoint_storage` with type `s3` or `gcp` it should be possible to select a key/path in the bucket where the checkpoints are stored. This would allow the use of one bucket for all training artifacts, eg checkpoints, data layer cache etc.

**Comment by vishnu2kmohan** [comment]
I'll defer to @varlogtim here, but we recently landed this https://github.com/determined-ai/determined/commit/a580ed5d2bfb426cd2c1eade39cadfec4326478e which should be out in the 0.17.3 release next week and _should_ address your request?

**Comment by varlogtim** [comment]
Correct. The change @vishnu2kmohan  mentioned adds supports the use of a `prefix` for `checkpoint_storage` types of `s3`.

We _should_ be adding support for `prefix`es in `gcs` very shortly. 

The `DataLayer` currently supports prefixes via the `bucket_directory_path` for `s3`.

**Comment by rb-determined-ai** [comment]
@varlogtim did we finish this work for gcs too?

**Comment by varlogtim** [comment]
Hrmm.... It looks like I never actually did this for GCS. @rb-determined-ai  I can add this feature in the next week or two, unless someone else wants to take this as a easy add?

**Comment by varlogtim** [comment]
This was done by @NicholasBlaskey
