### ISSUE TITLE
How to integration with DeepSpeed?

### ISSUE THREAD

**Issue by slyviacassell** [determined-ai/determined#3187]
I know that `deepspeed` has direct interaction with `transformers` or `pytorch-ligntning` .  Does this mean determined could be integrated with it? Or, this feature works in progress?

**Comment by vishnu2kmohan** [comment]
Hi @slyviacassell, I hope you'll be pleased to learn that we already have a working prototype training [gpt-neox](https://github.com/determined-ai/DeepSpeed) via [DeepSpeed](https://github.com/determined-ai/DeepSpeed) with ZeRo (3D Parallelism).

The full-fledged integration - i.e., beyond the prototype linked to above, is actively being worked on...

cc @liamcli @shiyuann 

We'd love if you would discuss your plans.

- What kinds of models/architectures do you wish to train?
- How large are your models (number of parameters) and what are your scale requirements (nodes and/or GPUs)?
- What kind of learning approaches (supervised, semi-supervised, self-supervised, etc.,) should we consider supporting?
- Any other technologies, libraries, frameworks, etc., you’d like us to consider?

**Comment by slyviacassell** [comment]
@vishnu2kmohan Thanks for your inspiring response. As far as I know, we could activate `deepspeed` by using `bash command` shown in the docs of `transformers` and `pytorch-lightning`. However, the determined have wrapped the initialization of distributed training, and there is no need to use `bash command`. My question is actually about the wrap layer of `determined`. I would like to figure out whether the developers have done it or are planning to develop it.

**Comment by vishnu2kmohan** [comment]
Hi @slyviacassell 

> My question is actually about the wrap layer of determined. I would like to figure out whether the developers have done it or are planning to develop it.

Yes, as mentioned earlier, we're actively working on the integration - i.e., our engineers are developing it:

> The full-fledged integration - i.e., beyond the prototype linked to above, is actively being worked on...

Is there something you'd like us to clarify about our integration/implementation - i.e., we'd like to understand the question/motivation behind your question below:

> My question is actually about the wrap layer of determined. I would like to figure out whether the developers have done it or are planning to develop it.
