### ISSUE TITLE
When launch a agent without gpu  use "det deploy local agent-up --no-gpu  <master_hostname>", but launch a agent with gpu.

### ISSUE THREAD

**Issue by 18724799167** [determined-ai/determined#3195]
![Picture2](https://user-images.githubusercontent.com/31273093/141891458-3ec76250-3dc2-49d6-afae-7c71801da88d.png)

**Comment by vishnu2kmohan** [comment]
Hello @18724799167 I'm not sure I understand the issue.

Are you saying that you have an agent that has GPUs in it that you'd like to register with the master but have it pretend/behave like it doesn't have GPUs - i.e., you don't want its GPUs advertised to the master? (If so, would you help us understand why you want to use/enable this sort of setup?)

cc @shiyuann @varlogtim

**Comment by vishnu2kmohan** [comment]
Hi @18724799167 have you managed to resolve the issue, and if so, is it safe to close this issue?

**Comment by vishnu2kmohan** [comment]
Please reopen if necessary.
