### ISSUE TITLE
Failed to change password for user: Forbidden(user not authorized): Please contact your administrator in order to access this resource.

### ISSUE THREAD

**Issue by hqsam** [determined-ai/determined#3261]
after install the determined,   I can not change the password.  When I type : det user change-password, the following error will occur.:

Failed to change password for user: Forbidden(user not authorized): Please contact your administrator in order to access this resource.

**Comment by vishnu2kmohan** [comment]
Hi @hqsam, are you sure you're already logged in as the user whose password you're attempting to change?

What does `det user whoami` say?

Note: You can always change the password for any user by assuming the admin role - i.e., via `det -u admin change-password <username>`

Ref: [Users](https://docs.determined.ai/latest/sysadmin-basics/users.html#getting-started)

**Comment by vishnu2kmohan** [comment]
Hi @hqsam ping :point_up:, or please let us know if we can close out this issue.

**Comment by vishnu2kmohan** [comment]
Please reopen if necessary.
