### ISSUE TITLE
tasks keep pending

### ISSUE THREAD

**Issue by DeriZSY** [determined-ai/determined#3337]
Hi, I met a problem of pending tasks when trying to execute some shell commands like `det cmd run nvidia-smi` or when try to open a JupyterNote book through the Web UI.

I can see the tasks on the Web UI and logs like:
```
resources are requested by /commands/7f2a7497-57ae-4c4b-b508-8d9f2ecb2ef7/7f2a7497-57ae-4c4b-b508-8d9f2ecb2ef7.1 (Allocation ID: 7f2a7497-57ae-4c4b-b508-8d9f2ecb2ef7.1)  id="default" resource-pool="default" system="master" type="ResourcePool"
```
however, the tasks kept pending and waiting for scheduling. 

I noticed the issue here and tried to update network settings as suggested which doesn't help: https://github.com/determined-ai/determined/issues/1743

I also met the problem as mentioned in: https://github.com/determined-ai/determined/issues/3318 whichever versions I used (tried 0.17.3 and 0.17.5)

Not sure if there are some connections between the problems.

**Comment by DeriZSY** [comment]
Also notice like related to network 
```
[2021-12-17 11:40:45] error while actor was running  error="websocket: close 1001 (going away)" id="websocket-57e7efe1-f6fa-4506-a133-9fe0aa790012" system="master" type="websocketActor"
<error> [2021-12-17 11:40:45] websocket: close 1001 (going away)
<error> [2021-12-17 11:40:45] http: connection has been hijacked
```

**Comment by DeriZSY** [comment]
The firewall on my master device has always been inactivated. So it may not be a firewall problem as mentioned in https://github.com/determined-ai/determined/issues/1743

**Comment by DeriZSY** [comment]
Problem solved. In my case, this may due to incorrect setup between agent and masters

**Comment by Taited** [comment]
> Problem solved. In my case, this may due to incorrect setup between agent and masters

Hi, I met the same issue as yours. Could you share more details of the setup?
