### ISSUE TITLE
Advanced user management setting to limit the runtime/priority/resource pool for users

### ISSUE THREAD

**Issue by DeriZSY** [determined-ai/determined#3338]
Hi, I've read through the documents and seems like the only thing admin can do is to activate/deactivate other users.

I'm wondering how can the admin of the system limit the performance of other users? For example, limit resources used or the priority of tasks created by certain groups of users? 

I also found that anyone can kill the tasks executed by some others on the Web UI which seems quite unreasonable to me.

**Comment by DeriZSY** [comment]
> Hi @DeriZSY, this is a feature that we have on our roadmap for the enterprise version of the open-source Determined project - i.e., [HPE Cray AI Development Environment](https://hpe.com/ai/cray-ai-development-environment).
> 
> Note: Advanced resource management (e.g., time and user-based limits, resource quota, etc.), authorization (AuthZ) and authentication (AuthN) features & capabilities will primarily be targeted for and made available in the commercially supported offering ☝️.

Thanks for the reply! The advanced resource management features you mentioned (time and user limits, quotas ...) are just what we've been looking for. And I'd like to pay for that for sure. I will take a look at the link you've provided.

**Comment by DeriZSY** [comment]
> Hi @DeriZSY, this is a feature that we have on our roadmap for the enterprise version of the open-source Determined project - i.e., [HPE Cray AI Development Environment](https://hpe.com/ai/cray-ai-development-environment).
> 
> Note: Advanced resource management (e.g., time and user-based limits, resource quota, etc.), authorization (AuthZ) and authentication (AuthN) features & capabilities will primarily be targeted for and made available in the commercially supported offering ☝️.

Hey, I'm wondering where can I find detailed information about the commercially supported version of Determined.ai? It hard to navigate it directly from the main website here: https://www.hpe.com/us/en/compute/hpc/cray-ai-development.html

**Comment by vishnu2kmohan** [comment]
Hi @DeriZSY would you like to be put in touch with our sales team to explore the commercially supported version?

cc @hoang-determined-ai
