### ISSUE TITLE
What is the best practice for binding context directories when the .git in the project directory exceeds 100M?

### ISSUE THREAD

**Issue by tshu-w** [determined-ai/determined#3358]
Is there any way exclude some folder?

https://docs.determined.ai/latest/features/commands-and-shells.html?highlight=context#context-directories

**Comment by vishnu2kmohan** [comment]
By default we _should_ be [ignoring](https://github.com/determined-ai/determined/blob/0.17.5/harness/determined/common/constants.py#L56) `.git` and few other common directories, the list of which can be extended by [creating](https://docs.determined.ai/latest/training-apis/trial-api.html?highlight=detignore#create-an-experiment-via-the-cli) a `.detignore` file in the base (of your context) directory.

Are you only seeing this error when creating non-experiments (notebooks, shells, commands) with a context directory (and via the CLI) @tshu-w? IOW would you please share the instructions for us to reproduce the issue you're witnessing?

cc @ioga @varlogtim

**Comment by tshu-w** [comment]
@vishnu2kmohan Hi, Thank you for quick reply. I haven't tried directly, just saw the documentation [here](https://docs.determined.ai/latest/features/commands-and-shells.html?highlight=context#context-directories) with a little doubt. If this is not just a feature of the Trial API, it shouldn't be mentioned somewhere more easy to find.
