### ISSUE TITLE
How to get the userid, taskid and gpuid?

### ISSUE THREAD

**Issue by loriqing** [determined-ai/determined#3370]
Hello, I want to know the names and ids of tasks created by users, and want to know which GPUs these tasks are running on. But I don't know how to get this data.

**Comment by vishnu2kmohan** [comment]
Hi @loriqing does the output of `det slot` and `det agent` help?

**Comment by loriqing** [comment]
> 

I can get the agent ID, Allocation ID, Task Name by using `det slot` and `det agent`. And how to know the username? If two users use the same task name, I want to distinguish between them.

**Comment by loriqing** [comment]
try `det cmd list -a` can get these information
