### ISSUE TITLE
Update cluster endpoint for Kubernetes clusters

### ISSUE THREAD

**Issue by hkang1** [determined-ai/determined#3419]
- add a new field `numSlots` that returns the total number of slots across all nodes
- update `numAgents` (already exists) from a hard coded `1` to actual number of nodes

***Related observation below maybe resolved if the above task is complete.***

For kubernetes cluster...

When calling `/api/v1/resource-pools` the pool object returns `numAgents` of `1`, but `/api/v1/agents` will be an empty array.

This can be observed here: http://34.127.77.240:8080/det/cluster

Run a job and view the Cluster page. The stats box is reporting the `agents` endpoint (empty array) so `0 connected agents` but down below the pool card shows `1 connected agent` due to `numAgents` set to `1`.

**Comment by hamidzr** [comment]
https://determinedai.atlassian.net/browse/DET-6411?jql=text%20~%20%22cluster%20kubernetes%22
