### ISSUE TITLE
webui test issue with sign in. username input not found

### ISSUE THREAD

**Issue by hamidzr** [determined-ai/determined#3444]
https://determined-community.slack.com/archives/C025A98H82X/p1642000525012800

https://app.circleci.com/pipelines/github/determined-ai/determined/18114/workflows/7d209555-aafd-4abc-a7be-066c93b8492e/jobs/556400

**Comment by hamidzr** [comment]
@hkang1 landed a fix for this. Is that holding up well?

**Comment by hkang1** [comment]
> @hkang1 landed a fix for this. Is that holding up well?

Hard to tell at this point. I took a look at some stats on the circleci app and I don't see much of sign in tests failing but still a bit early to tell IMO
