### ISSUE TITLE
integrate with Lightning ecosystem CI

### ISSUE THREAD

**Issue by Borda** [determined-ai/determined#3485]
Hello and so happy to see you use Pytorch-Lightning! :tada: 
Just wondering if you already heard about quite the new **Pytorch Lightning (PL) ecosystem CI** where we would like to invite you to... You can check out our blog post about it: [Stay Ahead of Breaking Changes with the New Lightning Ecosystem CI](https://devblog.pytorchlightning.ai/stay-ahead-of-breaking-changes-with-the-new-lightning-ecosystem-ci-b7e1cf78a6c7) :zap: 
As you use PL framework for your cool project, we would like to enhance your experience and offer you safe updates to our future releases. At this moment, you run tests with a particular PL version, but it may accidentally happen that the next version will be incompatible with your project... :confused: We do not intend to change anything on our project side, but still here we have a solution - ecosystem CI with testing both - your and our latest development head we can find it very early and prevent releasing eventually bad version... :+1: 

**What is needed to do?**
- have some tests, including PL integration
- add config to ecosystem CI - https://github.com/PyTorchLightning/ecosystem-ci

**What will you get?**
- scheduled nightly testing configured for development/stable versions
- slack notification if something went wrong to investigate
- testing also on multi-GPU machine as our gift to you :rabbit:

**Comment by mackrorysd** [comment]
@Borda Is the goal to avoid incompatibilities in PyTorch Lightning releases, or only provide earlier warning of them? For instance, if a test started failing, would that be considered a release-blocker for PyTorch Lightning by default? Or would it only serve as a notice that the next release would be incompatible in a breaking way?

**Comment by Borda** [comment]
> @Borda Is the goal to avoid incompatibilities in PyTorch Lightning releases, or only provide earlier warning of them? For instance, if a test started failing, would that be considered a release-blocker for PyTorch Lightning by default? Or would it only serve as a notice that the next release would be incompatible in a breaking way?

it s a very good question and I think it is case by case, so if it'll be something critical that many users use we may consider reverting this change even before release... if it is just something like a project is accessing a protected method which is not meant to be exposed to user I think it ll be just warning... :rabbit:

**Comment by rb-determined-ai** [comment]
We'll consider this with the team.
