### ISSUE TITLE
Delete task by another user, it work

### ISSUE THREAD

**Issue by sijin-dm** [determined-ai/determined#3761]
When I create a task by user A, then login with user B. When B click on the `Kill` button to the task created by A, the task is terminated!
Is this a expected behavior or a bug in RBAC?

**Comment by rb-determined-ai** [comment]
Hi @sijin-dm, this is not a "bug in RBAC", this is "we don't really have RBAC at all".  Not yet anyway, we have plans to work on it.  We know it is a missing feature.

**Comment by sijin-dm** [comment]
> Hi @sijin-dm, this is not a "bug in RBAC", this is "we don't really have RBAC at all". Not yet anyway, we have plans to work on it. We know it is a missing feature.

Got it. Thanks for your reply.
