### ISSUE TITLE
Restart determined master, task tracking log disappear.

### ISSUE THREAD

**Issue by sijin-dm** [determined-ai/determined#3762]
Hi there, 
I restart the determined server only, but the `cmd` history is disappeared. The postgres docker is not restarted. The user list is still remained. I am curious about what is versioning in determined master and where will they save. From the current phenomenon, I guess the user management table is saved in postgres, and `checkpoint` is saved in the given `checkpoint_storage` location. What about the experiment and task log ?

**Comment by ioga** [comment]
Currently, experiments is the only task type that persists on master restarts. Notebooks-tensorboards-commands do not, but persisting them is on the roadmap.

Sorry for the delay.
