### ISSUE TITLE
Jupyterlab can see all the gpu when slot=0

### ISSUE THREAD

**Issue by sijin-dm** [determined-ai/determined#3820]
Hi there,
I set slot to 0 when I start jupyterlab. However, I can see all the gpu there! Even though the avaibable gpu number does not change on dashboard and inside the cluster.

**Comment by neilconway** [comment]
@sijin-dm Can you confirm how you started Jupyterlab? e.g., was it via the CLI or the WebUI? If via the CLI, can you provide the exact command-line that you used?

**Comment by sijin-dm** [comment]
I start it via webui:
![image](https://user-images.githubusercontent.com/61957607/160639140-0fb97f15-9114-4b8f-ae63-adf6530c771b.png)

**Comment by rb-determined-ai** [comment]
Which version of Determined are you running with?

**Comment by sijin-dm** [comment]
> Which version of Determined are you running with?

0.17.11

**Comment by eecsliu** [comment]
Hi @sijin-dm, can you show us the output of `kubectl describe pod` on the jupyterlab pod?

**Comment by eecsliu** [comment]
Hmmm this is interesting because in both Determined and the kubernetes cluster, the resource request is gpu = 0. Can you check the environment variables inside the notebook? I'm interested in the value of `DET_SLOT_IDS`.

**Comment by sijin-dm** [comment]
> 
`DET_SLOT_IDS` is empty. 
![image](https://user-images.githubusercontent.com/61957607/161359369-8616ecca-54d3-4fb0-af8b-2bc0c8f7580e.png)
And I did not set the `defaultScheduler` in `values.yaml`, just use the default one.

**Comment by eecsliu** [comment]
It doesn't look to me that Determined is doing anything weird here - the resource requests and the internal environment vars look correct.

Can you try the following:
- create a simple kubernetes pod that just sleeps so you can `kubectl exec` inside to probe if necessary
- try different resource requests (`nvidia.com/gpu:0` or `nvidia.com/gpu:1`)
- see how it affects visible GPUs in the determined cluster + if you can access GPUs from inside the container

**Comment by sijin-dm** [comment]
> It doesn't look to me that Determined is doing anything weird here - the resource requests and the internal environment vars look correct.
> 
> Can you try the following:
> 
> * create a simple kubernetes pod that just sleeps so you can `kubectl exec` inside to probe if necessary
> * try different resource requests (`nvidia.com/gpu:0` or `nvidia.com/gpu:1`)
> * see how it affects visible GPUs in the determined cluster + if you can access GPUs from inside the container

1. When I set `nvidia.com/gpu:1` in the simple pod, the visible GPUs in the determined cluster does not change. Is this expected? 
2. When I set `nvidia.com/gpu:0`, this pod can access all the gpus...... So this is not the problem for determined, but k8s?

**Comment by eecsliu** [comment]
Yes, if this is the case for the simple pod, then it seems like something is preventing kubernetes from account the nvidia gpu requirement. How did you install the nvidia driver on your cluster?

**Comment by sijin-dm** [comment]
> Yes, if this is the case for the simple pod, then it seems like something is preventing kubernetes from accounting the nvidia gpu requirement. How did you install the nvidia driver on your cluster?

We use gpu-operator to manage the nvidia driver.

**Comment by eecsliu** [comment]
Hmmm the gpu-operator should be fine... Are you running on a cloud solution or an on-premise cluster? There are a couple of alternatives to the operator you can try. It may depend on your platform, but there is the [GCP daemonset](https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml) or the [nvidia device plugin](https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/master/nvidia-device-plugin.yml) to name a few.

**Comment by sijin-dm** [comment]
It have been fixed in the latest version.
