### ISSUE TITLE
.detignore does not follow .gitignore syntax

### ISSUE THREAD

**Issue by BlueskyFR** [determined-ai/determined#3951]
Hey!
It seems like in the `.gitignore`  syntax, adding `/*` ignores directories whereas in Determined's `.detignore`, `/*/` should also be added to ignore them.
It think it is due to these two lines -> https://cs.github.com/determined-ai/determined/blob/bb4050fe6f5a02385c78bc5eb79f7110523531af/harness/determined/common/context.py#L142-L143
However, as per git's gitignore doc:
> If there is a separator at the end of the pattern then the pattern will only match directories, otherwise the pattern can match both files and directories.

Determined's documentation says that `.detignore` follows `.gitignore` syntax which appears to be wrong, so it must be fixed.

It took me a few hours to debug since I had to dig in Determined's source code & I wrote a script that replicates the way it is currently matching files, so I think fixing this can save time to some people 😉

**Comment by rb-determined-ai** [comment]
hey, this finally [got fixed](https://github.com/determined-ai/determined/pull/4998), sorry for the long delay.
