### ISSUE TITLE
command(det experiment create const.yaml .) run failed

### ISSUE THREAD

**Issue by kelvinwang139** [determined-ai/determined#3969]
Hi，
Firstly thanks for your contribution for this project. When I complished the setting up the project and tried to run a training job and the following error happened. could you please provide some clues? Thanks a lot!

(determined) userr@user:~/ai/mnist_pytorch$ det experiment create const.yaml .
Traceback (most recent call last):
  File "/home/cyuser/anaconda3/envs/determined/lib/python3.7/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/cyuser/anaconda3/envs/determined/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/cyuser/anaconda3/envs/determined/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/cyuser/anaconda3/envs/determined/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
**json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cyuser/anaconda3/envs/determined/lib/python3.7/site-packages/determined/cli/cli.py", line 204, in main
    check_version(parsed_args)
  File "/home/cyuser/anaconda3/envs/determined/lib/python3.7/site-packages/determined/cli/version.py", line 36, in check_version
    info = get_version(parsed_args.master)
  File "/home/cyuser/anaconda3/envs/determined/lib/python3.7/site-packages/determined/cli/version.py", line 23, in get_version
    master_info = api.get(host, "info", authenticated=False).json()
  File "/home/cyuser/anaconda3/envs/determined/lib/python3.7/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
**requests.exceptions.JSONDecodeError: [Errno Expecting value] 
<!doctype html>
<html lang="en" style="width: 100%; height: 100%;">
<head>
  <meta charset="utf-8">
  <title>WIZIOT</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link id="appFavicon" rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="preload" href="assets/fonts/MaterialIcons-Regular.woff2" as="font" type="font/woff2" crossorigin="anonymous" />
  <link rel="stylesheet" href="assets/fonts/material-icons.css" />
  <style type="text/css">

    body, html {
      height: 100%;
      overflow: hidden;
      background-color: #eee;
    }

    .tb-loading-spinner {
      margin: auto;
      z-index: 1;
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      width: 136px;
      height: 30px;
      text-align: center;
    }

    .tb-loading-spinner > div {
      width: 30px;
      height: 30px;
      margin-right: 10px;
      background-color: rgb(43,160,199);

      border-radius: 100%;
      display: inline-block;
      -webkit-animation: tb-bouncedelay 1.4s infinite ease-in-out both;
      -moz-animation: tb-bouncedelay 1.4s infinite ease-in-out both;
      animation: tb-bouncedelay 1.4s infinite ease-in-out both;
    }

    .tb-loading-spinner .tb-bounce1 {
      -webkit-animation-delay: -0.32s;
      -moz-animation-delay: -0.32s;
      animation-delay: -0.32s;
    }

    .tb-loading-spinner .tb-bounce2 {
      -webkit-animation-delay: -0.16s;
      -moz-animation-delay: -0.16s;
      animation-delay: -0.16s;
    }

    @-webkit-keyframes tb-bouncedelay {
      0%, 80%, 100% { -webkit-transform: scale(0) }
      40% { -webkit-transform: scale(1.0) }
    }

    @-moz-keyframes tb-bouncedelay {
      0%, 80%, 100% { -moz-transform: scale(0) }
      40% { -moz-transform: scale(1.0) }
    }

    @keyframes tb-bouncedelay {
      0%, 80%, 100% {
        -webkit-transform: scale(0);
        -moz-transform: scale(0);
        transform: scale(0);
      } 40% {
          -webkit-transform: scale(1.0);
          -moz-transform: scale(1.0);
          transform: scale(1.0);
        }
    }

  </style>
<link rel="stylesheet" href="styles.d6908c7850788df8ac22.css"></head>
<body class="tb-default">
  <tb-root></tb-root>
  <div id="tb-loading-spinner" class="tb-loading-spinner">
    <div class="tb-bounce1"></div>
    <div class="tb-bounce2"></div>
    <div class="tb-bounce3"></div>
  </div>
<script src="runtime.db15fb68df8675623ff5.js" defer></script><script src="polyfills-es5.af800e0323122522e195.js" nomodule defer></script><script src="polyfills.2661fb415d77a8231f3a.js" defer></script><script src="scripts.7c04b02269a193d677ba.js" defer></script><script src="vendor.5f675409c6302d5ca839.js" defer></script><script src="main.ddb7b111ae3cbf2f115c.js" defer></script></body>
</html>
: 0
**Failed to create experiment**

**Comment by ioga** [comment]
hello, do you have some kind of http proxy that may be intercepting http requests between your determined cli client and the determined master?

**Comment by kelvinwang139** [comment]
@ioga thanks for your response. The issue has been resolved. The reason is that I change the master port to 9099 because the port conflict. I run the command as "det -m 0.0.0.0:9090 ....." the 9099 is current port setting and then the issue fixed.

Thanks again.
