### ISSUE TITLE
A lot of MissingHeaderBodySeparatorDefect warning 

### ISSUE THREAD

**Issue by sijin-dm** [determined-ai/determined#4001]
There are a lot of `MissingHeaderBodySeparatorDefect` warningS when we switch checkpoint storage to s3. As you can see in the following snapshot.
![image](https://user-images.githubusercontent.com/61957607/164974989-5d3c307b-466d-4871-af46-d2c5abd2fc57.png)

Even though I have make all my file to be not empty, these warnings are still exsited. At the meantime, using `Info` fillter not work, the expected information like `report_validation_metrics` does not appear.
![image](https://user-images.githubusercontent.com/61957607/164976198-632c734a-572e-4006-b09f-2ef26fd092f2.png)

I think you have noticed that this is mainly caused by some empty files:
https://github.com/minio/minio/issues/11245
I found a lot of people suggest using minio-py instead. Do you have any plans to fix this?

**Comment by ioga** [comment]
Hello, 

We've got a workaround for minio issue here: https://github.com/determined-ai/determined/blob/master/harness/determined/common/storage/s3.py#L63
We know a number of users successfully use minio, not sure why you hit this. Do you have some kind of proxy in front of minio that may be obscuring the `Server` header, by any chance?

>I found a lot of people suggest using minio-py instead. Do you have any plans to fix this?
While it shouldn't be necessary, minio-py solution will have to be a new storage backend alternative to S3. PRs are welcome.

CC @rb-determined-ai

>At the meantime, using Info fillter not work, the expected information like report_validation_metrics does not appear.

This was fixed recently by #3973. it should be a part of the upcoming 0.17.15 release - likely later this week.

**Comment by sijin-dm** [comment]
Actually we use the s3 storage from a thirty-party provider, so the `Server` header does not have `minio`. When we build our own s3 storage with minio, these warnings are disappeared. I think this workaround may not be a general solution. I will try to fix this when I am available. 
Moreover, I would be update to 0.17.15 when it is released, thanks for your prompt reply! @ioga
