### ISSUE TITLE
Using determined with podman

### ISSUE THREAD

**Issue by ce107** [determined-ai/determined#4079]
I am trying to install determined on a RHEL8 system with podman (working with the docker compatibility mode):

$ det deploy local cluster-up 
/projects/ML/DL/test-determined/lib64/python3.6/site-packages/OpenSSL/crypto.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography import utils, x509
/projects/ML/DL/test-determined/lib64/python3.6/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Failed to connect to Docker daemon: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
Please ensure that the Docker daemon is running and that the current user has access permissions.
For more details, please see Determined installation docs: https://docs.determined.ai/latest/how-to/installation/requirements.html#install-docker

Leaving aside the warning messages - how can I get this working?

**Comment by ioga** [comment]
hello, we only support docker runtime today and we're pretty tightly integrated with it. podman and other alternative runtimes will not work, but we are considering adding support for them in the future.

also I've noticed you're running python 3.6. that may also be a problem, we require 3.7 for the recent versions.

**Comment by ioga** [comment]
Podman is supported on Slurm resource manager since [0.19.2](https://docs.determined.ai/latest/release-notes.html?highlight=release%20notes#version-0-19-2)
