### ISSUE TITLE
How to configure local disk volume to map to backend: disk

### ISSUE THREAD

**Issue by kelvinwang139** [determined-ai/determined#4221]
Hi,
when I run the model-hub:mmdetection related example, and find the following error:
![image](https://user-images.githubusercontent.com/10773148/170163235-1f85463c-1286-4a12-9f81-1ad34da91038.png)

I think this is no mapping local data set to mmdetection docker(backend = disk), but I can not find the related docker run command to make this mapping or is there configuration could support to it?

**Comment by ioga** [comment]
hello, please see the [bind_mounts option](https://docs.determined.ai/latest/training-apis/experiment-config.html#exp-bind-mounts).

**Comment by kelvinwang139** [comment]
> hello, please see the [bind_mounts option](https://docs.determined.ai/latest/training-apis/experiment-config.html#exp-bind-mounts).

Thanks for your nice response. It works.
