### ISSUE TITLE
resource-pools    401 Unauthorized   In development mode

### ISSUE THREAD

**Issue by fengzf-github** [determined-ai/determined#4236]
Request URL: http://10.6.5.51:8080/api/v1/resource-pools
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 10.6.5.51:8080
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 79
Content-Type: application/json
Date: Fri, 27 May 2022 04:16:02 GMT
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Authorization: Bearer
Connection: keep-alive
Cookie: _ga=GA1.1.309483961.1652767205; csrftoken=vxTObb5CU8akEi0LJJPzl4Rp0i6ztPc2hJfXoseQzReSMCS31pJ3RyKNGzG2a91W; _gid=GA1.1.109284979.1653357311; sessionid=.eJxVjDuSwjAQBe8yMXZprD8hOWdwzWgkbKAkyp9kt7g7yxYJ6et-_Qv7LHCEYHUZlGCn7eA7gzp27IztMnkjPohyqOAAbblQnX9om1sdHzc44gFG2rdp3Ne8jP8phK-NKd1yfQO5Ur20PrW6LTP3b6X_0LU_N8n308f9Cky0Tn9vG8iHaIvDKFqiZ1WUZi05haBKcWTMUGJKrAwjY4wu0oCsDZNDIwmeLwH2SeM:1ntJvU:2ESLd2N4-Q7pY2Q-YlAJcnQ5bOpRgcws3Xmry2Et9pY; ajs_user_id=1; ajs_anonymous_id=adbe8713-be67-4285-b1cc-21c96e8779bc
Host: 10.6.5.51:8080
Referer: http://10.6.5.51:8080/det/login
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36

**Comment by ioga** [comment]
hello, 
1. can you explain a bit how did you get this? did you have to login before getting this? 
2. does `det` CLI work against your dev build?
3. does it work in incognito mode?
4. did you use a new database or reused the one from other, non-development installation?

**Comment by fengzf-github** [comment]
1.The compilation is successful. The cluster is started for the first time and successfully logged in.
2.Stop the service and delete the database directory.
     rm -rf /root/.postgres/
     rm -rf /tmp/determined determined-cp devcluster
     
3.Error when starting the service again.

Request URL: http://localhost:8080/api/v1/resource-pools
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: [::1]:8080
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 79
Content-Type: application/json
Date: Sat, 28 May 2022 01:20:29 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Bearer
Connection: keep-alive
Cookie: ajs_anonymous_id=815e0ed1-ef9a-476d-ad20-b72206f58328; ajs_user_id=1; _ga=GA1.1.924750066.1653567190; _gid=GA1.1.308101123.1653567190
Host: localhost:8080
Referer: http://localhost:8080/det/dashboard
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

**Comment by ioga** [comment]
Okay, this answers my questions 1 and 4. what about 2 and 3?

**Comment by fengzf-github** [comment]
###  I don't quite understand what your questions 2 and 3 mean
###  Here are my two installation procedures

###  1.First installation process

sudo su

conda activate determined

cd /root

git clone https://github.com/determined-ai/determined.git

git clone https://github.com/determined-ai/devcluster.git

cd determined

conda activate determined

make all

cd ../devcluster

pip install -e .

cp devcluster/example.yaml ~/.devcluster.yaml


devcluster -C ../determined

###  The cluster is started for the first time and successfully logged in.
###  Stop the service and delete the database directory.

rm -rf /root/.postgres/
rm -rf /tmp/determined determined-cp devcluster

Error when starting the service again.
Request URL: http://localhost:8080/api/v1/resource-pools
Request Method: GET
Status Code: 401 Unauthorized

###########################################################

###  2.Second installation method


sudo su

conda activate determined

pip install determined

pip install hydra-core>=1.1

det deploy local master-up


####  Determined starts successfully. There is no error after the first installation,But submit the model_hub task,The following errors will occur.

cd /root

git clone https://github.com/determined-ai/determined.git

vi /root/determined/model_hub/examples/mmdetection/hydra/configs/config.yaml

###  Write the following in the configuration file. Prepare the data in the corresponding directory.

bind_mounts:
  - host_path: /root/data
    container_path: /run/determined/workdir/data
    read_only: false

cd /root/determined/model_hub/examples/mmdetection/hydra


python mmdet_experiment.py hyperparameters.config_file=faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py

###  Wait for a period of time. The task log is as follows:(This is the result of the previous test. The first problem encountered when installing the latest git clone code with make all.)


[2022-05-25 03:55:35] timeout exceeded: some containers are taking a long time to connect to master; when running on kubernetes this may happen because only some of the pods have been scheduled; it is possible that some pods will never be scheduled without adding compute resources or pausing / killing other experiments in the cluster

**Comment by ioga** [comment]
Regarding part 1:

>The cluster is started for the first time and successfully logged in.

So, you login, then remove the database, and then login fails?
Try using "incognito" or "private" mode in the browser, i.e. when you no longer have your auth from the old database. Alternatively, try clearing the cookies for the given host, and see if that helps.

Also try using determined CLI (i.e. `det ...`, e.g. `det experiment list` and see if that works.

Part 2 is another issue discussed in #4225.

**Comment by fengzf-github** [comment]
After logging in, stop the cluster service and delete the local database directory. Then start the cluster again and the login page cannot be displayed.
Unable to log in after deleting the chrome cache.

The following questions need your help：
1、How to use the source code to build the required image?Where do I need to execute what commands?
2、What components are required to compile and install determined？What are the relationships of these components？How to use the CLI after the compilation and installation are successful？What documents can we refer to？

**Comment by ioga** [comment]
@fengzf-github since you are opening and closing a number of issues, and it's hard for us to understand what's happening with your setup, I am curious if this issue got resolved?

**Comment by fengzf-github** [comment]
I turned off this issue by mistake

**Comment by ioga** [comment]
okay. 

>How to use the source code to build the required image?

on a high level, I don't think that building determined from source will your issues. but if this is a goal in itself for you, there're some sparse docs here: https://github.com/determined-ai/determined/blob/master/CONTRIBUTING.md#installation-from-source

>How to use the CLI after the compilation and installation are successful？

I believe you've already used `det experiment create ...` commands to run some experiments, based on your other issues. Running an experiment should be a sufficient signal. Were you able to run any experiment successfully, either in normal setup, or in a custom build?

**Comment by fengzf-github** [comment]
Thank you for your answer，How to use the CLI after the compilation and installation are successful？I got it.
I can also run some experiments successfully.
The following questions need your help to answer：
How to use source code to build images（determined-fluent、determined-agent-0、determined_determined-master_1、determined_determined-db_1） and how to run them？ Is there any relevant document for reference？
