### ISSUE TITLE
Some suggestions for improving the Installation from Source guide

### ISSUE THREAD

**Issue by sirredbeard** [determined-ai/determined#4481]
**Summary**

The [Installation from Source guide](https://github.com/determined-ai/determined/blob/master/CONTRIBUTING.md#installation-from-source) in CONTRIBUTING.md could be more user friendly.

**Expected Results**

The Installation from Source guide allows developers to build Determined in a straightforward path.

**Actual Results**

The Installation from Source guide (IfSg) has some issues that prevent building Determined.

**Issue: The git command.**

The IfSg recommends running `git clone --recurse-submodules git@github.com:determined-ai/determined.git` to clone the Determined source code.

Most users expect to be able to copy and paste this command and it 'just work', but it does not:
![image](https://user-images.githubusercontent.com/33820650/177396207-af5d4eed-29d6-4475-b684-e7c0dd0361e2.png)

The command should be updated to:  `git clone --recurse-submodules https://github.com/determined-ai/determined.git`.

**Issue: The Python and Node dependencies.**

The latest Ubuntu LTS, Ubuntu 22.04, ships with Python 3.10 and nodejs 12.22 by default, which are not currently supported by Determined.

While the steps to install separate versions of python3 and nodejs are outside the scope of the IfSg, the guide should advise users to check the version of python3 and nodejs installed on their workstation and available from their distro package managers to make sure they meet the requirements. 

**Issue: The protoc dependency.**

Most distros ship protoc as `protobuf-compiler`.  Users attempting to install `protoc` with apt, dnf, etc. will get an error message that the package is not found. For usability purposes, change `protoc` to `protobuf-compiler` in the IfSg dependency list.

![image](https://user-images.githubusercontent.com/33820650/177400750-1905882a-5650-44ae-9507-35bc362e284f.png)

![image](https://user-images.githubusercontent.com/33820650/177401373-8b55cc7d-e740-48c0-af78-a5bdb8faec73.png)

**Issue: Tensorflow 2.4.3 is not available for Python 3.9.`**

See a separate issue opened [here](https://github.com/determined-ai/determined/issues/4480).

**Issue: python3-venv dependency.**

python3-venv is required by the IfSg but is an additional package that does not ship with base python3 installs on most Linux distros. python3-venv should be added to the IfSg dependency list.

**Issue: python3-wheel dependency.**

Without python3-wheel installed, deepspeed, sphinx-sitemap, and several other packages default to using the legacy `setup.py install' method. python3-wheel should be added to the IfSg dependency list.

![image](https://user-images.githubusercontent.com/33820650/177407250-cc2ab7a2-d5f9-4f93-b7fa-6b882c9155be.png)

**Issue: python3-dev dependency**

Building pycocotools requires the `python3-dev` or `python3-devel` package from a Linux distro.

Otherwise, the following error results:

```
  Building wheel for pycocotools (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/pycocotools
      copying pycocotools/__init__.py -> build/lib.linux-x86_64-cpython-38/pycocotools
      copying pycocotools/coco.py -> build/lib.linux-x86_64-cpython-38/pycocotools
      copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-cpython-38/pycocotools
      copying pycocotools/mask.py -> build/lib.linux-x86_64-cpython-38/pycocotools
      running build_ext
      skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
      building 'pycocotools._mask' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/common
      creating build/temp.linux-x86_64-cpython-38/pycocotools
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-s0g1dbdn/overlay/lib/python3.8/site-packages/numpy/core/include -I./common -I/home/hayden/.virtualenvs/determined/include -I/usr/include/python3.8 -c ./common/maskApi.c -o build/temp.linux-x86_64-cpython-38/./common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
      ./common/maskApi.c: In function ‘rleDecode’:
      ./common/maskApi.c:46:7: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
         46 |       for( k=0; k<R[i].cnts[j]; k++ ) *(M++)=v; v=!v; }}
            |       ^~~
      ./common/maskApi.c:46:49: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
         46 |       for( k=0; k<R[i].cnts[j]; k++ ) *(M++)=v; v=!v; }}
            |                                                 ^
      ./common/maskApi.c: In function ‘rleToBbox’:
      ./common/maskApi.c:135:32: warning: unused variable ‘xp’ [-Wunused-variable]
        135 |     uint h, w, xs, ys, xe, ye, xp, cc; siz j, m;
            |                                ^~
      ./common/maskApi.c: In function ‘rleFrPoly’:
      ./common/maskApi.c:181:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
        181 |   for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
            |   ^~~
      ./common/maskApi.c:181:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
        181 |   for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
            |                                                      ^
      ./common/maskApi.c:182:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
        182 |   for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
            |   ^~~
      ./common/maskApi.c:182:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
        182 |   for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
            |                                                      ^
      ./common/maskApi.c: In function ‘rleToString’:
      ./common/maskApi.c:227:7: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
        227 |       if(more) c |= 0x20; c+=48; s[p++]=c;
            |       ^~
      ./common/maskApi.c:227:27: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
        227 |       if(more) c |= 0x20; c+=48; s[p++]=c;
            |                           ^
      ./common/maskApi.c: In function ‘rleFrString’:
      ./common/maskApi.c:235:3: warning: this ‘while’ clause does not guard... [-Wmisleading-indentation]
        235 |   while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
            |   ^~~~~
      ./common/maskApi.c:235:22: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘while’
        235 |   while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
            |                      ^~~~
      ./common/maskApi.c:243:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
        243 |     if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
            |     ^~
      ./common/maskApi.c:243:34: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
        243 |     if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
            |                                  ^~~~
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-s0g1dbdn/overlay/lib/python3.8/site-packages/numpy/core/include -I./common -I/home/hayden/.virtualenvs/determined/include -I/usr/include/python3.8 -c pycocotools/_mask.c -o build/temp.linux-x86_64-cpython-38/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
      pycocotools/_mask.c:4:10: fatal error: Python.h: No such file or directory
          4 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
  Building wheel for sacremoses (setup.py) ... done
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895254 sha256=04e2185bf070316b849c38e0fd8503a6b60765cf81701e2c14ce4f4f8cf88000
  Stored in directory: /home/hayden/.cache/pip/wheels/82/ab/9b/c15899bf659ba74f623ac776e861cf2eb8608c1825ddec66a4
  Building wheel for dockerpty (setup.py) ... done
  Created wheel for dockerpty: filename=dockerpty-0.4.1-py3-none-any.whl size=16606 sha256=4f9e50b3d7cc940d096970f894357b7bbe4b9b6649d18aaeb888e23cc225e810
  Stored in directory: /home/hayden/.cache/pip/wheels/1a/58/0d/9916bf3c72e224e038beb88f669f68b61d2f274df498ff87c6
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13704 sha256=e8ca6a79322e4034e89b333f302ca0d7e16ffbe6985d549073d13f70d16a8816
  Stored in directory: /home/hayden/.cache/pip/wheels/56/ea/58/ead137b087d9e326852a851351d1debf4ada529b6ac0ec4e8c
Successfully built deepspeed sphinx-sitemap flake8-quotes future termcolor wrapt py-cpuinfo sacremoses dockerpty docopt
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects
make[1]: *** [Makefile:16: get-deps-pip] Error 1
make[1]: Leaving directory '/home/hayden/determined'
make: *** [Makefile:3: all] Error 2
```

`python3-dev` should be added to the IfSg dependency list.

**Issue: protoc-gen-go is missing**

When building Determined, `protoc-gen-go` and `protoc-gen-go-grpc` are installed:

```
go install github.com/golang/protobuf/protoc-gen-go@v1.5.2
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0
```

But cannot be found by the Makefile script: 

```
protoc-gen-go: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--go_out: protoc-gen-go: Plugin failed with status code 1.
```

protoc-gen-go is in `~/go/bin` and executable:

![image](https://user-images.githubusercontent.com/33820650/177417285-bee9ea2e-81c7-479e-a067-8ae832ae863a.png)

This issue can be fixed by setting `export PATH=$PATH:$HOME/go/bin` prior to running `make all`.

**Conclusion**

If there is consensus on:
* Updating the git command to be more user-friendly
* Adding a note about checking for the specific version of python3 and nodejs on your distro to ensure it meets the version requirements
* Adding `python3-venv` to the IfSg dependency list
* Adding `python3-wheel` to the IfSg dependency list
* Adding `python3-dev` to the IfSg dependency list
* Changing `protoc` to `protobuf-compiler` on the IfSg dependency list
* Adding a note about adding `$HOME/go/bin` to PATH
* Adding a note that addresses https://github.com/determined-ai/determined/issues/4480

I will open a PR.

**Comment by ioga** [comment]
These are all great points, looking forward to a PR. Nitpicks:
1. I'd put all items except for the git command under "Ubuntu" (or "Linux") subsection of the IfSg, because these are OS-specific and not applicable e.g. to macOS.
2. For active contributors, I'd recommend using [pyenv](https://github.com/pyenv/pyenv#automatic-installer) instead, because it'd allow more flexibility in your python setup compared to the system python packages (like fast switching between 3.7 and 3.9 or 3.10). That'd address `python3-venv`, `python3-wheel`, and `python3-dev` issues on the list. wrapper tools like `asdf` are also getting popular, and that'd allow nicer `node` version management as well. System packages path is still valid though.

**Comment by sirredbeard** [comment]
Here is my updated proposal:

**First**, amend the existing DIY general build guidelines with recommendations above, with caveat YMMV.

**Second**, have a guide to building Determined with Homebrew, which is reproducible across macOS and Linux distributions.

**Third**, as a stretch goal, provide a container image with all the of the dependencies pre-installed.
