### ISSUE TITLE
ZeroRedundancyOptimizer support

### ISSUE THREAD

**Issue by hturki** [determined-ai/determined#4531]
Hi,

Is it possible to use Pytorch's https://pytorch.org/tutorials/recipes/zero_redundancy_optimizer.html#how-to-use-zeroredundancyoptimizer in Determined.ai? An initial attempt has it fail with the following stacktrace:

[2022-07-13 05:54:27] [d2997185] [rank=15]   File "/opt/conda/envs/my-env/lib/python3.9/site-packages/torch/distributed/optim/zero_redundancy_optimizer.py", line 391, in __init__
<none> [2022-07-13 05:54:27] [d2997185] [rank=15]     self.world_size: int = dist.get_world_size(self.process_group)
<none> [2022-07-13 05:54:27] [d2997185] [rank=15]   File "/opt/conda/envs/my-envf/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 845, in get_world_size
<none> [2022-07-13 05:54:27] [d2997185] [rank=15]     return _get_group_size(group)
<none> [2022-07-13 05:54:27] [d2997185] [rank=15]   File "/opt/conda/envs/my-env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 306, in _get_group_size
<none> [2022-07-13 05:54:27] [d2997185] [rank=15]     default_pg = _get_default_group()
<none> [2022-07-13 05:54:27] [d2997185] [rank=15]   File "/opt/conda/envs/my-env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 410, in _get_default_group
<none> [2022-07-13 05:54:27] [d2997185] [rank=15]     raise RuntimeError(
<none> [2022-07-13 05:54:27] [d2997185] [rank=15] RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
<none> [2022-07-13 05:54:27] [fdc13c47] Process 12 exit with status code 1.

**Comment by liamcli** [comment]
Could you provide more information about the code you are trying to run and how you are launching the experiment?

**Comment by hturki** [comment]
I unfortunately can't share my code this should be pretty straightforward to reproduce - just swap out the SGD optimizer in the example at https://docs.determined.ai/latest/training-apis/api-pytorch.html#using-optimizer with something like:

`
        optimizer = ZeroRedundancyOptimizer(
            ddp_model.parameters(),
            optimizer_class=torch.optim.SGD,
            lr=0.01
        )
`

This is on a DAI cluster in GCP and I'm launching a distributed job which I think is using horovod under the hood.

**Comment by liamcli** [comment]
Can you try changing the `entrypoint` of the expeirment config to use our pytorch distributed launcher instead:
`entrypoint: python3 -m determined.launch.torch_distributed --trial <YOUR_TRIAL>`

**Comment by hturki** [comment]
Sadly the cluster I'm on is not on 0.18 yet :/ feel free to close and i can reopen if needed. Thanks for the quick replies!
