### ISSUE TITLE
Here is a question about the operation of distributed tasks that you need to help answer.

### ISSUE THREAD

**Issue by fengzf-github** [determined-ai/determined#4557]
There are two agents in my determined cluster. Each agent is located on a different physical machine, and each physical machine has two GPUs.
Submit the distributed task and put the parameter slots_ per_ The value of trial is set to 4, and the task runs incorrectly。
My question is, can a distributed task run with all GPUs on multiple physical machines?
If yes, which documents should be referenced to set task parameters?

**Comment by rb-determined-ai** [comment]
please read the [docs](https://docs.determined.ai/latest/training-distributed/index.html) for basic questions on how distributed training works.
