### ISSUE TITLE
det deploy local cluster-up fails (wrong determinedai/determined-agent image pull)

### ISSUE THREAD

**Issue by moracabanas** [determined-ai/determined#4572]
Following the official example for a basic workstation I do:
`det deploy local cluster-up` 
The `determinedai/determined-agent:0.18.4` gives error at pulling so I manually pulled `latest` and repeat `det deploy ...` and it is fixed.
The default `determined-agent` image reference should be updated as it is now stoping basic installation.

**Comment by moracabanas** [comment]
I will check it as I am trying `pop-os` and I am doing initial tests, maybe reinstalling docker could resolve issues.
I will post some tests.
Thanks you!

**Comment by moracabanas** [comment]
I reinstalled docker and still getting issues pulling images for some reason.  
I am testing pulling `ubuntu:latest` and removing it for several times: 

RESUTLS
1. Sometimes it pulls ok.
2. Sometimes I get some of the following errors:

a) 
```
Error response from daemon: Get "https://registry-1.docker.io/v2/library/ubuntu/manifests/sha256:b6b83d3c331794420340093eb706a6f152d9c1fa51b262d9bf34594887c2c7ac": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Amazon")
```

b)
```
docker: Error response from daemon: Head "https://registry-1.docker.io/v2/library/ubuntu/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io": tls: failed to parse certificate from server: x509: invalid RDNSequence: invalid attribute value: invalid PrintableString.
```

c)
```
Error response from daemon: Head "https://registry-1.docker.io/v2/library/ubuntu/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fubuntu%3Apull&service=registry.docker.io": tls: failed to parse certificate from server: x509: invalid RDNSequence: invalid attribute value: invalid PrintableString
```

**Comment by ioga** [comment]
This is odd, I've never seen anything like it. Can you reproduce it on another machine?

My random guesses would be:
- bad networking setup with a middleware box or a proxy messing your TLS bytes up
- bad RAM, run memtest

Either way, it doesn't seem to be a determined issue, but I'd love to know what the root cause was out of general curiousity.

**Comment by moracabanas** [comment]
I bought a Cat 6a ethernet. Docker TLS problem solved. This is crazy.
