### ISSUE TITLE
PyTorch 1.12 Support

### ISSUE THREAD

**Issue by benjaminrwilson** [determined-ai/determined#4608]
Hi,

Thanks for this great project! Is PyTorch 1.12 currently supported? If not, when do you expect it will be?

Thanks!

**Comment by ioga** [comment]
hello, we're a little backed up and can't provide any timeline. 
I think you can try this out yourself in a couple ways:
1. take our current image, then `pip install` pytorch 1.12 (pick cuda 11.3 flavor), then also use pip to reinstall horovod 0.24.2 or later (if you need it for distributed training). 
2. alternatively, clone and tweak our [image building code](https://github.com/determined-ai/environments/blob/master/Makefile#L207) to install the new pytorch.

It may "just work", but if you encounter any issues we'd love to hear them.

**Comment by MikhailKardash** [comment]
Our default images use `pytorch==1.12`. Closing this.
