### ISSUE TITLE
[feat] Use IMDS v2 for EC2 instances  

### ISSUE THREAD

**Issue by tekumara** [determined-ai/determined#4681]
### Describe the problem

[IMDS v2 offers defense in depth against SSRF attacks](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/) and is mandated in some organisations via service control policies.

Enabling IMDS v2 by default on the master and agent instances would allow determined to work in such organisations and is good security hygiene. 

### Describe the solution you'd like

Master and agent EC2 instances are created with IMDSv2 enabled, ie: with [InstanceMetadataOptions](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_InstanceMetadataOptions.html)`HttpTokens=required`

**Comment by stoksc** [comment]
Hi @tekumara, thanks for the feature request. Make sense, this is useful. I'll ticket this internally.

**Comment by vishnu2kmohan** [comment]
Related:
* https://github.com/determined-ai/determined/pull/5421
* https://github.com/determined-ai/determined/pull/5494

**Comment by ioga** [comment]
IMDSv2 support should be coming out in the next release.
