### ISSUE TITLE
[bug] det tensorboard - link is not URL-encoded 

### ISSUE THREAD

**Issue by tekumara** [determined-ai/determined#4715]
### Describe the bug

```
det -m localhost:8080 tensorboard start 2
Scheduling TensorBoard (previously-in-goldfish) (id: e4d8c6dc-1f6c-4a3f-91d6-54e1b2b9fcbc)...
TensorBoard (previously-in-goldfish) was assigned to an agent...
Resources for TensorBoard (previously-in-goldfish) has started...
TensorBoard is running at: http://localhost:8080/det/interactive/e4d8c6dc-1f6c-4a3f-91d6-54e1b2b9fcbc/tensorboard/TensorBoard (previously-in-goldfish)/aux-pool/%2Fdet%2Fwait%2Ftensorboard%2Fe4d8c6dc-1f6c-4a3f-91d6-54e1b2b9fcbc%3FeventUrl%3D%2Fproxy%2Fe4d8c6dc-1f6c-4a3f-91d6-54e1b2b9fcbc%2F%2Ftensorboard%2Fe4d8c6dc-1f6c-4a3f-91d6-54e1b2b9fcbc%2Fevents%3Ftail%3D1%26serviceAddr%3D%2Fproxy%2Fe4d8c6dc-1f6c-4a3f-91d6-54e1b2b9fcbc%2F
```

The tensorboard link does not url encode the space in `TensorBoard (previously-in-goldfish)` and so it can't be used without modification
 

### Reproduction Steps

det -m localhost:8080 tensorboard start 2

### Expected Behavior

Produce a valid url-encoded link, eg: `TensorBoard%20(previously-in-goldfish)` instead of `TensorBoard (previously-in-goldfish)`

### Screenshot

see above

### Environment

python 3.9 det 0.19.0

**Comment by ioga** [comment]
thank you for the report. we should have a fix for this in the upcoming 0.19.1 release.
