### ISSUE TITLE
[bug] Here are two questions about the correctness of the model results that you need to answer，thank you！

### ISSUE THREAD

**Issue by fengzf-github** [determined-ai/determined#4751]
### Describe the bug

1、Why is the content stored in the PTH file model file generated by the determinedai training mmdetection task different from that of the PTH file model file directly generated by mmdetection?
2、Why is the map50 value of the model displayed on the determinedai page 92.2%, but the confidence of the detection frame generated by the forward reasoning of the model is less than 2%？

### Reproduction Steps

1

### Expected Behavior

1

### Screenshot

1

### Environment

1

### Additional Context

1

**Comment by liamcli** [comment]
1. Our checkpoint also stores information about RNG state and other things needed to resume training whereas the mmdetection checkpoint only has model weights.  
2. Where is the 92.2% that you are referring to?  mAP on COCO is usually around 50 or 60 mAP.  What do you mean by confidence of the detection frame?

**Comment by fengzf-github** [comment]
Thank you for your answer. I have found the reason for this question.
