### ISSUE TITLE
[bug] zsh: command not found: det

### ISSUE THREAD

**Issue by logankilpatrick** [determined-ai/determined#4928]
### Describe the bug

I am following the quickstart guide here: https://docs.determined.ai/latest/quickstart-mdldev.html#run-a-local-single-cpu-gpu-training-job and have installed determined. I can see it when I do `pip list`, however, when I run: `det deploy local cluster-up --no-gpu` I get `zsh: command not found: det`. Any suggestions on this? 

### Reproduction Steps

1. `pip install determined`
2. `det deploy local cluster-up --no-gpu`
3. `zsh: command not found: det`

### Expected Behavior

I would expect that the local cluster starts.

### Screenshot

<img width="832" alt="Screen Shot 2022-08-31 at 9 04 05 PM" src="https://user-images.githubusercontent.com/35577566/187816643-550a5f48-2c26-4c3b-8be6-35b662537b9f.png">

### Environment

- Device or hardware: MacBook Pro (16-inch, 2021)
- OS: macOS 12.5 (21G72)
- Browser Safari
- Version 0.19.2

**Comment by logankilpatrick** [comment]
I can get past this issue if I use a new Python Env, might it make sense to suggest that to users?

**Comment by logankilpatrick** [comment]
Also, this getting started tutorial should say you have to launch docker locally before running the `det deploy local cluster-up --no-gpu` command.

**Comment by ioga** [comment]
>I can get past this issue if I use a new Python Env, might it make sense to suggest that to users?

sounds like your issue got resolved? there's a number of ways to setup a python environment, and "using a new one" is not necessarily a solution, so I am hesitant to suggest that.

>this getting started tutorial should say you have to launch docker locally
it's mentioned earlier in [prerequisites](https://docs.determined.ai/latest/quickstart-mdldev.html#docker). but I agree, documentation can always use improvements.

**Comment by sirredbeard** [comment]
> I can get past this issue if I use a new Python Env, might it make sense to suggest that to users?

Is this an issue in zsh vs. bash? Is the location of det not being updated in zsh's PATH?

**Comment by ioga** [comment]
> Is this an issue in zsh vs. bash? Is the location of det not being updated in zsh's PATH?

I believe this was a python virtualenv setup issue: perhaps the default venv's `bin` is not in the `PATH`, but once the user created an explicit venv, that patched their  shell's `PATH` and it started working.
