### ISSUE TITLE
Lower Barrier to Entry by making the CLA sign off a webpage

### ISSUE THREAD

**Issue by logankilpatrick** [determined-ai/determined#4930]
### Describe the problem

For small docs changes or other fixes, it's unlikely that someone is going to take the time to go to the CLA, download it, use PDF editor software to add their info, and then email it back to the requested address. There are tools out there that make this process more simple where devs can just check a box online and they are good to go. 

### Describe the solution you'd like

Something like: https://colineberhardt.github.io/cla-bot/#installing-cla-bot where the process can stay GitHub native.

**Comment by neilconway** [comment]
Hi @logankilpatrick ! Thanks for the suggestion. We're already using clabot, we've just been updating the config file manually. More automation here sounds like a nice improvement.
