### ISSUE TITLE
help with mmclassification and mmsegmentation

### ISSUE THREAD

**Issue by fengzf-github** [determined-ai/determined#4958]
### Describe the bug

1、Does determined currently support mmclassification and mmsegmentation?
2、If I want to integrate mmclassification and mmsegmentation myself, use the existing determined / model_ hub/model_ The code structure in hub / mmdetection. How to implement the mmclassification and mmsegmentation task execution code?

### Reproduction Steps

1

### Expected Behavior

1

### Screenshot

1

### Environment

1

### Additional Context

1

**Comment by rb-determined-ai** [comment]
1. With the Core API, we support any python-based training whatsoever.  So yes.
2. Have you reviewed our [mmdetection example](https://github.com/determined-ai/determined/tree/master/model_hub/examples/mmdetection) yet?  I would guess that you could look at that code and perhaps the implementation of mmdetection support in the [model_hub library](https://github.com/determined-ai/determined/tree/master/model_hub/model_hub/mmdetection) to figure it out.  We don't have first-class support for mmclassification and mmsegmentation yet.

Also, please don't mark things as `[bug]` when they are clearly not a bug.

**Comment by fengzf-github** [comment]
OK, thank you
