### ISSUE TITLE
🐛[bug] Checkpointing with LR Scheduler throws an error for multi-GPU Pytorch Trial

### ISSUE THREAD

**Issue by abhinavagarwalla** [determined-ai/determined#5017]
### Describe the bug

Hi!

I am trying to port a Pytorch script to DAI. I am met with the following error:
```_pickle.PicklingError: Can't pickle <class 'horovod.torch.optimizer.Adam'>: attribute lookup Adam on horovod.torch.optimizer failed```

How do I fix this error? This seems to be a determined-ai bug. The trial works for a single-GPU setup but fails on running a multi-GPU trial.

### Reproduction Steps

```
self.optimizer = torch.optim.Adam(self.model.parameters(), lr=1e-3, betas=(0.9,0.99))
self.optimizer = self.context.wrap_optimizer(self.optimizer)
self.lr_scheduler = torch.optim.lr_scheduler.OneCycleLR(self.optimizer, ...)
self.lr_scheduler = self.context.wrap_lr_scheduler(self.lr_scheduler, LRScheduler.StepMode.STEP_EVERY_BATCH)
```

### Expected Behavior

The trial should run without errors.

### Screenshot

Can't share.

### Environment

Determined-AI v0.17.15

**Comment by ighodgao** [comment]
Hi @abhinavagarwalla -- thank you for reaching out with this issue. One of our engineers will get back to you as soon as possible. Thanks for your patience!

**Comment by rb-determined-ai** [comment]
Hi @abhinavagarwalla,

This issue comes up with the OneCycleLR scheduler.  You need a little wrapper around it to make it nicer to serialize:

```python
class MyOneCycleLR(torch.optim.lr_scheduler.OneCycleLR):
    def state_dict(self):
        return {
            key: value for key, value in self.__dict__.items()
            if key not in ['optimizer', 'anneal_func']
        }
```

Then just use `MyOneCycleLR` as a drop-in replacement for `OneCycleLR`.

We could probably find a better way to let users know they need this though...

**Comment by rb-determined-ai** [comment]
[I agree](https://github.com/determined-ai/determined/pull/5037)
