### ISSUE TITLE
[bug] sorting of workload table by metric column is broken

### ISSUE THREAD

**Issue by zjorgensenbits** [determined-ai/determined#5052]
In version 0.19.3, trying to sort the workload table (in an experiment page) by one of the metric columns gives an incorrect sorting when the workloads span multiple pages. It looks like what is happening is that it first divides the workloads into pages based on the batches column and then it sorts each page by the selected column, rather than sorting first and then dividing into pages.

**Comment by varlogtim** [comment]
Hello @zjorgensenbits, I am taking a look at this now.

**Comment by varlogtim** [comment]
Hello @zjorgensenbits, We were about to reproduce this locally, and found at least one other bug, and are currently looking into a fix. I cannot find a work around at this time. I will keep you updated about progress being made on this issue.

Thanks for your report!

**Comment by varlogtim** [comment]
Hey @zjorgensenbits, We have fixed this upstream here: https://github.com/determined-ai/determined/pull/5086. This will likely be in the release after next. (probably ~2 weeks from now)

**Comment by varlogtim** [comment]
https://github.com/determined-ai/determined/pull/5086
