### ISSUE TITLE
🐛[bug] the "total checkpoint size" box on experiment page includes deleted checkpoints in the total

### ISSUE THREAD

**Issue by zjorgensenbits** [determined-ai/determined#5053]
### Describe the bug

In Determined v0.19.3, the "total checkpoint size" box at the top of the overview tab of an experiment page seems to be including the sizes of deleted checkpoints in the total.

### Reproduction Steps

1. In the UI, select an completed experiment for which the cleanup policy was set to delete all but a few checkpoints, and then open the overview tab
2. observe the total checkpoint size at the top of the tab
3. click the checkpoints tab and filter by status completed. Add up the sizes and compare to the reported total. 

### Expected Behavior

"Total Checkpoint Size" should be computed only with the sizes of the checkpoints with status=completed.

### Screenshot

n/a

### Environment

- Device or hardware: Laptop
- OS: Windows 10
- Browser Firefox
- Determined Version: 0.19.3

**Comment by ighodgao** [comment]
Hi @zjorgensenbits, one of our engineers will get back to you shortly. Thanks for your patience!

**Comment by rb-determined-ai** [comment]
I think @varlogtim is working on this, even though I think he forgot to mention it.

**Comment by varlogtim** [comment]
Yes, I was able to reproduce this behavior locally. Thanks for the detailed report @zjorgensenbits!

**Comment by varlogtim** [comment]
@zjorgensenbits, thanks again for the report. I have merged a fix for this and it should be available in the next version of Determined. https://github.com/determined-ai/determined/pull/5063
