### ISSUE TITLE
🤔[question] Multi-GPU Error for Custom Optimizer

### ISSUE THREAD

**Issue by abhinavagarwalla** [determined-ai/determined#5162]
### Describe your question

I am porting a PyTorch code that uses a fastai-based optimizer (OptimWrapper over Adam). I notice this error on moving from single-GPU to multi-GPU setting. A single-GPU works fine since horovod's DistributedOptimizer isn't utilized.
It seems that on hvd.DistributedOptimizer call; the optimizer is reinitialized. The optimizer expects an additional parameter 'wd' that isn't passed. Is there a simple fix to enable passing of extra arguments?

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/harness.py", line 131, in <module>
    sys.exit(main(args.train_entrypoint))
  File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/harness.py", line 112, in main
    trial_inst = trial_class(trial_context)
  File "/run/determined/workdir/tools/train_dai_optimizer.py", line 132, in __init__
    self.optimizer = self.context.wrap_optimizer(self.optimizer)
  File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/pytorch/_pytorch_context.py", line 230, in wrap_optimizer
    optimizer = hvd.DistributedOptimizer(
  File "/opt/conda/lib/python3.8/site-packages/horovod/torch/optimizer.py", line 598, in DistributedOptimizer
    return cls(optimizer.param_groups, named_parameters, compression, backward_passes_per_step, op,
  File "/opt/conda/lib/python3.8/site-packages/horovod/torch/optimizer.py", line 43, in __init__
    super(self.__class__, self).__init__(params)
TypeError: __init__() missing 1 required positional argument: 'wd'
```

**Comment by rb-determined-ai** [comment]
I'm not sure how that code works, to be honest, since I know it works with normal optimizers but I can't see how.  So I'll play with fastai and see if I can reproduce, then see if I can come up with a workaround.

**Comment by rb-determined-ai** [comment]
I've tried several things but I can't quite reproduce the error you are seeing.  Can you share the following bits of information with me?

- the version of horovod you are using (include the line `pip show horovod` in a `startup-hook.sh`)
- the version of fastai you are using
- the version of determined you are using
- a snippet that is representative of the way you are building and wrapping your optimizer.  For example, if I run:

  ```python
  opt = fastai.optimizer.Adam(self.model.parameters(), lr=0.01, wd=0.01)
  self.opt = context.wrap_optimizer(opt)
  ```
  then I see a `TypeError: __init__() missing 1 required positional argument: 'cbs'` message, which is a bit different than what you are seeing.

**Comment by abhinavagarwalla** [comment]
Let me share an example by tomorrow!

**Comment by abhinavagarwalla** [comment]
The error might be different but the root cause is the same.
FastAi Optimizer class expects a 2nd argument `cbs` [here](https://docs.fast.ai/optimizer.html#optimizer). I am using the OptimWrapper class provided by fastai which expects an argument `wd`. My understanding is that `wrap_optimizer` reinitializes the optimizer, without any functionality to the pass these arguments. It seems to be a Horovod restriction.
Let me share the coder snippets and version information with you by tomorrow.

**Comment by abhinavagarwalla** [comment]
Environment:
horovod: 0.24.2
determined: 0.17.15

```
opt = build_optimizer(self.model, config)
self.optimizer = self.context.wrap_optimizer(opt)
```

`build_optimizer` returns an `OptimWrapper` class as defined [here](https://docs.fast.ai/optimizer.html#optimizer).

**Comment by rb-determined-ai** [comment]
Dumb question, but since I have never used FastAPI, can you show a snippet of how you instantiate the `OptimWrapper`, maybe the just the contents of `build_optimizer()`?

**Comment by abhinavagarwalla** [comment]
It looks something like this:

```
return OptimWrapper.create(
     partial(torch.optim.Adam, betas, weight_decay..),
     lr,
     [nn.Sequential(*flatten_model(model))],
     wd=config.wd,
     true_wd=config.true_wd,
     bn_wd=cfg.bn_wd)
```

**Comment by rb-determined-ai** [comment]
I'm still not able to quite reproduce your situation.  I see that the `fastai.optimizer.OptimWrapper` doesn't seem to have a `.create` method, as your code snippet calls for.

Also, to be honest, I don't really understand what fastai is good for.  Perhaps if you could explain to me what you are using it for, I could offer better advice?

But the way it looks right now is that PyTorchTrial + Fastai is just not compatible.

There is always [Core API](https://docs.determined.ai/latest/training/apis-howto/api-core/overview.html) though.  You're not required to use PyTorchTrial to use pytorch in Determined.

**Comment by abhinavagarwalla** [comment]
I am trying to port a `OptimWrapper` based optimizer to DAI. I observed that the performance drops on switching from a Fastai optimizer to a Pytorch one. I do agree that horovod and fastai don't seem to be compatible. More specifically, horovod doesn't support custom optimizers yet.

I can't really use torch distributed launch unless the determined version is upgraded on the server. The Core API looks promising. I will give it a try.

Thank you for looking into the issue.

**Comment by rb-determined-ai** [comment]
> More specifically, horovod doesn't support custom optimizers yet.

I would say, "horovod doesn't support non-pytorch-compatible optimizers".  You could absolutely use a custom optimizer, but it has to conform to the (odd) initialization patterns that pytorch optimizers have, which fastai's optimizers do not.

(I learned a lot about the oddness of pytorch optimizers while looking into this issue last week)
