### ISSUE TITLE
🤔[question] Any user can see the tasks created by other users?

### ISSUE THREAD

**Issue by dhiyu** [determined-ai/determined#5289]
### Describe your question

Hi! I found that any user (not an administrator) can see the tasks created by other users in webpage, like this:
![image](https://user-images.githubusercontent.com/37993729/196688275-ca3471e7-db02-4a8e-8ea0-6bec5bd67509.png).
In theory, this is unsafe because any user can kill other's process, and watch other's files and so on.
So, is it don't deploy till now? Also, the docs for [webui interface](https://docs.determined.ai/latest/interfaces/webui-if.html) is broken, what is the time to access it?

**Comment by rb-determined-ai** [comment]
> Hi! I found that any user (not an administrator) can see the tasks created by other users in webpage

That is correct.  We are working on RBAC support, but it will only be a feature in the enterprise edition.

> Also, the docs for [webui interface](https://docs.determined.ai/latest/interfaces/webui-if.html) is broken, what is the time to access it?

I don't understand the question.  Those docs look incomplete to me, but not broken.  I don't think we have a date for when we expect them to be finished.

**Comment by dhiyu** [comment]
Thank you for your reply. 
> I don't understand the question. Those docs look incomplete to me, but not broken. I don't think we have a date for when we expect them to be finished.
Yep, you are right. I notice the attention in that page and I think there will be a update rapidly, so I think it is broken for adjusting somewhat. 
![image](https://user-images.githubusercontent.com/37993729/196745418-a63dc9f2-7505-4c65-83f2-e3b7b3b66f6a.png)
Now I get it.
