### ISSUE TITLE
🐛[bug] Cannot select alternative metrics for main plot on trial page of multi-trial experiment

### ISSUE THREAD

**Issue by zjorgensenbits** [determined-ai/determined#5365]
### Describe the bug

I'm using Determined v 0.19.5.  I cannot select a metric (other than the default validation metric) to be displayed on the main plot on the trial page of any trial in a multi-trial experiment. This bug seems to be limited to multi-trial experiments, as things work fine for single trial experiments. The plot also works fine on the main plot that plots all trials, but not when viewing an individual trial under the experiment. I can see the other metrics in the drop down but clicking on them does nothing. I have confirmed this behavior across multiple browsers on Linux/Windows/Mac.

### Reproduction Steps

1. Select a multi-trial experiment in the UI (e.g., a hyperparam tuning experiment)
2. Click on one of the trials under that experiment
3. Try to select an alternative metric to be displayed in the plot.

### Expected Behavior

The plot should show the selected metric. 

### Screenshot

n/a

### Environment

- Device or hardware: 
- OS: [e.g. iOS]: Multiple (Windows 10, Ubuntu, Mac OS)
- Browser Chrome/Firefox
- Version: Determined 0.19.5

**Comment by varlogtim** [comment]
Hello @zjorgensenbits , thanks for the report! This issue should be resolve in 0.19.6. Could you upgrade and see if you are still experiencing it?

https://github.com/determined-ai/determined/pull/5228
