### ISSUE TITLE
🐛[bug] "CUDA out of memory" error when trying to run distributed training

### ISSUE THREAD

**Issue by psydok** [determined-ai/determined#5418]
### Describe the bug

When running distributed training with batch size 8 on each machine, I get an error:

> [] [rank=0] RuntimeError: CUDA out of memory. Tried to allocate 824.00 MiB (GPU 0; 7.93 GiB total capacity; 4.71 GiB already allocated; 362.38 MiB free; 5.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF 

But if I run without distributed learning (`slots_per_trial: 1` and `global_batch_size: 8`), there is no error on any of the machines.

```yaml
hyperparameters:
  learning_rate: 0.0001
  global_batch_size: 16
  num_worker: 4
  num_epochs: 10
  gradient_accumulation_steps: 1

min_validation_period:
   batches: 200

max_restarts: 0

searcher:
  name: single
  metric: val_loss
  max_length:
      batches: 8000
  smaller_is_better: true

entrypoint: model_def:PlTrial

resources:
  resource_pool: test-cluster
  slots_per_trial: 2
```

### Reproduction Steps

1. In *config.yaml* I set `slots_per_trial: 2` and `global_batch_size: 8 * slots_per_trial` (i.e. `global_batch_size: 16`).
2. Run the experiment: `det experiment create config.yaml .`
3. In *model_def:PlTrial* through `self.context.get_per_slot_batch_size()` I pull up the batch size for training (I check if
which returns 8 for each GPU on different machines).
4. I get an error:
```bash
none]>
[2022-11-14 05:47:35] [0381c62a] [rank=0] Traceback (most recent call last):
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     return _run_code(code, main_globals, None,
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     exec(code, run_globals)
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/harness.py", line 132, in <module>
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     sys.exit(main(args.train_entrypoint))
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/harness.py", line 123, in main
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     controller.run()
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/pytorch/_pytorch_trial.py", line 274, in run
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     self._run()
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/pytorch/_pytorch_trial.py", line 282, in _run
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     metrics = self._train_for_step(
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/pytorch/_pytorch_trial.py", line 440, in _train_for_step
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     tr_metrics = self.trial.train_batch(
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/pytorch/lightning/_adapter.py", line 375, in train_batch
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     metrics = self._pls.lm.training_step(*train_args)  # type: ignore
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/run/determined/workdir/model.py", line 63, in training_step
none]>
[2022-11-14 05:47:35] [0381c62a] [rank=0]     audio_features = self.model.encoder(input_ids)
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     return forward_call(*input, **kwargs)
...
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     w = F.softmax(qk.float(), dim=-1).to(q.dtype)
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]   File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 1680, in softmax
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0]     ret = input.softmax(dim)
<none> [2022-11-14 05:47:35] [0381c62a] [rank=0] RuntimeError: CUDA out of memory. Tried to allocate 824.00 MiB (GPU 0; 7.93 GiB total capacity; 4.71 GiB already allocated; 362.38 MiB free; 5.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
<none> [2022-11-14 05:47:35] [a54ac129] [rank=1] Traceback (most recent call last):
none]>
[2022-11-14 05:47:35] [a54ac129] [rank=1] Traceback (most recent call last):
<none> [2022-11-14 05:47:35] [a54ac129] [rank=1]   File "/opt/conda/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 145, in _allreduce_async
<none> [2022-11-14 05:47:35] [a54ac129] [rank=1]     handle = getattr(mpi_lib, function)(tensor, output, divisor,
<none> [2022-11-14 05:47:35] [a54ac129] [rank=1] RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.


```

### Expected Behavior

I want to start distributed learning.
I expect to get a learning rate gain by training distributed on the same batch size on 2 machines (8 * 2) and expect to get the same validation metrics as without distributed training.

### Screenshot

-

### Environment

- Device or hardware: Nvidia gtx 1080 and Nvidia gtx 1080ti
- OS: Linux
- Version: determined==0.19.4

**Comment by psydok** [comment]
Can you please tell me if it is possible to set a dynamic batch size for each GPU from the cluster?

**Comment by ioga** [comment]
>But if I run without distributed learning (slots_per_trial: 1 and global_batch_size: 8), there is no error on any of the machines.

there's a small memory overhead associated with distributed training. so if a model worked fine with batch size of 8 on a single GPU, but had little memory headroom, there's a risk it won't fit in distributed setting. try setting a lower batch size, e.g. maybe 6 per GPU, and see if that works.

**Comment by psydok** [comment]
> there's a small memory overhead associated with distributed training. so if a model worked fine with batch size of 8 on a single GPU, but had little memory headroom, there's a risk it won't fit in distributed setting. try setting a lower batch size, e.g. maybe 6 per GPU, and see if that works.

Thanks! It's work.

> can you elaborate what do you mean by "dynamic batch size"?

I have 2 GPU, GPU0 is 8gb and GPU1 is 16gb. I would like to install batch_size so that GPU0 handles batch_size=6, and GPU1 batch_size=12 (because it has more space).

**Comment by ioga** [comment]
> I have 2 GPU, GPU0 is 8gb and GPU1 is 16gb. I would like to install batch_size so that GPU0 handles batch_size=6, and GPU1 batch_size=12 (because it has more space).

Unfortunately we don't support that, and I don't believe horovod or torch DDP have support for that out of the box either.

In a heterogeneous configuration you need to be really mindful about the performance, because you'll typically be bottlenecked by the slowest card you have. it very well may be possible that training on the single larger/newer GPU will end up faster than distributed training on both. 

it's recommended to run distributed training on the same homogeneous hardware.
