### ISSUE TITLE
🤔[question] How can I commit a running container of a shell job to a image in determined-ai?

### ISSUE THREAD

**Issue by EliomEssaim** [determined-ai/determined#5435]
### Describe your question

I use determined-ai in shell job mode. 
I have run a container in determined-ai for a while, but recently I want to transfer my task to another machine. I found I have to push the container to a docker hub first, then I can use it in another machine (by writing YAML). But I cannot find any CLI commands to be helpful.
That means I cannot commit a running container of a shell job to a image in determined-ai. I have to maintain a version of the container which is not in use, but records everything changes in environments so as to be ready to be committed to a docker hub in a machine without determined-ai.
It's silly. But I have not found useful information. How to solve it? Thanks.

**Comment by ioga** [comment]
hello, just to clarify, are you looking for a way to do `docker commit` on a running shell job container within determined?

**Comment by EliomEssaim** [comment]
> hello, just to clarify, are you looking for a way to do `docker commit` on a running shell job container within determined?

yes

**Comment by ioga** [comment]
we don't have support for that unfortunately. I don't believe kubernetes has a way to do that either.

as a workaround, if you are running determined with agents, and assuming you have direct access to the agents, you can ssh directly into the agent node which is running your shell, and run the `docker commit ...` and `docker push ...` commands there.

I can see why this workflow is attractive for you, however it's somewhat limited: when running applications at scale, people usually like to have "reproducible builds", e.g. container images built from `Dockerfiles` where it's clear what went into the image, as opposed to an opaque hand-crafted "committed" image.

**Comment by EliomEssaim** [comment]
> we don't have support for that unfortunately. I don't believe kubernetes has a way to do that either.
> 
> as a workaround, if you are running determined with agents, and assuming you have direct access to the agents, you can ssh directly into the agent node which is running your shell, and run the `docker commit ...` and `docker push ...` commands there.
> 
> I can see why this workflow is attractive for you, however it's somewhat limited: when running applications at scale, people usually like to have "reproducible builds", e.g. container images built from `Dockerfiles` where it's clear what went into the image, as opposed to an opaque hand-crafted "committed" image.

ok, maybe I have to familar with the new workflow. Thanks for your kindly reply.
