### ISSUE TITLE
🤔[question] how to convert bn to syncbn

### ISSUE THREAD

**Issue by caiduoduo12138** [determined-ai/determined#5648]
### Describe your question

Hi,
I attemp to convert the BN module to sync_BN. Can you provide a demo? I directly use the api:torch.nn.SyncBatchNorm.convert_sync_batchnorm(model), but it has some error. The cluster has 4 machines and each machine has 8 gpus. The error is:
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by ioga** [comment]
hello,

`torch.nn.SyncBatchNorm.convert_sync_batchnorm` runs torch DDP batchnorm, while you're probably using our default horovod distributed training. Few options:

1. use another `convert_` helper which converts it to horovod syncbatchnorm, e.g. https://github.com/determined-ai/determined/blob/514eb2c899c822c35b716660a989b8f2ba380cd4/examples/computer_vision/efficientdet_pytorch/model_def.py#L408 or https://github.com/determined-ai/determined/blob/b3a34baa7dcca788a090120a17f9a4f8dc1a4184/model_hub/model_hub/mmdetection/utils.py#L95
2. use horovod's `SyncBatchNorm` directly instead: https://horovod.readthedocs.io/en/stable/api.html#horovod.torch.SyncBatchNorm
3. switch from using horovod to torch DDP: https://docs.determined.ai/latest/training/submit-experiment.html?highlight=torch_distributed#pytorch-distributed-launcher
