### ISSUE TITLE
🐛[bug] Error running 

### ISSUE THREAD

**Issue by MiChaelinzo** [determined-ai/determined#6142]
### Describe the bug

Master not found at localhost:8080. Hint: Remember to set the DET_MASTER environment variable to the correct Determined master IP and port or use the '-m' flag.
Failed to list experiments: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235986C7250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

### Reproduction Steps

1. Went to terminal to type a code
2. For example: det experiment list
3. The error will show 

### Expected Behavior

To run the application

### Screenshot

<img width="635" alt="Screenshot 2023-03-04 124759" src="https://user-images.githubusercontent.com/68110223/222892351-97509c23-a5c3-400a-b208-c18aadb7fa4d.png">

### Environment

- Device or hardware: [e.g. iPhone6, Nvidia A100]
- OS: Windows 11 Pro [e.g. iOS]
[DxDiag.txt](https://github.com/determined-ai/determined/files/10887999/DxDiag.txt)

**Comment by ioga** [comment]
hello, can you describe how did you install determined?

**Comment by MiChaelinzo** [comment]
@ioga I installed determined via CLI

**Comment by ioga** [comment]
if you were following the quickstart guide, it calls for `det deploy local cluster-up` [in step 1 here](https://docs.determined.ai/latest/quickstart-mdldev.html#run-a-local-single-cpu-gpu-training-job). Did you run that, or did you follow some other set of instructions?

I'd also highlight that we don't support cluster installation on windows natively, but WSL2 should work.

here's more docs for [det deploy](https://docs.determined.ai/latest/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-prem/deploy.html) or [other installation flavors](https://docs.determined.ai/latest/cluster-setup-guide/deploy-cluster/index.html).

**Comment by MiChaelinzo** [comment]
Alright, thanks, and yeah I am a hackathon participant. So I can't also run it in my Windows 11 Pro?

**Comment by MiChaelinzo** [comment]
Can I run it on kali linux wsl2?

**Comment by MiChaelinzo** [comment]
I got new error 
````
PS C:\Users\micha\Downloads\Pokemon-Terminal> det deploy local cluster-up
Traceback (most recent call last):
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\determined\cli\cli.py", line 211, in main
    parsed_args.func(parsed_args)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\determined\deploy\local\cli.py", line 16, in handle_cluster_up
    cluster_utils.cluster_up(
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\determined\deploy\local\cluster_utils.py", line 224, in cluster_up
    cluster_down(cluster_name, delete_db)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\determined\deploy\local\cluster_utils.py", line 257, in cluster_down
    master_down(master_name=cluster_name, delete_db=delete_db)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\determined\deploy\local\cluster_utils.py", line 207, in master_down
    docker_compose(["down", "-t", "1"], master_name)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\determined\deploy\local\cluster_utils.py", line 89, in docker_compose
    process_env["INTEGRATIONS_PROXY_ADDR"] = get_proxy_addr()
                                             ^^^^^^^^^^^^^^^^
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\site-packages\determined\deploy\local\cluster_utils.py", line 69, in get_proxy_addr
    s = subprocess.check_output(proxy_addr_args, encoding="utf-8")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\micha\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
Failed to Create a Determined cluster 
```

**Comment by ioga** [comment]
>yeah I am a hackathon participant

you can join our [community slack](https://join.slack.com/t/determined-community/shared_invite/zt-cnj7802v-KcVbaUrIzQOwmkmY7gP0Ew) and ask for the cloud cluster invite in the `#hackathon` channel. then you won't have to run your own cluster.

>So I can't also run it in my Windows 11 Pro?

no, we don't support it, and the new error you've posted confirms it.

>Can I run it on kali linux wsl2?

Usually people run on ubuntu or redhat flavors. It'll probably work on Kali, but I haven't heard of anyone doing that, so can't confirm.

**Comment by MiChaelinzo** [comment]
<img width="862" alt="Screenshot 2023-03-06 143814" src="https://user-images.githubusercontent.com/68110223/223100664-0f3205cf-7272-497b-88e5-59fa53c49f5b.png">

having trouble with wsl2 kali linux distro

**Comment by MiChaelinzo** [comment]
<img width="859" alt="Screenshot 2023-03-06 152200" src="https://user-images.githubusercontent.com/68110223/223109159-3811d0aa-7029-49ef-af05-f0fc64a0dd2b.png">

**Comment by MiChaelinzo** [comment]
I got docker installed etc. in Kali Linux distro

**Comment by ioga** [comment]
will close this one since you're getting help on slack.
