### ISSUE TITLE
🐛[bug] temporary shell key file has too open permissions on Windows 10

### ISSUE THREAD

**Issue by Violin9906** [determined-ai/determined#6433]
### Describe the bug

When trying to connect to an existing determined instance using
```shell
det shell start
```
on Windows 10, the private key seems to have too open permissions that openSSH ignored it:
```
Warning: Permanently added '5e13a189-e87f-4091-9521-dc5a69759b6e' (RSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'C:/Users/me/AppData/Local/Temp/tmp9ie33sne' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "C:/Users/me/AppData/Local/Temp/tmp9ie33sne": bad permissions
root@5e13a189-e87f-4091-9521-dc5a69759b6e: Permission denied (publickey).
```

### Reproduction Steps

1. install determined pip package on windows
```
pip install determined
```
2. set DET_MASTER to the existing determined instance
3. try open a shell
```
det shell start
```

### Expected Behavior

It should work like opening a shell in the container. I've tried the same operations on an Ubuntu machine, which succeeded.

### Screenshot

![捕获](https://user-images.githubusercontent.com/30993803/229449520-2b60db3a-0171-4ca7-ae2c-c351005feb48.PNG)

### Environment

- Device or hardware: i5-10400F, RTX2060
- OS: Windows 10 LTSC 21H2
- Python version: 3.8.16 (in conda venv)
- Determined pip package version: 0.21.0
- Determined instance version: 0.21.0 (installed on k8s)

**Comment by ioga** [comment]
hello, thank you for report. Windows issues are often environment-specific and tough to reproduce. 

1. Can you try patching your local python determined code like this, and see if it solves the issue:
```
diff --git a/harness/determined/cli/shell.py b/harness/determined/cli/shell.py
index 42b710cdb..94eb09f6a 100644
--- a/harness/determined/cli/shell.py
+++ b/harness/determined/cli/shell.py
@@ -100,6 +100,7 @@ def _prepare_key(retention_dir: Union[Path, None]) -> Tuple[ContextManager[IO],
         # by name on Windows, which prevents the ssh process from reading it.
         fd, path = tempfile.mkstemp(text=True)
         f = open(fd, "w")
+        os.chmod(path, 0o600)
 
         @contextlib.contextmanager
         def file_closer() -> Iterator[IO]:
```

you can discover the location for this file python executing this in python:
```
import determined.cli.shell
print(determined.cli.shell.__file__)
```

2. if this does not help, can you please try `det shell start --show-ssh-command` and let us know if that works?

**Comment by Violin9906** [comment]
Hi! Thanks for replying! The patch didn't work but I've tried another way:
```bash
pip install oschmod
```
and replace `os.chmod(path, 0o600)` to:
```python
import oschmod
oschmod.set_mode(path, "600")
```
and it WORKED!
It seems that python's default `os.chmod ` is buggy on Windows: [Link](https://stackoverflow.com/questions/60139536/python-chmod-for-windows)

For reference, the command `det shell start --show-ssh-command` outputs:
```bash
ssh -o "ProxyCommand=C:\Users\me\.miniconda3\envs\det\python.exe -m determined.cli.tunnel ai.lan:80 %h" -o StrictHostKeyChecking=no -tt -o IdentitiesOnly=yes -i C:/Users/me/AppData/Local/determined/determined/Cache/shell/888f4b2e-ab91-4dd9-8798-cd230d97e55b/key root@888f4b2e-ab91-4dd9-8798-cd230d97e55b
```

**Comment by ioga** [comment]
Thank you for debugging this, very helpful. Glad to hear it works for you.

We'll take a look at this third-party package and see if we can pull it in as a dependency (or if we can implement the same ourselves).

**Comment by Violin9906** [comment]
I find another related issue today. When I use the ssh command output by `--show-ssh-command`, the same error happens:
```bash
ssh -o "ProxyCommand=C:\Users\me\.miniconda3\envs\det\python.exe -m determined.cli.tunnel ai.lan:80 %h" -o StrictHostKeyChecking=no -tt -o IdentitiesOnly=yes -i C:/Users/me/AppData/Local/determined/determined/Cache/shell/deddf0c2-ff34-42af-809c-0bbcbd48a616/key root@deddf0c2-ff34-42af-809c-0bbcbd48a616
C:\Users\me\.miniconda3\envs\det\lib\runpy.py:127: RuntimeWarning: 'determined.cli.tunnel' found in sys.modules after import of package 'determined.cli', but prior to execution of 'determined.cli.tunnel'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'C:/Users/me/AppData/Local/determined/determined/Cache/shell/deddf0c2-ff34-42af-809c-0bbcbd48a616/key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "C:/Users/me/AppData/Local/determined/determined/Cache/shell/deddf0c2-ff34-42af-809c-0bbcbd48a616/key": bad permissions
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'C:/Users/me/AppData/Local/determined/determined/Cache/shell/deddf0c2-ff34-42af-809c-0bbcbd48a616/key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "C:/Users/me/AppData/Local/determined/determined/Cache/shell/deddf0c2-ff34-42af-809c-0bbcbd48a616/key": bad permissions
root@deddf0c2-ff34-42af-809c-0bbcbd48a616: Permission denied (publickey).
```
My temporary solution is to change the key file permission manually by `oschmod`, but it will be helpful if this can be done automatically.

**Comment by MikhailKardash** [comment]
We decided to include this third party package. Thanks again for the report!
