### ISSUE TITLE
🐛[bug] Experiment comparison is no longer available in web UI

### ISSUE THREAD

**Issue by nnevatie** [determined-ai/determined#6451]
### Describe the bug

Previous versions of the web UI used to allow the user to select a number of experiments and to compare them via the action-dropdown directly.

This is no longer possible in version `0.20.1`.

Using TensorBoard for comparing experiments is a workaround, but it is not as usable, as the data loads slowly and the TB sessions are prone to timeouts.

### Reproduction Steps

1. Enter web UI experiments view.
2. Select multiple experiments by ticking their checkboxes on the left.
3. Open actions dropdown from `Select an action...`
4. Observe missing `Compare` action.

### Expected Behavior

The user should be able to compare experiments within the web UI.

### Screenshot

![image](https://user-images.githubusercontent.com/7149440/229701509-11078d93-9f08-4eac-8e7b-57c71420a20c.png)

### Environment

- Device or hardware: Desktop
- OS: Windows 11
- Browser: Chrome, latest

**Comment by ClaireNeveu** [comment]
Hi @nnevatie, are you thinking of the "Compare trials" option that's available for multi-trial experiments?
![Screen Shot 2023-04-04 at 10 48 44](https://user-images.githubusercontent.com/1002726/229832993-9c7e27c9-7121-4834-9367-6a2481b9dbff.png)

**Comment by nnevatie** [comment]
Hi, @ClaireNeveu. In the past I remember being able to compare experiments, even if they were being run on different resource pools. Here's an example of a past comparison - notice the differing experiment IDs:
![image](https://user-images.githubusercontent.com/7149440/229986596-5f5d28d7-cfa4-4d76-b979-13ae809d7646.png)

**Comment by ClaireNeveu** [comment]
To my knowledge we've never supported this feature. What you posted looks a lot like our multi-trial experiment view but with an extra column added. You might have been running a fork of determined that had this feature added.

If you can point to a version of determined that had this feature I'll re-open the thread but for now I'm closing it.

**Comment by nnevatie** [comment]
For reference, the feature existed during versions `0.18.3` - `0.19.5`:

This is the introduction of the feature: https://github.com/determined-ai/determined/pull/4410

And this is the removal of it: https://github.com/determined-ai/determined/pull/4820

**Comment by ClaireNeveu** [comment]
Ah, apologies, this was not intended to be released, it looks like it snuck by us. We are working on a much more robust version of this feature presently that should be out later this year.

**Comment by nnevatie** [comment]
> We are working on a much more robust version of this feature presently that should be out later this year.

Ok, makes sense. Thanks!
