### ISSUE TITLE
🤔[question] After running det deploy local cluster-up, Failed to Create a Determined cluster:

### ISSUE THREAD

**Issue by ys0123** [determined-ai/determined#6678]
### Describe the Question 
Hello.
I run the commands:
det deploy local cluster-up

I got an error:
ERROR
The requested URL could not be retrieved

How can I successfully start the cluster?
Thanks!

### screen shot
Creating network determined_default...
Creating determined_determined-db_1...
Waiting for determined_determined-db_1...
Creating determined_determined-master_1...
Stopping determined_determined-master_1
Removing determined_determined-master_1
Stopping determined_determined-db_1
Removing determined_determined-db_1
Removing network determined_default
![2023-04-29_163318](https://user-images.githubusercontent.com/80317523/235290096-70e10586-3890-4a8d-9a18-c1a470f7fc27.png)

### Reproduction Steps
1. python -m venv ~/.virtualenvs/test
2. . ~/.virtualenvs/test/bin/activate
3. pip install determined
4. det deploy local cluster-up

### Expected Behavior
Start a cluster locally.

### Environment
Device or hardware: Nvidia GTX2060 Super
CUDA:10.2
Driver:440.33.01
OS: CentOS7.9
Determined:0.21.2

### Additional Context
No response

**Comment by tara-det-ai** [comment]
@ys0123 

- Make sure you have Docker installed and the Docker daemon is running. If you do not have Docker installed, you can follow the [instructions](https://docs.determined.ai/latest/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-prem/requirements.html).

- If you already have Docker installed and running, revisit the [Quickstart for Model Developers](https://docs.determined.ai/latest/quickstart-mdldev.html#quickstart-for-model-developers) and let us know if you run into any more issues.

**Comment by ioga** [comment]
it seems you've got squid setup as a proxy, which messes up the access to a service running locally. can you please try disabling it for localhost? perhaps do `export NO_PROXY=localhost,127.0.0.1`?

**Comment by ys0123** [comment]
@tara-det-ai 

Hi. I already have Docker and running correctly. 

> (test) [xxx@xxx determined_ai]$ docker --version
Docker version 23.0.3, build 3e7cbfd

I followed the [Quickstart for Model Developers](https://docs.determined.ai/latest/quickstart-mdldev.html#quickstart-for-model-developers) and got an error on 1. det deploy local cluster-up.

Do you have any ideas?

**Comment by ys0123** [comment]
@ioga 

Thanks! 
I could start `det deploy local cluster-up` after `export NO_PROXY=localhost,127.0.0.1`.

but I got another error.
I followed the Quickstart for Model Developers and got an error on 2. det deploy local cluster-up.

> [2023-04-30T03:07:10.055924Z]          || ERROR: Trial 1 (Experiment 1) was terminated: allocation failed: task failed without an associated exit code: starting container: starting container: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.3, please update your driver to a newer version, or use an earlier cuda container: unknown
Trial log stream ended. To reopen log stream, run: det trial logs -f 1

I will try update CUDA later.
Thanks!
