### ISSUE TITLE
🐛[bug] The output of "det slot" is not right?

### ISSUE THREAD

**Issue by zebin-dm** [determined-ai/determined#6800]
### Describe the bug

When i upgrade determined from version 0.21.1 to 0.22.0. The output of "det slot" is not right?

### Reproduction Steps

1.  upgrade determined from version 0.21.1 to 0.22.0
2. det slot 

### Expected Behavior

Agent id :  used to be hostname, but now defalut,.
Enabled   | Draining   | Allocation ID   | Task Name   | Type   | Device : though some task running on the gpu, but  the value is not right, 

### Screenshot

 Agent ID   | Resource Pool   |   Slot ID | Enabled   | Draining   | Allocation ID   | Task Name   | Type   | Device
------------+-----------------+-----------+-----------+------------+-----------------+-------------+--------+----------
 default    | default         |         0 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         1 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         2 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         3 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         4 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         5 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         6 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         7 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         0 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         1 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         2 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         3 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         4 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         5 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         6 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         7 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         8 | True      | False      | FREE            | FREE        | cuda   |
 default    | default         |         9 | True      | False      | FREE            | FREE        | cuda   |

### Environment

- Device or hardware: [ Nvidia A100]
- OS: [ubuntu]
- Browser [e.g. chrome]
- Version [0.22.0]

**Comment by zebin-dm** [comment]
> hello, just to confirm, are you running on kubernetes?

Yes, we running on kubernetes. and deploy with helm.

**Comment by ioga** [comment]
we are aware of the `det slot` regression, and we are working on it.

**Comment by ioga** [comment]
this was fixed a long time ago - sorry for not attaching PR to the issue.
