### ISSUE TITLE
🤔[question] Using AMD GPU with ROCM

### ISSUE THREAD

**Issue by ChrisAi89** [determined-ai/determined#6856]
### Describe your question

I would like to run my determinedAI cluster with a AMD GPU, hence ROCM. Is there a way to start the cluster using `det deploy local cluster-up` which automatically uses the ROCM framework?
Thanks and best whises

**Comment by ioga** [comment]
hello,

`det deploy` does not support ROCm at this time. Please use the [linux packages](https://docs.determined.ai/latest/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-prem/linux-packages.html#master-and-agent) instead.

Also note our environment images are currently at ROCm 5.0 which is a bit out of date and may not be compatible with the latest amd drivers.
