### ISSUE TITLE
Question for Installing Det for Ubuntu by Docker🤔[question] 

### ISSUE THREAD

**Issue by Q1ngS0ng** [determined-ai/determined#6917]
### Describe your question

When i run "docker run  -v "$PWD"/master.yaml:/etc/determined/master.yaml     determinedai/determined-master:0.22.1", I get " error mounting "/home/user/master.yaml" to rootfs at "/etc/determined/master.yaml""

**Comment by Q1ngS0ng** [comment]
I cannot find the keyword which defines the file mounted in default master configuration file.

**Comment by ioga** [comment]
>I cannot find the keyword which defines the file mounted in default master configuration file.

sorry, what file do you mean? the error is coming from the `docker run -v` argument. are there any other error details? does `/home/user/master.yaml` exist?
