### ISSUE TITLE
🤔[question] How to access more GPU resources？

### ISSUE THREAD

**Issue by wu19841918** [determined-ai/determined#6951]
### Describe your question

Hi！ I am currently learning to use the Determined. At present, we have 8 machines, one of which is set as the master and the others as the agent. Each machine has 4 GPUs, and each machine corresponds to a different agent label. Now the docker containers can only access up to 4 GPUs. What should I do if I want to link 8 GPUs? Please let me know whether it can be operated or not. Thank you very much.

**Comment by ioga** [comment]
>Now the docker containers can only access up to 4 GPUs.

what exactly do you mean by that? 

distributed training experiments in this setup should be able to access all 8 GPUs (i.e. `slots_per_trial: 8`).

notebooks, shells, and commands should be able to use up to 4 GPUs max at a time, as there's no way to "unite" the nodes together in a transparent way.

**Comment by wu19841918** [comment]
In distributed training experiment, is it possible to use 8GPUs from two different agent_label (each agent_label has 4 GPUs)?

**Comment by ioga** [comment]
no, it is not possible. moreover, `agent_label` option has been removed in 0.20.0 several months ago: https://docs.determined.ai/latest/release-notes.html#version-0-20-0

the point of `agent_label` (and its replacement, resource pool configuration) was to have completely separated pools of resources. if you want to use the machines together, they should not have agent labels (in pre-0.20.0 world) and be in the same resource pool.

**Comment by wu19841918** [comment]
Thanks for your reply! As a beginner of Determined, we still have several questions on how to config the determined cluster in order to put all GPUs on different machines together. The version of determined we are using is 0.19.7. For each agent, we have set the label in agent-config.yaml. Below is an example:
master_host:XXX.XX.XX.XX
master_port:8080
agent_id:3090_91
label:rtx3090_91
Do we need to upgrade the determined to the version above 0.20 and get rid of the 'label' in agent-config.yaml?

**Comment by wu19841918** [comment]
Thanks for your reply! As a beginner of Determined, we still have several questions on how to config the determined cluster in order to put all GPUs on different machines together. The version of determined we are using is 0.19.7. For each agent, we have set the label in agent-config.yaml. Below is an example:
master_host:XXX.XX.XX.XX
master_port:8080
agent_id:3090_91
label:rtx3090_91
Do we need to upgrade the determined to the version above 0.20 and get rid of the 'label' in agent-config.yaml?

**Comment by rb-determined-ai** [comment]
I think you just need to remove the label from the agent config and from all your experiment configs.  It's not a required field.

**Comment by wu19841918** [comment]
Thank you for your reply. It was a great help to me. 

> I think you just need to remove the label from the agent config and from all your experiment configs. It's not a required field.
