### ISSUE TITLE
GPU's suddenly unavailable when deploying on Kubernetes due to Insufficient nvidia.com/gpu [question]

### ISSUE THREAD

**Issue by Jeremy009** [determined-ai/determined#7044]
Hi,

We are running a Kubernetes cluster on an Nvidia DGX 2 and we have successfully deployed Determined (V0.17.11) on that cluster in the past.

Unfortunately since a couple of days we are unable to launch new notebooks or shells with GPU support, but notebooks and shells started with GPU support continue on running. Furthermore the cluster allocation mentions 0% while in reality some GPU's are still in use and GPU usage (e.g. 5/8 GPU's in use) does not appear:
![Screenshot 2023-06-02 at 13 48 02](https://github.com/determined-ai/determined/assets/42143613/bab1872b-f211-475b-a711-2feaeccdf88f)

Launching new notebooks/shells without GPU's (e.g. resources: agent_label: '' devices: null resource_pool: kubernetes slots: 0)
works, but requests with GPU's results in an eternal "assigned" state. In the Kubernetes dashboard we see that scheduling has failed due to Insufficient nvidia.com/gpu: 
![Screenshot 2023-06-02 at 13 51 57](https://github.com/determined-ai/determined/assets/42143613/cf6454eb-1e2d-437f-8871-c0b6c11b8f25)

The same message also appears in the logs of the determined-master-deployment logs:
![Screenshot 2023-06-02 at 13 56 13](https://github.com/determined-ai/determined/assets/42143613/a7fddb23-cf4f-45eb-b5ea-ebb8f8b43bf4)

And finally we see in the cluster's resource pool we see that there is no connected agent and that there is no aux container running:
![Screenshot 2023-06-02 at 14 03 03](https://github.com/determined-ai/determined/assets/42143613/b1f400bf-0c9a-4328-bf7d-d5196dc6d5f7)

This seems to indicate that something is wrong with the determined deployment because - we suspect - the Determined master can not find the GPU's anymore. Restarting the determined-master-deployment pod from the Kubernetes dashboard did not help either. Restarting the whole DGX is possible, but should be avoided unless all other options are exhausted or if there is near certainity that that will fix the problem (some production containers are running on that cluster).

Any help with this or some tips or pointers towards useful documentation would be greatly appreciated!

**Comment by rb-determined-ai** [comment]
Hi @Jeremy009, I have requested somebody who is familiar with our k8s support take a look at this.

**Comment by ioga** [comment]
hello, one way to debug this is to look at what's happening at the kubernetes level:
1. kill/pause everything in determined.
2. setup `kubectl` to talk to your cluster.
3. `kubectl get pods` to see what's up - there should not be any determined tasks, only master and postgres pods + whatever else you run besides determined.
4. submit a job in determined.
5. run `kubectl get pods` again: there should be a pod corresponding to the job. you can see the pod name in the task logs as well.
6. inspect the pod `kubectl describe pod <POD NAME>` and check why it's not scheduling.
7. List the nodes via `kubectl get nodes` and see what's their status.

**Comment by Jeremy009** [comment]
Thanks for the quick reply!

I tried the above when launching a job in Determined with 1 GPU ( resource_pool: kubernetes slots: 1 weight: 1) which failed as expected. Describing the pod resulted in:

  **xxxxxxx@xxxxxxxxx:~$ kubectl -n determined describe pod cmd-0-05e7a180-2d80-46af-bfee-0dafe51102a5.1-sacred-tomcat**
  Name:         cmd-0-05e7a180-2d80-46af-bfee-0dafe51102a5.1-sacred-tomcat
  Namespace:    determined
  Priority:     0
  Node:         <none>
  Labels:       determined=05e7a180-2d80-46af-bfee-0dafe51102a5.1
  Annotations:  <none>
  Status:       Pending
  IP:           
  IPs:          <none>
  Init Containers:
    determined-init-container:
      Image:      determinedai/environments:cuda-11.1-pytorch-1.9-lightning-1.5-tf-2.4-gpu-5158dec
      Port:       <none>
      Host Port:  <none>
      Command:
        /run/determined/temp/k8_init_container_entrypoint.sh
      Args:
        7
        /run/determined/temp/tar/src
        /run/determined/temp/tar/dst
      Environment:  <none>
      Mounts:
        /run/determined/temp/ from entrypoint-volume (ro)
        /run/determined/temp/tar/dst from additional-files-volume (rw)
        /run/determined/temp/tar/src from archive-volume (ro)
        /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7ptxg (ro)
  Containers:
    determined-fluent-container:
      Image:      fluent/fluent-bit:1.6
      Port:       <none>
      Host Port:  <none>
      Command:
        /fluent-bit/bin/fluent-bit
        -c
        fluent.conf
      Environment:  <none>
      Mounts:
        /run/determined/fluent/ from det-fluent (rw)
        /run/determined/train/logs from det-logs (rw)
        /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7ptxg (ro)
    determined-container:
      Image:      determinedai/environments:cuda-11.1-pytorch-1.9-lightning-1.5-tf-2.4-gpu-5158dec
      Port:       <none>
      Host Port:  <none>
      Command:
        /run/determined/jupyter/notebook-entrypoint.sh
      **Limits:
        nvidia.com/gpu:  1
      Requests:
        nvidia.com/gpu:  1**
      Environment:
        PYTHONUSERBASE:       /run/determined/pythonuserbase
        DET_USER_TOKEN:       v2.public.eyJpZCI6MTY1OCwidXNlcl9pZCI6MTcsImV4cGlyeSI6IjIwMjMtMDYtMTBUMDk6MTI6NTUuNjk5Nzg4NTY1WiJ9o3snVMxM9RTuMF_dvKSWxhnxE-Lz87BWkh33lRzKUFeIAJjwhVIUdCacAFmqYk8tvDjPMPBjEPKfWWRcBQ9eAQ.bnVsbA
        DET_SEGMENT_ENABLED:  false
        DET_AGENT_ID:         k8agent
        DET_TASK_ID:          05e7a180-2d80-46af-bfee-0dafe51102a5
        DET_SESSION_TOKEN:    v2.public.eyJpZCI6MTM5MCwiYWxsb2NhdGlvbl9pZCI6IjA1ZTdhMTgwLTJkODAtNDZhZi1iZmVlLTBkYWZlNTExMDJhNS4xIn15Skuu8tzEaBl813hf-6UJGNieX6Pw6MFIg-_pwixJjl80hqz7UbgbXo5HVlJKTErkUjfWoHPh2U4Ra4i4aUAE.bnVsbA
        DET_USE_TLS:          false
        DET_TASK_TYPE:        NOTEBOOK
        NOTEBOOK_PORT:        2986
        DET_MASTER_PORT:      8080
        DET_ALLOCATION_ID:    05e7a180-2d80-46af-bfee-0dafe51102a5.1
        DET_USER:             jeremy
        NOTEBOOK_IDLE_TYPE:   kernels_or_terminals
        DET_CLUSTER_ID:       026fdf18-2f6c-4852-a17d-983f0bee44fe
        DET_MASTER:           10.109.12.3:8080
        DET_CONTAINER_ID:     b3cea12c-41eb-499d-954c-b14fbe19a0a5
        NOTEBOOK_CONFIG:      {"description":"Test-hello","bind_mounts":null,"environment":{"image":{"cpu":"determinedai/environments:py-3.8-pytorch-1.9-lightning-1.5-tf-2.4-cpu-5158dec","cuda":"determinedai/environments:cuda-11.1-pytorch-1.9-lightning-1.5-tf-2.4-gpu-5158dec"},"environment_variables":{},"ports":null,"force_pull_image":false,"pod_spec":{"metadata":{"creationTimestamp":null},"spec":{"volumes":[{"name":"nas-volume","persistentVolumeClaim":{"claimName":"pvc-nas"}},{"name":"nas-old-volume","persistentVolumeClaim":{"claimName":"pvc-old-nas"}},{"name":"notebook-volume","persistentVolumeClaim":{"claimName":"pvc-notebook"}}],"containers":[{"name":"determined-container","resources":{},"volumeMounts":[{"name":"nas-volume","mountPath":"/run/determined/workdir/projects"},{"name":"nas-old-volume","mountPath":"/data"},{"name":"notebook-volume","mountPath":"/run/determined/workdir/persistent-storage/"}]}]},"status":{}},"add_capabilities":null,"drop_capabilities":null},"resources":{"slots":1,"weight":1,"agent_label":"","resource_pool":"kubernetes","devices":null},"entrypoint":null,"idle_timeout":null,"notebook_idle_type":"kernels_or_terminals","work_dir":null,"debug":false}
        DET_MASTER_HOST:      10.109.12.3
        DET_MASTER_ADDR:      10.109.12.3
        DET_SLOT_IDS:         [0]
        DET_K8S_LOG_TO_FILE:  true
      Mounts:
        /data from nas-old-volume (rw)
        /dev/shm from det-shm-volume (rw)
        /opt/determined/wheels/determined-0.17.11-py3-none-any.whl from additional-files-volume (rw,path="3/opt/determined/wheels/determined-0.17.11-py3-none-any.whl")
        /run/determined from additional-files-volume (rw,path="0/run/determined")
        /run/determined/check_ready_logs.py from additional-files-volume (rw,path="6/run/determined/check_ready_logs.py")
        /run/determined/etc/group from additional-files-volume (rw,path="2/run/determined/etc/group")
        /run/determined/etc/passwd from additional-files-volume (rw,path="2/run/determined/etc/passwd")
        /run/determined/etc/shadow from additional-files-volume (rw,path="2/run/determined/etc/shadow")
        /run/determined/fluent/ from det-fluent (rw)
        /run/determined/info from additional-files-volume (rw,path="0/run/determined/info")
        /run/determined/jupyter from additional-files-volume (rw,path="6/run/determined/jupyter")
        /run/determined/jupyter/check_idle.py from additional-files-volume (rw,path="6/run/determined/jupyter/check_idle.py")
        /run/determined/jupyter/config from additional-files-volume (rw,path="6/run/determined/jupyter/config")
        /run/determined/jupyter/data from additional-files-volume (rw,path="6/run/determined/jupyter/data")
        /run/determined/jupyter/notebook-entrypoint.sh from additional-files-volume (rw,path="6/run/determined/jupyter/notebook-entrypoint.sh")
        /run/determined/jupyter/runtime from additional-files-volume (rw,path="6/run/determined/jupyter/runtime")
        /run/determined/pythonuserbase from additional-files-volume (rw,path="0/run/determined/pythonuserbase")
        /run/determined/task-logging-setup.sh from additional-files-volume (rw,path="1/task-logging-setup.sh")
        /run/determined/train/logs from det-logs (rw)
        /run/determined/workdir from additional-files-volume (rw,path="0/run/determined/workdir")
        /run/determined/workdir/README.ipynb from additional-files-volume (rw,path="6/run/determined/workdir/README.ipynb")
        /run/determined/workdir/persistent-storage/ from notebook-volume (rw)
        /run/determined/workdir/projects from nas-volume (rw)
        /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7ptxg (ro)
  Conditions:
    Type           Status
    PodScheduled   False 
  Volumes:
    nas-volume:
      Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
      ClaimName:  pvc-nas
      ReadOnly:   false
    nas-old-volume:
      Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
      ClaimName:  pvc-old-nas
      ReadOnly:   false
    notebook-volume:
      Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
      ClaimName:  pvc-notebook
      ReadOnly:   false
    det-shm-volume:
      Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
      Medium:     Memory
      SizeLimit:  <unset>
    archive-volume:
      Type:      ConfigMap (a volume populated by a ConfigMap)
      Name:      cmd-0-05e7a180-2d80-46af-bfee-0dafe51102a5.1-sacred-tomcat
      Optional:  false
    entrypoint-volume:
      Type:      ConfigMap (a volume populated by a ConfigMap)
      Name:      cmd-0-05e7a180-2d80-46af-bfee-0dafe51102a5.1-sacred-tomcat
      Optional:  false
    additional-files-volume:
      Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
      Medium:     
      SizeLimit:  <unset>
    det-logs:
      Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
      Medium:     Memory
      SizeLimit:  <unset>
    det-fluent:
      Type:      ConfigMap (a volume populated by a ConfigMap)
      Name:      cmd-0-05e7a180-2d80-46af-bfee-0dafe51102a5.1-sacred-tomcat
      Optional:  false
    kube-api-access-7ptxg:
      Type:                    Projected (a volume that contains injected data from multiple sources)
      TokenExpirationSeconds:  3607
      ConfigMapName:           kube-root-ca.crt
      ConfigMapOptional:       <nil>
      DownwardAPI:             true
  QoS Class:                   BestEffort
  **Node-Selectors:              <none>**
  **Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                               node.kubernetes.io/unreachable:NoExecute op=Exists for 300s**
  Events:
    Type     Reason            Age                  From               Message
    ----     ------            ----                 ----               -------
    **Warning  FailedScheduling  54s (x6 over 6m22s)  default-scheduler  0/1 nodes are available: 1 Insufficient nvidia.com/gpu.**


And launching a job without a GPU does work just fine. When getting and describing the nodes I get nothing that looks off:

kubectl get nodes
NAME          STATUS   ROLES                            AGE    VERSION
dgx2pc01   Ready       control-plane,master   445d   v1.23.4

But digging deeper:

**Comment by ioga** [comment]
> And launching a job without a GPU does work just fine. When getting and describing the nodes I get nothing that looks off:
> 
> kubectl get nodes
> NAME STATUS ROLES AGE VERSION
> dgx2pc01 Ready control-plane,master 445d v1.23.4
> 
> But digging deeper:
> kubectl describe node
> 
> Allocated resources:
> (Total limits may be over 100 percent, i.e., overcommitted.)
> Resource Requests Limits
> cpu 8300m (3%) 1 (0%)
> memory 22634Mi (2%) 840Mi (0%)
> ephemeral-storage 0 (0%) 0 (0%)
> hugepages-1Gi 0 (0%) 0 (0%)
> hugepages-2Mi 0 (0%) 0 (0%)
> nvidia.com/gpu 0 0
> Events:
> Type Reason Age From Message
> Warning ImageGCFailed 3m25s (x22667 over 78d) kubelet failed to get imageFs info: non-existent label "docker-images"

it seems you have only one node, and that reports having 0 gpus. this sounds wrong to me.

>All this seems to indicate to me that Determined is unable to find the GPU's when launching a job. But I must admit that I don't really know what could cause this or how to fix it. I do notice that:

our software doesn't try to "find" the GPUs, we just ask kubernetes to schedule a pod which has `nvidia.com/gpu: 1` in the resource requests. so, in this case, it seems like you've got something wrong with your kubernetes / nvidia-device-plugin setup which causes it to not detect any nvidia gpus.

**Comment by Jeremy009** [comment]
There is indeed only one node and it reports 0 GPU's

Capacity:
  cpu:                256
  ephemeral-storage:  1843217020Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             1056638624Ki
  nvidia.com/gpu:     0
  pods:               110

**Comment by ioga** [comment]
okay, it means this is not a problem on determined side. 
something is wrong with your kubernetes / nvidia-device-plugin setup.
