### ISSUE TITLE
🤔[question] Permission management for individual users

### ISSUE THREAD

**Issue by CHENBIN99** [determined-ai/determined#7088]
### Describe your question

Thank you very much for your great work!

 I have successfully built Determined on the local cluster and successfully run the demo provided. However, I noticed that different users can kill each other's tasks. I think this will happen in the future It will be inconvenient during use. May I ask if there are settings such as user rights management here to avoid such phenomena? In other words, how to achieve isolation between users.

Thanks.

**Comment by ioga** [comment]
hello, this can be done using [role-based access control feature](https://docs.determined.ai/latest/setup-cluster/security/rbac.html).

It is only available on Enterprise Edition. See [HPE Machine Learning Development Environment](https://www.hpe.com/us/en/solutions/artificial-intelligence/machine-learning-development-environment.html) page for more.

**Comment by CHENBIN99** [comment]
Thanks for your quick answer! 

Does that mean the enterprise edition can only be obtained from HP? I think some simple user isolation is also beneficial for some small teams, whether it can be applied to all versions in the future?

Thanks.

**Comment by ioga** [comment]
>Does that mean the enterprise edition can only be obtained from HP?

That is correct. Determined is a part of HPE, so the "paid version" of our software can be obtained through HPE sales process.

**Comment by CHENBIN99** [comment]
Thanks
