### ISSUE TITLE
What should I do if I need to average the results of multiple experiments to perform hyperparameters search🤔[question] 

### ISSUE THREAD

**Issue by BOOMKNIGHT** [determined-ai/determined#7118]
### Describe your question

What should I do if I need to average the results of multiple experiments to perform hyperparameters search? (the data was not split into batches)

**Comment by ioga** [comment]
hello, 

can you please elaborate what are you trying to achieve? in our system, hyperparameter search runs on trials within a single experiment.

**Comment by BOOMKNIGHT** [comment]
Hello, for example, running one dataset per experiment, I need this set of hyperparameters to be good on several datasets.

**Comment by ioga** [comment]
I'd suggest you should have your trial code do the training and/or validation on all your datasets together.

**Comment by BOOMKNIGHT** [comment]
Ok, I will try, thanks!

**Comment by ioga** [comment]
let us know if you need more help.
