### ISSUE TITLE
🤔[question] Jupyter Notebook Launch Issue

### ISSUE THREAD

**Issue by ashish-kumar-hpe** [determined-ai/determined#7119]
### Describe your question

I am trying to mount a Jupyter Notebook in Determined with my specified mountpath. Notebook launches but the mountpath is not mouted in the notebook. Any suggestion? I am providing mount-path like this...

Also what is the meaning of "work_dir" ? 

det -v
/usr/lib/python3.6/site-packages/OpenSSL/_util.py:6: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.bindings.openssl.binding import Binding
det 0.19.10

bind_mounts:
  - container_path: /etc/hosts
    host_path: /etc/hosts
    propagation: rprivate
    read_only: false
  - container_path: /ashish
    host_path: /home/ashish
debug: false
description: data-pipeline-test1
entrypoint: null
environment:
  add_capabilities: null
  drop_capabilities: null
  environment_variables: {}
  force_pull_image: false
  image:
    cpu: determinedai/environments:py-3.8-pytorch-1.12-tf-2.8-cpu-835d8b1
    cuda: determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.8-gpu-835d8b1
    rocm: determinedai/environments:rocm-5.0-pytorch-1.10-tf-2.7-rocm-835d8b1
  pod_spec: null
  ports: null
  proxy_ports: null
idle_timeout: null
notebook_idle_type: kernels_or_terminals
pbs: {}
resources:
  devices: null
  resource_pool: gpu
  slots: 1
  weight: 1
slurm: {}
work_dir: null

**I am also trying to launch using commandline but commandline is giving me errors.**

cat config.yaml
bind_mounts:
  - host_path: /home/ashish
    container_path: /ashish
debug: false
description: ashish-data-pipeline-test1
entrypoint: null
environment:
  add_capabilities: null
  drop_capabilities: null
  environment_variables: {}
  force_pull_image: false
  image:
    cpu: determinedai/environments:py-3.8-pytorch-1.12-tf-2.8-cpu-835d8b1
    cuda: determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.8-gpu-835d8b1
    rocm: determinedai/environments:rocm-5.0-pytorch-1.10-tf-2.7-rocm-835d8b1
  pod_spec: null
  ports: null
  proxy_ports: null
idle_timeout: null
notebook_idle_type: kernels_or_terminals
pbs: {}
resources:
  devices: null
  resource_pool: gpu
  slots: 1
  weight: 1
slurm: {}
work_dir: null

**det notebook start --config-file config.yaml**

**det notebook list**
/usr/lib/python3.6/site-packages/OpenSSL/_util.py:6: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.bindings.openssl.binding import Binding
CLI version 0.19.10 is less than master version 0.21.0. Consider upgrading the CLI.
 id                                   | username   | description                | state      | exitStatus                               | resourcePool
--------------------------------------+------------+----------------------------+------------+------------------------------------------+----------------
 5be3f1b5-3e16-49a2-b624-571575bf0614 | charlie    | data-pipeline-test1        | TERMINATED | allocation exited successfully           | gpu
 6af593af-5508-4555-ab56-d9821313d5a3 | charlie    | data-pipeline-test1        | TERMINATED | resources failed with non-zero exit code | gpu
 eb551e88-c7ef-4b55-a438-513aab23eb89 | charlie    | ashish-data-pipeline-test1 | RUNNING    |                                          | gpu

**Comment by ioga** [comment]
Hello,

>I am trying to mount a Jupyter Notebook in Determined with my specified mountpath. Notebook launches but the mountpath is not mouted in the notebook. Any suggestion? I am providing mount-path like this...

can you elaborate a bit, how do you tell it's not mounted?

>I am also trying to launch using commandline but commandline is giving me errors.

Per this message:

>CLI version 0.19.10 is less than master version 0.21.0. Consider upgrading the CLI.

We recommend you upgrade your CLI to 0.21.0; compatibility between 0.19.10 and 0.21.0 is not guaranteed which may be causing some of the errors you're seeing.

> /usr/lib/python3.6/site-packages/OpenSSL/_util.py:6: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.

We no longer support python 3.6, because it has been end-of-life'd at the end of 2021, so we'd recommend an upgrade.

>Also what is the meaning of "work_dir" ?

here's the configuration reference: https://docs.determined.ai/latest/reference/interface/job-config-reference.html

**Comment by ashish-kumar-hpe** [comment]
I am assuming that once I launch the Notebook, I should be able to see and access the mounted drives. 

![image](https://github.com/determined-ai/determined/assets/65278896/3e469a69-06c0-4fa0-b174-d34eda7f6212)

**Comment by ioga** [comment]
that's the current working directory listing. mounted directories won't show up there, unless they're mounted at the working dir (by default, `/run/determined/workdir`).

your `bind_mounts` config had two things: `container_path: /etc/hosts` and `container_path: /ashish`. so you need to check these paths. 

you should also see these when you run `mount`, although it's usually a bit noise.

**Comment by rb-determined-ai** [comment]
As I suggested in slack, you actually can mount things relative to the container's working directory by setting `container_path: ./ashish`

**Comment by rb-determined-ai** [comment]
resolved in slack channel.  Resolution was to set work_dir to `/` I think, which made `/ashish` visible in the notebook.
