### ISSUE TITLE
How do I use my own dataset?

### ISSUE THREAD

**Issue by Mrhs121** [determined-ai/determined#712]
Let's say I've already downloaded the data set.

The directory structure is as follows:
 -rw-r--r-- 1 dc2-user dc2-user  653 Jun 13 08:23 adaptive.yaml
-rw-r--r-- 1 dc2-user dc2-user  405 Jun 13 08:23 const.yaml
-rw-r--r-- 1 dc2-user dc2-user 1.5K Jun 15 22:27 data.py
-rw-r--r-- 1 dc2-user dc2-user  486 Jun 13 08:23 distributed.yaml
-rw-r--r-- 1 dc2-user dc2-user  555 Jun 13 08:23 layers.py
drwxrwxr-x 2 dc2-user dc2-user 4.0K Jun 15 22:20 MNIST_data
-rw-r--r-- 1 dc2-user dc2-user 4.0K Jun 15 22:27 model_def.py

The MNIST_data dir is myself dataset

When I use the command “det create ------” to create a experiment. Then the log from experiment page indicates that no data was found.

How do I use my own dataset?

**Comment by neilconway** [comment]
@Mrhs121 Hi! I believe we already discussed this via Slack. If so, can we close this issue?

**Comment by Mrhs121** [comment]
Of course. Thank you for your help

**Comment by neilconway** [comment]
Great!
