### ISSUE TITLE
connection error on WebUI when using simple examples🐛[bug] 

### ISSUE THREAD

**Issue by CAGeng** [determined-ai/determined#7276]
### Describe the bug

I run two commands:

pip install determined
sudo det deploy local cluster-up

then I create an experiment using examples mnist_pytorch_const

but webui shows [11a23c1d] [43] urllib3.connectionpool: Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8538c39af0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /api/v1/experiments/4/model_def

### Reproduction Steps

1.pip install determined
2.sudo det deploy local cluster-up
3.create an experiment using examples mnist_pytorch_const

### Expected Behavior

run the experiment normally

### Screenshot

![WX20230630-163107@2x](https://github.com/determined-ai/determined/assets/62201637/7b906fdb-338f-4391-8a2a-ed9b747042f1)

### Environment

- Device or hardware:  x86-64 cpu
- OS: ubuntu
- Version determined 0,23,1

**Comment by rb-determined-ai** [comment]
This is the first connection from the training job (inside the docker container) to the master (oustide the docker conatiner).   We have a bunch of extra debug statements to help with this exact scenario.  The code looks like this:

```python
    try:
        model_def_resp = bindings.get_GetModelDef(sess, experimentId=trial_info.experiment_id)
    except Exception as e:
        # Since this is the very first api call in the entrypoint script, and the call is made
        # before you can debug with a startup hook, we offer an overly-detailed explanation to help
        # sysadmins debug their cluster.
        resp_content = str(e)
        noverify = info.master_cert_file == "noverify"
        cert_content = None if noverify else info.master_cert_file
        if cert_content is not None:
            with open(cert_content) as f:
                cert_content = f.read()
        print(
            "Failed to download model definition from master.  This may be due to an address\n"
            "resolution problem, a certificate problem, a firewall problem, or some other\n"
            "networking error.\n"
            "Debug information:\n"
            f"    master_url: {info.master_url}\n"
            f"    endpoint: api/v1/experiments/{trial_info.experiment_id}/model_def\n"
            f"    tls_verify_name: {info.master_cert_name}\n"
            f"    tls_noverify: {noverify}\n"
            f"    tls_cert: {cert_content}\n"
            f"    response content: {resp_content}\n",
            file=sys.stderr,
        )
        raise
```

And if I simulate this failure, I see output like this:
```
[2023-06-30T14:46:22.482682Z] 6ead53a6 || Failed to download model definition from master.  This may be due to an address
[2023-06-30T14:46:22.482697Z] 6ead53a6 || resolution problem, a certificate problem, a firewall problem, or some other
[2023-06-30T14:46:22.482702Z] 6ead53a6 || networking error.
[2023-06-30T14:46:22.482706Z] 6ead53a6 || Debug information:
[2023-06-30T14:46:22.482710Z] 6ead53a6 ||     master_url: http://192.168.0.4:8080
[2023-06-30T14:46:22.482713Z] 6ead53a6 ||     endpoint: api/v1/experiments/1/model_def
[2023-06-30T14:46:22.482717Z] 6ead53a6 ||     tls_verify_name: None
[2023-06-30T14:46:22.482720Z] 6ead53a6 ||     tls_noverify: False
[2023-06-30T14:46:22.482724Z] 6ead53a6 ||     tls_cert: None
[2023-06-30T14:46:22.482728Z] 6ead53a6 ||     response content: HTTPConnectionPool(host='192.168.0.4', port=8080): Max retries exceeded with url: /api/v1/experiments/1/model_def (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f852e81dc40>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

Can you find these lines and share the output with me?  If there's any public IP addresses, feel free to scrub them, but let me know what they referred to (like, "XYZ was the public IP address of my master node" or something).

Lastly, based on the "connection timed out", I have a haunch that your problem might be a firewall that is configured to DROP incoming packets.  Do you know if that is the case?  You can check with `sudo iptables -L` and look at the `Chain INPUT (policy ...)` line.

**Comment by CAGeng** [comment]
Thank you for your detailed reply. I am not sure if the "extra debug statements to help with this exact scenario" you mentioned refers to running an experiment to execute the Python code you provided. I have set up a new experiment and specified it to run this Python code with an additional output line.
<img width="303" alt="image" src="https://github.com/determined-ai/determined/assets/62201637/bf6a39bd-faac-4bfc-a7fc-0ca93c3fee93">
<img width="888" alt="image" src="https://github.com/determined-ai/determined/assets/62201637/875073e9-dd1c-482e-b699-d32e822f1754">
<img width="586" alt="image" src="https://github.com/determined-ai/determined/assets/62201637/5982f8dd-ea4b-4da1-b2b3-c96df4c7490b">

As expected, the error "name 'bindings' is not defined" occurred. Although I was able to resolve the previous issue by changing the network environment and cannot reproduce the error now, I am still very interested in  learning about the troubleshooting methods you mentioned and understanding the reason for the previous error.

I am looking forward to receiving your further reply. I will close this issue later as the previous problem has been resolved.

**Comment by rb-determined-ai** [comment]
Sorry, what I am asking for is more of the logs from your original failed experiment.  Your screenshot does not include the output I need to help debug your situation.  But it is in the output of your logs, somewhere.  So if you want to provide the whole trial logs, that's fine, or if you just want to find the relevant output that looks like what I showed, that's also fine.
