### ISSUE TITLE
Determined on Kubernetes Issue with launching Jupyter Notebook🤔[question] 

### ISSUE THREAD

**Issue by ashish-kumar-hpe** [determined-ai/determined#7686]
### Describe your question

Hello,

I have installed Determined on Kubernetes Cluster and am trying to spin up a Jupyter Notebook. Jupyter Notebook launch is getting errored out. Error that i see in the UI is as follows in the log. This error indicates "ServiceAccount" related error. 

[2023-08-21 09:53:37] || INFO: Scheduling JupyterLab (blindly-settling-polliwog) (id: 57e4d8e5-0df9-4cea-a117-bd09ffc95527)
<info> [2023-08-21 09:53:38] [7f94294e] pods "cmd-0-57e4d8e5-0df9-4cea-a117-bd09ffc95527.1-uncommon-python" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000690000, 1000699999], spec.containers[1].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000690000, 1000699999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "nfd-worker": Forbidden: not usable by user or serviceaccount, provider "nvidia-driver": Forbidden: not usable by user or serviceaccount, provider "nvidia-gpu-feature-discovery": Forbidden: not usable by user or serviceaccount, provider "nvidia-mig-manager": Forbidden: not usable by user or serviceaccount, provider "nvidia-node-status-exporter": Forbidden: not usable by user or serviceaccount, provider "nvidia-operator-validator": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "hpe-ezmeral-csi-scc": Forbidden: not usable by user or serviceaccount, provider "nvidia-dcgm": Forbidden: not usable by user or serviceaccount, provider "nvidia-dcgm-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
<error> [2023-08-21 09:53:38] || ERROR: JupyterLab (blindly-settling-polliwog) was terminated: allocation failed: task failed without an associated exit code: pod actor exited while pod was running

**Comment by ashish-kumar-hpe** [comment]
Just wanted to communicate that this error is resolved after debugging the kubernetes environment and adding required scc permissions to determined namespace.

Before apply scc permissions
==================
[root@rhel8_installer ashish]# oc describe ns determined
Name:         determined
Labels:       kubernetes.io/metadata.name=determined
              pod-security.kubernetes.io/audit=restricted
              pod-security.kubernetes.io/audit-version=v1.24
              pod-security.kubernetes.io/warn=restricted
              pod-security.kubernetes.io/warn-version=v1.24
Annotations:  openshift.io/sa.scc.mcs: s0:c26,c20
              openshift.io/sa.scc.supplemental-groups: 1000690000/10000
              openshift.io/sa.scc.uid-range: 1000690000/10000
Status:       Active

No resource quota.

No LimitRange resource.


after applying scc permissions
====================
oc adm policy add-scc-to-user privileged -z default -n determined
clusterrole.rbac.authorization.k8s.io/system:openshift:scc:privileged added: "default"

oc describe ns determined
Name:         determined
Labels:       kubernetes.io/metadata.name=determined
              pod-security.kubernetes.io/audit=privileged
              pod-security.kubernetes.io/audit-version=v1.24
              pod-security.kubernetes.io/warn=privileged
              pod-security.kubernetes.io/warn-version=v1.24
Annotations:  openshift.io/sa.scc.mcs: s0:c26,c20
              openshift.io/sa.scc.supplemental-groups: 1000690000/10000
              openshift.io/sa.scc.uid-range: 1000690000/10000
Status:       Active

No resource quota.

No LimitRange resource.

**Comment by ashish-kumar-hpe** [comment]
While the permission issue is resolved, I now see that notebook launch is progressing and finally dying. Log says following error.

<info> [2023-08-21 11:27:07] [c0714f91] Pod cmd-0-51dd1c79-80f4-4737-96ec-c9be2fcefd90.1-bright-scorpion: Created container determined-init-container
<info> [2023-08-21 11:27:07] [c0714f91] Pod cmd-0-51dd1c79-80f4-4737-96ec-c9be2fcefd90.1-bright-scorpion: Started container determined-init-container
<info> [2023-08-21 11:27:08] [c0714f91] Pod cmd-0-51dd1c79-80f4-4737-96ec-c9be2fcefd90.1-bright-scorpion: Add eth0 [12.131.3.163/23] from openshift-sdn
<info> [2023-08-21 11:27:08] [c0714f91] Pod cmd-0-51dd1c79-80f4-4737-96ec-c9be2fcefd90.1-bright-scorpion: Container image "fluent/fluent-bit:1.6" already present on machine
<info> [2023-08-21 11:27:08] [c0714f91] Pod cmd-0-51dd1c79-80f4-4737-96ec-c9be2fcefd90.1-bright-scorpion: Created container determined-fluent-container
<info> [2023-08-21 11:27:08] [c0714f91] Pod cmd-0-51dd1c79-80f4-4737-96ec-c9be2fcefd90.1-bright-scorpion: Started container determined-fluent-container
<info> [2023-08-21 11:27:08] [c0714f91] Pod cmd-0-51dd1c79-80f4-4737-96ec-c9be2fcefd90.1-bright-scorpion: Container image "determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.11-gpu-6eceaca" already present on machine
<info> [2023-08-21 11:27:08] [c0714f91] Pod cmd-0-51dd1c79-80f4-4737-96ec-c9be2fcefd90.1-bright-scorpion: Created container determined-container
<info> [2023-08-21 11:27:08] [c0714f91] Pod cmd-0-51dd1c79-80f4-4737-96ec-c9be2fcefd90.1-bright-scorpion: Started container determined-container
<info> [2023-08-21 11:27:16] [c0714f91] Pod cmd-0-51dd1c79-80f4-4737-96ec-c9be2fcefd90.1-bright-scorpion: Pod resources allocated.
<info> [2023-08-21 11:30:54] || INFO: Scheduling ashish-ai-pipeline-test1 (id: 51dd1c79-80f4-4737-96ec-c9be2fcefd90)
<info> [2023-08-21 11:30:54] || INFO: ashish-ai-pipeline-test1 was assigned to an agent
<info> [2023-08-21 11:30:58] [c0714f91] Resources for ashish-ai-pipeline-test1 have started
<error> [2023-08-21 11:30:58] || ERROR: ashish-ai-pipeline-test1 was terminated: allocation failed: task failed without an associated exit code: pod actor exited while pod was running

**Comment by ashish-kumar-hpe** [comment]
Hello - Just wanted to share that this was again kubernetes "csr certificate" related issue which were in pending state and once i approved the certificates from openshift then notebook was successfully launching. 

oc logs determined-master-deployment-detai-6494686458-mpsvp -n determined
Error from server: Get "https://10.218.44.207:10250/containerLogs/determined/determined-master-deployment-detai-6494686458-mpsvp/determined-master-detai": remote error: tls: internal error

Get the current state of csr deployed on nodes:
oc get csr

Approve all csr:
oc get csr -o name | xargs oc adm certificate approve

Then Job launching was working fine.
(venv39) [root@gl-scalableai-gpu-compute1 ashish]# cat config-ai-pipeline-test1
bind_mounts:
  - host_path: /root/ashish
    container_path: /workdir/ashish
debug: false
description: ashish-ai-pipeline-test1
entrypoint: null
environment:
  add_capabilities: null
  drop_capabilities: null
  environment_variables: {}
  force_pull_image: false
  image:
    cpu: determinedai/environments:py-3.8-pytorch-1.12-tf-2.8-cpu-9d07809
    cuda: determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.11-gpu-6eceaca
  pod_spec: null
  ports: null
  proxy_ports: null
idle_timeout: null
notebook_idle_type: kernels_or_terminals
pbs: {}
resources:
  devices: null
  resource_pool: default
  slots: 1
  weight: 1
slurm: {}
work_dir: /workdir
(venv39) [root@gl-scalableai-gpu-compute1 ashish]# det notebook start --config-file config-ai-pipeline-test1
Master version 0.23.4 is less than CLI version 0.24.0. Consider upgrading the master.
Launched notebook (id: 2edd9490-4dc1-4f32-9b9b-6bbdec5f5004).
notebook (id: 2edd9490-4dc1-4f32-9b9b-6bbdec5f5004) is ready.
Jupyter Notebook is running at: http://10.218.44.207:30497/det/interactive/2edd9490-4dc1-4f32-9b9b-6bbdec5f5004/jupyter-lab/ashish-ai-pipeline-test1/default/%2Fdet%2Fwait%2Fjupyter-lab%2F2edd9490-4dc1-4f32-9b9b-6bbdec5f5004%3FeventUrl%3D%2Fproxy%2F2edd9490-4dc1-4f32-9b9b-6bbdec5f5004%2F%2Fjupyter-lab%2F2edd9490-4dc1-4f32-9b9b-6bbdec5f5004%2Fevents%26serviceAddr%3D%2Fproxy%2F2edd9490-4dc1-4f32-9b9b-6bbdec5f5004%2F?currentSlotsExceeded=false
(venv39) [root@gl-scalableai-gpu-compute1 ashish]#

However, I do not see that my local drive is mounted in the Jupyter Notebook workspace.

**Comment by ashish-kumar-hpe** [comment]
Yes. It is similar issue. However the key difference is that earlier determined was standalone and this time it is in kubernetes environment.  When i get inside the pod then i do see that "/workdir/ashish is there mounted however it is is saying that there is no permission. 

ls -l /workdir
total 8
-rw-r--r--. 1 root root 3018 Aug 22 17:00 Untitled.ipynb
drwxr-xr-x. 2 root root 4096 Jul 14 12:36 ashish

ls -l /workdir/ashish
ls: cannot open directory '/workdir/ashish': Permission denied

mount also shows...
/dev/mapper/rhel-root on /workdir/ashish type xfs (rw,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,noquota)

but this is not accessible. Not sure if there is additional configuration that I need to provide and that could be the reason that this is not showing up in the workspace as well.

**Comment by ioga** [comment]
1. What are the underlying permission for the host path you're mounting? since your `host_path: /root/ashish`, I assume it's owned by root:root.
2. Does your container run as root, or as some user (because openshift security)?

If it's a user, then it is expected the user cannot access root-owned directory. So you need to change the permissions for the underlying storage (i.e. the host_path you're mounting) to make that data accessible by the container user.

**Comment by ashish-kumar-hpe** [comment]
Some sites recommends me to add securityContext as below while spinning up the notebook pod. Typically pod specs have securityContext.

  securityContext:
    fsGroup: GROUP_ID

How do i provide the securiyContext in the yaml file?

**Comment by ashish-kumar-hpe** [comment]
Recommended PVC suggestion with OCP/Determined works. 

1. Create PVC
=============

	cat sample-pvc.yaml
	apiVersion: v1
	kind: PersistentVolumeClaim
	metadata:
	  name: ashish-ai-pipeline-volume-claim
	  namespace: determined
	spec:
	  accessModes:
	  - ReadWriteOnce
	  resources:
	    requests:
	      storage: 50Gi
	  storageClassName: cp-sc

3. Custom PodSpec
=================

	debug: false
	description: ashish-ai-pipeline-test1
	entrypoint: null
	environment:
	  add_capabilities: null
	  drop_capabilities: null
	  environment_variables: {}
	  force_pull_image: false
	  image:
	    cpu: determinedai/environments:py-3.8-pytorch-1.12-tf-2.8-cpu-9d07809
	    cuda: determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.11-gpu-6eceaca
	  pod_spec:
	    apiVersion: v1
	    kind: Pod
	    metadata:
	      labels:
		customLabel: gpu-label
	      namespace: determined
	    spec:
	      containers:
		- name: determined-container
		  volumeMounts:
		    - name: ashish-ai-pipeline-volume
		      mountPath: /workdir/ashish
	      volumes:
		- name: ashish-ai-pipeline-volume
		  persistentVolumeClaim:
		    claimName: ashish-ai-pipeline-volume-claim
	  ports: null
	  proxy_ports: null
	idle_timeout: null
	notebook_idle_type: kernels_or_terminals
	pbs: {}
	resources:
	  devices: null
	  resource_pool: default
	  slots: 2
	  weight: 1
	slurm: {}
	work_dir: /workdir

now, when i execute this task in the pod I get permission denied error. 
!nvidia-smi
Failed to initialize NVML: Insufficient Permissions

when i execute the same host or ocp environment i am getting no issues. 

		nvidia-smi
		Thu Aug 24 03:53:33 2023
		+---------------------------------------------------------------------------------------+
		| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
		|-----------------------------------------+----------------------+----------------------+
		| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
		| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
		|                                         |                      |               MIG M. |
		|=========================================+======================+======================|
		|   0  NVIDIA A100-PCIE-40GB          Off | 00000000:27:00.0 Off |                    0 |
		| N/A   45C    P0              41W / 250W |  37989MiB / 40960MiB |      0%      Default |
		|                                         |                      |             Disabled |
		+-----------------------------------------+----------------------+----------------------+
		|   1  NVIDIA A100-PCIE-40GB          Off | 00000000:A3:00.0 Off |                    0 |
		| N/A   44C    P0              41W / 250W |    463MiB / 40960MiB |      0%      Default |
		|                                         |                      |             Disabled |
		+-----------------------------------------+----------------------+----------------------+

		+---------------------------------------------------------------------------------------+
		| Processes:                                                                            |
		|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
		|        ID   ID                                                             Usage      |
		|=======================================================================================|
		|    0   N/A  N/A   1509856      C   /root/venv39/bin/python3.9                37976MiB |
		|    1   N/A  N/A   1509856      C   /root/venv39/bin/python3.9                  450MiB |
		+---------------------------------------------------------------------------------------+
		
		nvidia-smi
		Thu Aug 24 03:54:02 2023
		+---------------------------------------------------------------------------------------+
		| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
		|-----------------------------------------+----------------------+----------------------+
		| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
		| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
		|                                         |                      |               MIG M. |
		|=========================================+======================+======================|
		|   0  NVIDIA A100-PCIE-40GB          Off | 00000000:27:00.0 Off |                    0 |
		| N/A   44C    P0              35W / 250W |    150MiB / 40960MiB |      0%      Default |
		|                                         |                      |             Disabled |
		+-----------------------------------------+----------------------+----------------------+
		|   1  NVIDIA A100-PCIE-40GB          Off | 00000000:A3:00.0 Off |                    0 |
		| N/A   44C    P0              37W / 250W |      4MiB / 40960MiB |      0%      Default |
		|                                         |                      |             Disabled |
		+-----------------------------------------+----------------------+----------------------+

		+---------------------------------------------------------------------------------------+
		| Processes:                                                                            |
		|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
		|        ID   ID                                                             Usage      |
		|=======================================================================================|
		|    0   N/A  N/A      4215      G   /usr/libexec/Xorg                            63MiB |
		|    0   N/A  N/A      4936      G   /usr/bin/gnome-shell                         59MiB |
		+---------------------------------------------------------------------------------------+
		


		oc exec -it pod/nvidia-device-plugin-daemonset-zbbnl -n nvidia-gpu-operator -- nvidia-smi
		Defaulted container "nvidia-device-plugin" out of: nvidia-device-plugin, toolkit-validation (init)
		Thu Aug 24 08:51:13 2023
		+---------------------------------------------------------------------------------------+
		| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
		|-----------------------------------------+----------------------+----------------------+
		| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
		| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
		|                                         |                      |               MIG M. |
		|=========================================+======================+======================|
		|   0  NVIDIA A100-PCIE-40GB          Off | 00000000:27:00.0 Off |                    0 |
		| N/A   44C    P0              35W / 250W |    150MiB / 40960MiB |      0%      Default |
		|                                         |                      |             Disabled |
		+-----------------------------------------+----------------------+----------------------+
		|   1  NVIDIA A100-PCIE-40GB          Off | 00000000:A3:00.0 Off |                    0 |
		| N/A   44C    P0              37W / 250W |      4MiB / 40960MiB |      0%      Default |
		|                                         |                      |             Disabled |
		+-----------------------------------------+----------------------+----------------------+

		+---------------------------------------------------------------------------------------+
		| Processes:                                                                            |
		|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
		|        ID   ID                                                             Usage      |
		|=======================================================================================|
		+---------------------------------------------------------------------------------------+

		oc exec -it  pod/nvidia-device-plugin-daemonset-g4ht2 -n nvidia-gpu-operator -- nvidia-smi
		Defaulted container "nvidia-device-plugin" out of: nvidia-device-plugin, toolkit-validation (init)
		Thu Aug 24 08:51:41 2023
		+---------------------------------------------------------------------------------------+
		| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
		|-----------------------------------------+----------------------+----------------------+
		| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
		| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
		|                                         |                      |               MIG M. |
		|=========================================+======================+======================|
		|   0  NVIDIA A100-PCIE-40GB          Off | 00000000:27:00.0 Off |                    0 |
		| N/A   45C    P0              41W / 250W |  37989MiB / 40960MiB |      0%      Default |
		|                                         |                      |             Disabled |
		+-----------------------------------------+----------------------+----------------------+
		|   1  NVIDIA A100-PCIE-40GB          Off | 00000000:A3:00.0 Off |                    0 |
		| N/A   44C    P0              41W / 250W |    463MiB / 40960MiB |      0%      Default |
		|                                         |                      |             Disabled |
		+-----------------------------------------+----------------------+----------------------+

		+---------------------------------------------------------------------------------------+
		| Processes:                                                                            |
		|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
		|        ID   ID                                                             Usage      |
		|=======================================================================================|
		+---------------------------------------------------------------------------------------+
