### ISSUE TITLE
The following resource(s) failed to create: [DeterminedAddress]

### ISSUE THREAD

**Issue by sbhonde1** [determined-ai/determined#771]
I tried to run `det-deploy aws up --cluster-id testcluster0 --keypair mykeypairname --deployment-type vpc`. It failed with `--depoyment-type simple` as well. I also made sure that I have all the permissions before running these.
Any help would be appreciated.
Thank you

**Comment by neilconway** [comment]
@sbhonde1 Thanks for the report! Can you post the complete output that is produced by `det-deploy`? Might be easier to understand what is going on with `--deployment-type simple` first and then we can investigate the `vpc` case later.

**Comment by seanr15** [comment]
The Cloudformation console might have more information on why the resource failed to create. You should see a stack there named `testcluster0`. It could be that you are already at your Elastic IP (EIP) quota if the DeterminedAddress was the only failing resource. Both `vpc` and `simple` attach an EIP to the Determined master instance.

**Comment by sbhonde1** [comment]
@neilconway @seanr15 Thank you for the quick response. 
I was able to run `det-deploy` using a `secure` type. However, I got the following message on CloudFormation when I ran with `vpc` :
```
You must specify an allocation id when mapping an address to a VPC instance (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterCombination;
```

**Comment by seanr15** [comment]
The CloudFormation templates behind `det-deploy` were not designed to run from one deployment type to another. If you ran `det-deploy aws up --deployment-type vpc` and then followed with `det-deploy aws up --deployment-type secure`, there is a good chance your deployment is in a funky state. I recommend running `det-deploy aws down` to remove the resources and try again using `det-deploy aws up --deployment-type simple`.

**Comment by sbhonde1** [comment]
I am totally new to this so I think it was in a funny state. I was not able to connect to the master. I am trying again with `--deployment-type simple`. Is there any way exist to check if I am able to connect/ping to master?

**Comment by seanr15** [comment]
Interesting. Seems like things are still in a strange state. 

Are you on our community slack channel (determined-community.slack.com)? I can hop on a slack call to get you unblocked. Send me a DM - sean.determined

**Comment by sbhonde1** [comment]
Hi Sean,
I tried reaching out but I think I do not have access to slack group. Also, I am not able to login using my personal slack account.

**Comment by seanr15** [comment]
[Use this link](https://join.slack.com/t/determined-community/shared_invite/zt-cnj7802v-KcVbaUrIzQOwmkmY7gP0Ew) to join

**Comment by sbhonde1** [comment]
The issue was caused because of internal aws setup. The `--deployment-type secure` is working fine so closing this for now. I will comment if I find the exact reason.
