### ISSUE TITLE
🐛[bug] Error launch experiments from windows

### ISSUE THREAD

**Issue by kmilouh** [determined-ai/determined#7712]
### Describe the bug

There is a bug when i lunch a experiment from windows. the startup hook does not find the requirements.txt but if a lunch this from linux it works fine. Also in the log the output of the requirements are inside ' and with a \r at the end, but in linux not.

### Reproduction Steps

1. From a windows terminal launch a experiment with a folder with the experiment context

### Expected Behavior

It should work as when i lunch from linux or mac.

### Screenshot

![image](https://github.com/determined-ai/determined/assets/13699090/a07bd444-0411-4053-9fed-d4a0c79e29d0)
![image](https://github.com/determined-ai/determined/assets/13699090/ef3d7c6c-d53e-4710-a05c-29ad43f813c8)
![image](https://github.com/determined-ai/determined/assets/13699090/538294ca-d967-4a07-bde3-9e2dce0afdfa)

### Environment

- OS: Windows 10
- Version 0.24.0

**Comment by ioga** [comment]
hello, does the `startup-hook.sh` have `\r` in it? 

I'd like to understand if
A. this can be worked around by configuring your Windows editor to use `\n` as newlines, and not use `\r`.
OR B. there's something in our code which inserts `\r`'s on Windows.

**Comment by kmilouh** [comment]
i have the code in a github repo when clone the repo in linux and execute the command` det experiment create -f ./context/const.yaml ./context` the `startup-hook.sh` execute fine. When i clone the repo in a Windows 10 Pro 21H2 in Spanish and execute the command `det experiment create  -f context\const.yaml   context\` this error happens.  After more deep review the issue is with the git client that change the  LF to CRLF.
