### ISSUE TITLE
🤔[question] image(determinedai/environments:cuda-11.8-pytorch-2.0-gpu-mpi-0.24.0) to submit multinodes task

### ISSUE THREAD

**Issue by caiduoduo12138** [determined-ai/determined#7739]
### Describe your question

When I use the image(determinedai/environments:cuda-11.8-pytorch-2.0-gpu-mpi-0.24.0) to submit multinodes task, it seems has some error. Can you give me some help?
Here is the log file
[experiment_20_trial_18_logs.txt](https://github.com/determined-ai/determined/files/12435957/experiment_20_trial_18_logs.txt)

**Comment by rb-determined-ai** [comment]
Could you share more information, like what version your determined-master is running, the experiment config you are using, and if the contents of your startup hook (if you have one)?

**Comment by KevinMusgrave** [comment]
Could this be related? https://github.com/yaml/pyyaml/issues/724
