### ISSUE TITLE
🐛[bug] “det agent disable/enable --agent-id” can not work normally

### ISSUE THREAD

**Issue by ShiroZhang** [determined-ai/determined#7831]
### Describe the bug

when i using det agent disable/enable， i found param “--all” can work，but “--agent-id” can not work

### Reproduction Steps

```
root@node94:/mnt/userData/public/test_torch# det agent
 Agent ID       | Version   | Registered Time          |   Slots |   Containers |   Resource Pool | Enabled   | Draining   | Addresses
----------------+-----------+--------------------------+---------+--------------+-----------------+-----------+------------+----------------
 192.168.100.95 | 0.25.0    | 2023-09-07 13:27:11+0000 |       2 |            0 |            2060 | True      | False      | 192.168.100.95
 192.168.100.97 | 0.25.0    | 2023-09-07 13:27:13+0000 |       1 |            0 |            3070 | True      | False      | 192.168.100.97
root@node94:/mnt/userData/public/test_torch# det agent disable 
Must specify exactly on of --all or --agent-id
root@node94:/mnt/userData/public/test_torch# det agent disable --agent-id="192.168.100.97"
usage: det [-h] [-u username] [-m address] [-v] command ...
det: error: unrecognized arguments: --agent-id=192.168.100.97
```

### Expected Behavior

can disable/enable specific agent normally

### Screenshot

![image](https://github.com/determined-ai/determined/assets/132639336/5911dd89-30ec-49ee-9437-8480fa246a0b)

### Environment

- Device or hardware: NVIDIA Geforce 3070、2060
- OS: ubuntu20.04 
- Version: determined==0.25.0

**Comment by ioga** [comment]
hello,

the error message is misleading, sorry about that. agent ids are supposed to be a [positional argument](https://github.com/determined-ai/determined/blob/main/harness/determined/cli/agent.py#L254), i.e. please try:
```
det agent disable "192.168.100.97"
```

**Comment by ShiroZhang** [comment]
>

**Comment by ShiroZhang** [comment]
it works，thank you very much
