### ISSUE TITLE
Image support for newer versions of ROCm and PyTorch 

### ISSUE THREAD

**Issue by albertogg99** [determined-ai/determined#7832]
### Describe your question

I was wondering if you are planning to launch images supporting newer versions of ROCm (i.e. 5.6) and PyTorch (i.e. 2.0), given that the [latest images](https://hub.docker.com/r/determinedai/environments/tags?page=1&name=rocm) are a bit behind with ROCm 5.0 and PyTorch 1.10. Thanks in advance.

**Comment by vishnu2kmohan** [comment]
Yes, we are actively working to update our ROCm task environment Docker images to be based on:
* rocm/pytorch:rocm5.6_ubuntu20.04_py3.8_pytorch_2.0.1
* rocm/pytorch:rocm5.6_ubuntu20.04_py3.8_pytorch_1.13.1

I'll post an update here once they're ready; thanks for inquiring.
