### ISSUE TITLE
Are there any cpu based examples of determined?🤔[question] 

### ISSUE THREAD

**Issue by humbleearth** [determined-ai/determined#7846]
### Describe your question

I have been trying a few examples of determined in kubernetes cluster. Since the cluster is cpu based, it always gives me an error 0 gpus available. Are there any examples which I can try of cpu based?

**Comment by ioga** [comment]
hello, we have a couple options:

1. you can set `resources -> slots_per_trial` option in the experiment config yaml to 0. Alternatively, on the CLI, `det e create ... --config resources.slots_per_trial=0`. This will effectively run one k8s pod per trial without resource requests.
2. you can setup a cluster in a specific way to describe the resource requests: https://docs.determined.ai/latest/setup-cluster/deploy-cluster/k8s/install-on-kubernetes.html#resource-configuration-cpu-based-setups . this may be useful if you want to run distributed training with CPU pods.

Not all of our examples will run on a CPU. The simpler ones or tutorials have a higher chance.

**Comment by r-s-4** [comment]
I tried setting slots_per_trial=0, but I still keep getting this in the logs:
[a5884739] [29] root: detected 0 gpu processes (nvidia-smi not found).

Is there any other option?

**Comment by r-s-4** [comment]
> hello, we have a couple options:
> 
> 1. you can set `resources -> slots_per_trial` option in the experiment config yaml to 0. Alternatively, on the CLI, `det e create ... --config resources.slots_per_trial=0`. This will effectively run one k8s pod per trial without resource requests.
> 2. you can setup a cluster in a specific way to describe the resource requests: https://docs.determined.ai/latest/setup-cluster/deploy-cluster/k8s/install-on-kubernetes.html#resource-configuration-cpu-based-setups . this may be useful if you want to run distributed training with CPU pods.
> 
> Not all of our examples will run on a CPU. The simpler ones or tutorials have a higher chance.

I tried setting slots_per_trial=0, but I still keep getting this in the logs:
[a5884739] [29] root: detected 0 gpu processes (nvidia-smi not found).

Is there any other option?

**Comment by ioga** [comment]
>[a5884739] [29] root: detected 0 gpu processes (nvidia-smi not found).

this is normal, and not even a warning. perhaps your code fails later for some other reason? can you please share which example you're trying out, how do you launch it, and the full logs?

if you want a specific example, you can try the `mnist_pytorch`: https://github.com/determined-ai/determined/blob/main/examples/tutorials/mnist_pytorch/const.yaml
then, `det e create const.yaml . -f --config resources.slots_per_trial=0` to start it up.

**Comment by humbleearth** [comment]
Thanks this is resolved with the code fix.
