### ISSUE TITLE
🤔[question] Where is the training stage log?

### ISSUE THREAD

**Issue by caiduoduo12138** [determined-ai/determined#7966]
### Describe your question

environment: determined 0.25.0
I train the mnist demo, but I cannot find the trianing stage log.  There is only the validation stage in the log, whether it is a bug in version 0.25.0?
Here is the train log and chart image. 
[experiment_34_trial_34_logs.txt](https://github.com/determined-ai/determined/files/12696419/experiment_34_trial_34_logs.txt)
![image](https://github.com/determined-ai/determined/assets/55495912/3beb2b5d-9013-45d3-9ba7-e9ce2fb50b10)

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
are you looking for the metrics selector in the upper right corner of the chart?

<img width="1182" alt="Screen Shot 2023-09-21 at 21 45 01" src="https://github.com/determined-ai/determined/assets/839187/5e0d064a-a238-4f20-86d4-a6924a8dc92e">

**Comment by caiduoduo12138** [comment]
> are you looking for the metrics selector in the upper right corner of the chart?
>
> <img alt="Screen Shot 2023-09-21 at 21 45 01" width="1182" src="https://user-images.githubusercontent.com/839187/269831265-5e0d064a-a238-4f20-86d4-a6924a8dc92e.png">

here is the whole image. but the [experiment_34_trial_34_logs.txt](https://github.com/determined-ai/determined/files/12696419/experiment_34_trial_34_logs.txt). do not contains any training infromation.
![image](https://github.com/determined-ai/determined/assets/55495912/f2e041d1-2347-4c7c-9c2d-a994eaa500aa)

**Comment by ioga** [comment]
Still trying to understand the issue.

We used to log lines such as:
`[2023-09-22T17:41:59.520515Z] 62bed52f || INFO: [38] determined.core: report_training_metrics(steps_completed=200, metrics={'loss': 0.2438710629940033})`

In 0.25.0, we do not log these, and you're suggesting we should. The problem is with the log file, and there's nothing wrong with the Web UI or the metrics charts. Did I get the situation right?

**Comment by caiduoduo12138** [comment]
> used to log lines such as:
> `[2023-09-22T17:41:59.520515Z] `

sorry for my poor English, you are right.
