### ISSUE TITLE
Are there terraform templates available for determined for aws?🤔[question] 

### ISSUE THREAD

**Issue by humbleearth** [determined-ai/determined#8094]
### Describe your question

Currently determined ai uses cloud formation templates for deploying to aws. Are there any templates or examples of terraform for same for aws? Also similarly for kubernetes deployment on AWS do we have cloudformation and terraform templates for AWS?

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
we don't have the CloudFormation templates reimplemented in terraform for AWS. we use terraform for [GCP](https://github.com/determined-ai/determined/tree/main/harness/determined/deploy/gcp/terraform) though, you can take it as an inspiration.

>Also similarly for kubernetes deployment on AWS do we have cloudformation and terraform templates for AWS?

We do not. Creating a k8s cluster on any cloud platform is usually quite straightforward and well-documented. Also that'd be a strange thing to do: usually people run a number of applications in one k8s cluster, so I am not sure we'd want to be in charge of creating the k8s clusters. Do you really think that's something we're supposed to offer?

**Comment by ioga** [comment]
feel free to reopen this issue if you want to discuss this more.
