### ISSUE TITLE
🐛[bug] Multi-node training hangs in _combine_and_average_training_metrics due to ZeroMQ bug

### ISSUE THREAD

**Issue by igor0** [determined-ai/determined#8222]
### Describe the bug

We reliably observe hangs in `_combine_and_average_training_metrics` in training under the following circumstances:

* The training job is multi-node
* And the time between consecutive _combine_and_average_training_metrics  calls is greater than TCP keep-alive interval, which for us is 1 hour

In these circumstances, our training reliably hangs. We root-caused the hangs to the following known issue in the ZeroMQ library: https://github.com/zeromq/libzmq/issues/2763

The problem is that ZeroMQ will stop delivering messages if no messages are sent for a longer time period than the TCP keep-alive interval. As a result, the next `gather()` will simply hang because the cross-node messages never reach the IPC chief.

The recommendation from the ZeroMQ bug linked above is to set HEARTBEAT_IVL to prevent the TCP connection from going stale. We were able to work around the issue by including the following monkey-patch in our Determined Trial implementation:

```
def monkeypatch_zmq_context_init():
    """Monkey-patch zmq.Context constructor to set the heartbeat interval to 1 minute."""
    import zmq

    original_zmq_context_init = zmq.Context.__init__

    def patched_zmq_context_init(self, *args, **kwargs):
        original_zmq_context_init(self, *args, **kwargs)
        self.setsockopt(zmq.HEARTBEAT_IVL, 60 * 1000)

    zmq.Context.__init__ = patched_zmq_context_init


monkeypatch_zmq_context_init()
```

To avoid the monkey-patching, we'd need one of the following from Determined:
* Option 1: `ZMQBroadcastClient` and `ZMQBroadcastServer` issue the appropriate `setsockopt`, either on the `zmq.Context` or on each ZMQ socket
* Option 2: Determined enables us to pass in our own `zmq.Context` that we can configure as above. From looking at the code, it doesn't seem like it would be particularly easy to plumb this through.

### Reproduction Steps

1. Run a multi-node training job that invokes `_combine_and_average_training_metrics` with long gaps in between (likely hours, depending on the TCP keep-alive in your environment)
2. Observe that `_combine_and_average_training_metrics` hangs

### Expected Behavior

`_combine_and_average_training_metrics` should not hang

### Screenshot

N/A

### Environment

N/A

**Comment by ioga** [comment]
Hello,

Thanks a ton for the detailed bug description. I don't think there's any downside to a zmq heartbeat option, the performance overhead will be negligible. Let me know if I am missing something.

So, we'll likely do the option 1.

**Comment by igor0** [comment]
Yes, I think that Option 1 makes the most sense. I don't think there is any downside. And it would prevent other Determined users from hitting this issue.

**Comment by rb-determined-ai** [comment]
@igor0 it should be fixed in our upcoming release (whichever follows 0.27.0)
