### ISSUE TITLE
🤔[question] how to disabling address space randomization

### ISSUE THREAD

**Issue by Force1ess** [determined-ai/determined#8242]
### Describe your question

When I debug cuda applications, it raises
`
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
`
[solution in docker](https://stackoverflow.com/questions/35860527/warning-error-disabling-address-space-randomization-operation-not-permitted), I don't have any idea after I looked up to docs.
Thank u for your patience

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
hello,

I assume you're using agent resource manager, and you're looking for a way to do `--cap-add=SYS_PTRACE --security-opt seccomp=unconfined`.

You can set `--cap-add` using the [add_capabilities](https://docs.determined.ai/latest/reference/deploy/config/master-config-reference.html#add-capabilities) option.

We do not offer a way to set `seccomp=unconfined`, unfortunately.
