### ISSUE TITLE
Does determined provide data / model access through gitlfs 🤔[question] 

### ISSUE THREAD

**Issue by humbleearth** [determined-ai/determined#8297]
### Describe your question

Similar to s3 and efs does determined provide access to gitlfs for storage layer

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
hello, 

We are not prescriptive on data access side: you can download or read your data any way you want. you can bake in gitlfs setup into your env image, or do it dynamically in `startup-hook.sh`.

We do not have checkpoint storage support for gitlfs today.
