### ISSUE TITLE
Any example for matplotlib figure as part of artifact?🤔[question] 

### ISSUE THREAD

**Issue by humbleearth** [determined-ai/determined#8350]
### Describe your question

Hi, As part of a submitted experiment, I am using matplotlib to plot and show it. Does determined ai uses this information and put it in artifacts or checkpoints. If not by default, how do I include matplotlib pic as part of the experiement artifacts? Do you have any examples for same?

Also wanted to know apart from the default metrics, does determined allow any custom visualization or inclusion of any other chart types as part of the visualization dashboard?

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
We have a few ways to add arbitrary files to checkpoints depending on which API you use.

Core API v1 or v2: https://docs.determined.ai/latest/model-dev-guide/api-guides/apis-howto/api-core-ug.html#step-3-1-save-checkpoints

PyTorchTrial: https://docs.determined.ai/latest/reference/training/api-pytorch-reference.html#determined.pytorch.PyTorchCallback.on_checkpoint_write_end

TFKerasTrial: https://docs.determined.ai/latest/reference/training/api-keras-reference.html#determined.keras.callbacks.Callback.on_checkpoint_end

>Also wanted to know apart from the default metrics, does determined allow any custom visualization or inclusion of any other chart types as part of the visualization dashboard?

Not at this time, but it's on the roadmap.
