### ISSUE TITLE
Anyway to avoid non-Admin User Ability to Delete Others' Task Containers？

### ISSUE THREAD

**Issue by jeremyjiao** [determined-ai/determined#8379]
### Describe your question

I would like to inquire about the Determined framework. After creating a container using the task interface, non-administrator accounts still have the ability to delete task containers belonging to other users. Is there a solution to address this issue?

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
Determined Enterprise Edition supports [Role-Based Access Control](https://docs.determined.ai/latest/manage/security/rbac.html) feature which would let you configure that. Let us know if you want to chat about it.

**Comment by jeremyjiao** [comment]
Great thx for your response!
