### ISSUE TITLE
🤔[question] Customize Slack Webhook?

### ISSUE THREAD

**Issue by Wildshire** [determined-ai/determined#8581]
### Describe your question

Hello

I was playing with the slack integration with webhooks and I was wondering if it was possible to customize the messages sent to the webhook. I know you can provide the link to the experiments but I was aiming for a customized messages with the determined user. Like:

```
Hey @determined_user, your experiment is completed / failed
(insert here original slack webhook)
```

"determined_user" can be the displayed name on the determined platform or the username for instance

I am quite new with this type of integrations, if that's something to be handled on the Slack app let me know.

Cheers and thanks in advance

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
hello, we do not have a way to customize it. 

here's the code which generates the payload, if you want to patch it or make a PR: https://github.com/determined-ai/determined/blob/main/master/internal/webhooks/postgres_webhook.go#L487
