### ISSUE TITLE
🤔[question] add resource_pools

### ISSUE THREAD

**Issue by TdTianpo** [determined-ai/determined#8619]
### Describe your question

how to add resource_pools? dont restart determined-master
v 0.26.7
### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by MikhailKardash** [comment]
Hello, right now we don't support attaching resource pools without restarting the master. However, we are thinking about adding this feature. 

Can you give me some more details about why you don't want to restart master?
