### ISSUE TITLE
🐛[bug] det CLI tool errors on Python 3.12 because it relies on distutils which was deprecated in Python 3.10

### ISSUE THREAD

**Issue by sirredbeard** [determined-ai/determined#8666]
### Describe the bug

The det CLI tool produces an error that distuils is not found when run on Python 3.12.

distutils was depcreated in Python 3.10 and removed in 3.12.

### Reproduction Steps

1. Install Python 3.12
2. Install Determined with pip install determined
3. Run det --version

### Expected Behavior

Determined client works on 3.12. Even if 3.12 is not yet supported, we should plan for deprecation of distutils.

### Screenshot

![image](https://github.com/determined-ai/determined/assets/33820650/59aa5c54-3fc6-408b-9d4f-91c8c675dc8d)

### Environment

- Device or hardware: Windows Dev Kit 2023
- OS: Windows 11 Beta Insiders
- Browser: Edge
- Version: 0.26.7

**Comment by sirredbeard** [comment]
The temporary workaround on 3.12 is to `pip install setuputils`.

**Comment by rb-determined-ai** [comment]
Yeah, this has been coming.  We can either change our CLI flag reading logic to something more standard ("non-empty flag means true, empty flag means false"), which is a breaking change, or reimplement the one-line function that we were using from distutils.

I'll create a ticket for this internally.

**Comment by rb-determined-ai** [comment]
The fix is up: #8667
