### ISSUE TITLE
Notebooks started from the UI don't appear in the CLI

### ISSUE THREAD

**Issue by tekumara** [determined-ai/determined#868]
Create a local cluster: `det-deploy local cluster-up --no-gpu`
Visit the UI and launch a new notebook.

The notebook isn't listed in the CLI:
```
$ det notebook ls
 Id   | Owner   | Description   | State   | Exit Status
------+---------+---------------+---------+---------------
```

**Comment by vishnu2kmohan** [comment]
@tekumara Would you please try again after trying to login via `det user login`?

I assume you're seeing this is on Determined [0.12.11](https://github.com/determined-ai/determined/releases/tag/0.12.11)?

**Comment by neilconway** [comment]
@tekumara Did the notebook actually launch successfully / does it appear in the WebUI? (Note that you'll need to specify launching a CPU-only notebook if your cluster has no GPUs.)

**Comment by tekumara** [comment]
@vishnu2kmohan thanks for pointing me in the right direction.

I'd logged into the Web UI as `admin`, and wasn't logged in on the CLI, so was authenticated as the `determined` user.

`det notebook list -a` shows me the notebook started by admin!
