### ISSUE TITLE
🤔 model registry - inference with pytorch model

### ISSUE THREAD

**Issue by Fedege98** [determined-ai/determined#8806]
### Describe your question

Hello! I have a question with respect to a behavior of python library to interact with determined.ai.
Specifically, I want to be able to download a specific pytorch model from the model registry of determined.ai to do real-time inference. Following the documentation it is not clear how to do this. 

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by KevinMusgrave** [comment]
If you have the name of the model in the model registry and the model version number:

```python
from determined.experimental import client

model_name = ...
version_num = ...

# checkpoint_dir will contain the downloaded checkpoint
# By default checkpoint_dir will be checkpoint/<checkpoint_uuid> in the current working directory.
# You can download to a custom path by passing in path=<path> into the download function.
checkpoint_dir = client.get_model(model_name).get_version(version_num).checkpoint.download()
```
