### ISSUE TITLE
🐛[bug] Error Starting Up Cluster using det deploy

### ISSUE THREAD

**Issue by Ke293-x2Ek-Qe-7-aE-B** [determined-ai/determined#8824]
### Describe the bug

After installing docker and determined, I can not start up the cluster. When I run `det deploy local cluster-up` I get an error.

### Reproduction Steps

1. Install Docker
2. Install Determined using `pip install determined`
3. Run `det deploy local cluster-up`

### Expected Behavior

The cluster should start up so I can log in to the web portal.

### Screenshot

![Screenshot from 2024-02-09 18-26-47](https://github.com/determined-ai/determined/assets/134176316/0d63eb4f-6dfb-4782-9983-09a5c88e01e2)

### Environment

- Device or hardware: Geforce GTX 1660 Ti
- OS: Ubuntu 22.04
- Browser: Firefox
- Version 22.04

**Comment by MikhailKardash** [comment]
Hello, thanks for the report. It looks like `det deploy` is having trouble detecting your gpu. Can you run `nvidia-smi`?

**Comment by Ke293-x2Ek-Qe-7-aE-B** [comment]
@MikhailKardash Sorry for the late reply. My GPU is old, so that might be the reason.
![image](https://github.com/determined-ai/determined/assets/134176316/71839c6c-7bfe-4fbe-819d-bbd9c3399be7)

**Comment by MikhailKardash** [comment]
Great. Do you also have `nvidia-container-toolkit` installed? https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
