### ISSUE TITLE
🐛[bug] Bad ref on requirements.rst in Docs

### ISSUE THREAD

**Issue by sirredbeard** [determined-ai/determined#8826]
### Describe the bug

Ref link is broken on https://docs.determined.ai/latest/setup-cluster/on-prem/requirements.html.

### Reproduction Steps

1. Visit https://docs.determined.ai/latest/setup-cluster/on-prem/requirements.html

### Expected Behavior

Ref link works.

### Screenshot

![image](https://github.com/determined-ai/determined/assets/33820650/82cd2664-6d2c-420b-85ab-bad5f8a35208)

### Environment

Browser

**Comment by tara-det-ai** [comment]
fix: https://github.com/determined-ai/determined/pull/8825
