### ISSUE TITLE
🐛[bug] Resources failed with non-zero exit code: container failed with non-zero exit code: 80

### ISSUE THREAD

**Issue by samjenks** [determined-ai/determined#8844]
### Describe the bug

I'm trying to start the tutorial experiment via `det e create const.yaml . -f` experiment starts up but then fails when using default docker container `determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.11-gpu-0.27.1`. 

The logs show: 

[2024-02-13 22:50:35] || INFO: Scheduling Trial 6 (Experiment 6) (id: 6.687cde07-ba3f-4966-9994-073a60ce3021.1)
<info> [2024-02-13 22:50:35] || INFO: Trial 6 (Experiment 6) was assigned to an agent
<info> [2024-02-13 22:50:35] [2b9091c2] image already found, skipping pull phase: [docker.io/determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.11-gpu-f66cbce](http://docker.io/determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.11-gpu-f66cbce)
<info> [2024-02-13 22:50:35] [2b9091c2] copying files to container: /
<info> [2024-02-13 22:50:35] [2b9091c2] copying files to container: /run/determined
<info> [2024-02-13 22:50:35] [2b9091c2] copying files to container: /
<info> [2024-02-13 22:50:35] [2b9091c2] copying files to container: /
<info> [2024-02-13 22:50:35] [2b9091c2] copying files to container: /
<info> [2024-02-13 22:50:35] [2b9091c2] copying files to container: /
<info> [2024-02-13 22:50:35] [2b9091c2] copying files to container: /
<info> [2024-02-13 22:50:35] [2b9091c2] copying files to container: /
<info> [2024-02-13 22:50:36] [2b9091c2] Resources for Trial 6 (Experiment 6) have started
<error> [2024-02-13 22:51:08] [2b9091c2] crashed: resources failed with non-zero exit code: container failed with non-zero exit code: 80 (exit code 80)
<error> [2024-02-13 22:51:08] || ERROR: Trial 6 (Experiment 6) was terminated: allocation failed: resources failed with non-zero exit code: container failed with non-zero exit code: 80 (exit code 80))

What is that error code 80?
How do I verify my agent/resources are setup correctly?
Likewise if I want to create my own docker env images for my experiments as noted [here](https://docs.determined.ai/latest/model-dev-guide/prepare-container/custom-env.html#custom-images) what Determined AI specific code do i need to integrate into them to get that to work?

### Reproduction Steps

1. Deploy cluster anyway you like, I've tried both the cluster-up and the Linux services method
2. Download mnist tutorial
3. Run tutorial via `det e create const.yaml . -f`

### Expected Behavior

I expected it to run how the tutorial document said it would

### Screenshot

can furnish upon request

### Environment

- Device or hardware: Nvidia A40
- OS: Ubuntu 22.04
- Browser Chrome/CLI
- Version 0.28.0

**Comment by rb-determined-ai** [comment]
oh, hey, this is my code!

The exit code of 80 with no logs means that the log shipper crashed for some reason.

There's a [special escape hatch](https://github.com/determined-ai/determined/blob/ba03375270d0c63620c4171a35a40d89ff4bf89a/master/static/srv/ship_logs.py#L708) built in to help debug this case.

You can rerun this task with a bind mount with `container_path: /ship_logs`, and see what shows up in that directory.  There should be a stack trace that explains what happened.

**Comment by samjenks** [comment]
Thanks, that got me more info. This seems to be the overall error. any thoughts on why the localhost is refusing connection?

ERROR: [1] root: Unable to reach the master at DET_MASTER=http://127.0.0.1:8090/.  The connection to http://127.0.0.1:8090/ was refused.
Debug information:
    master_url: http://127.0.0.1:8090/
    endpoint: http://127.0.0.1:8090/api/v1/me
    tls_verify_name: None
    tls_noverify: False
    tls_cert: None
    http_proxy: None
    HTTP_PROXY: None
    no_proxy: None
    NO_PROXY: None

**Comment by rb-determined-ai** [comment]
Well, that depends.  Do you have host networking mode configured?  If not, then `DET_MASTER` of `127.0.0.1` will never work.  You might have to configure the agent with `container_master_host` with an appropriate IP address that can point to the master.

But if things were working before and all you changed was the port, then probably you do have host networking mode configured, and it's a firewall problem.

Can you share more info about how you launched the cluster, and what your master and agent config files contain?

**Comment by samjenks** [comment]
I switched the networking mode from `bridge` to `host` and it all worked for the const.yaml. however the distrib.yaml hangs for a very long time during training without finishing. I've run it a couple of times to verify. It does it at the downloading dataset mostly. Is this normal or another problem with my configuration. The logging files don't have any information, is there a way to see why its hanging?

I launched the cluster via the deploy on prem guide [here](https://docs.determined.ai/latest/setup-cluster/on-prem/options/linux-packages.html#install-using-linux-packages)

**Comment by rb-determined-ai** [comment]
Hi sam, I'd say "don't waste your time".  Instead focus on making sure you don't have 127.0.0.1 for your master address in the first place.

I'd recommend setting the `container_master_host` in the agent yaml to an IP address that resolves to your master node even from inside a container (often the external IP address of the machine running the master).
