### ISSUE TITLE
🤔[question] Updating the default Determined-Pytorch container to 2.1/2.2

### ISSUE THREAD

**Issue by samjenks** [determined-ai/determined#8908]
### Describe your question

Is there any issue foreseen with updating the current determined docker container with Pytorch 2.1 or 2.2 with cuda 11.8? The documents say not to, however I am wonder if there is a reason? 1.12 is pretty old at this point

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
did you find an answer or did you close it by mistake?
