### ISSUE TITLE
Integrated with VTable

### ISSUE THREAD

**Issue by fangsmile** [determined-ai/determined#9528]
### Describe the problem

Whether it can be integrated with VTable. VTable table library has a strong visual display ability and high-performance.
You can check the VTable website for more information：https://visactor.io/vtable
Github: https://github.com/VisActor/VTable
![img_v3_029n_c20f8bf0-914d-480e-9369-9541ff50bc7g](https://github.com/determined-ai/determined/assets/3468473/51c8b675-ef30-4669-964e-b805b7f6cfa8)

### Describe the solution you'd like

visualization and  high-performance.

**Comment by ioga** [comment]
no self-promotion please.
