### ISSUE TITLE
🤔[question] I want to callback the interface when the resource is released.

### ISSUE THREAD

**Issue by caiduoduo12138** [determined-ai/determined#9734]
### Describe your question

I want add the callback when the resource is released. I try to add some code at resources.go:
![image](https://github.com/user-attachments/assets/6c585117-2b35-406f-968d-57e3c273cc91)
And I build this project from source code using MakeFile, but it seems does not work.  Even l add some fmt.Println code and it also does not work.
Inform function
![image](https://github.com/user-attachments/assets/6815e1de-c929-498c-9357-f0846df024b3)
can you give me some advice, thanks.

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
>And I build this project from source code using MakeFile, but it seems does not work. Even l add some fmt.Println code and it also does not work.

I'd suggest you figure out if you can make custom builds of the software with your code changes. For example, you can put some prints into `Run` function in `core.go` which is called on master startup to initialize everything, so it'll be easy for you to confirm your changes are there.

Then, once you know you can change the code with confidence, you can hack it further.

Also, `String()` method on `ResourcesStopped` is called to create a string representation of that object — it won't necessarily happen when the resources are released.

**Comment by caiduoduo12138** [comment]
> > And I build this project from source code using MakeFile, but it seems does not work. Even l add some fmt.Println code and it also does not work.
> 
> I'd suggest you figure out if you can make custom builds of the software with your code changes. For example, you can put some prints into `Run` function in `core.go` which is called on master startup to initialize everything, so it'll be easy for you to confirm your changes are there.
> 
> Then, once you know you can change the code with confidence, you can hack it further.
> 
> Also, `String()` method on `ResourcesStopped` is called to create a string representation of that object — it won't necessarily happen when the resources are released.

thanks for you reply, I will try it.

**Comment by caiduoduo12138** [comment]
How determined create a specific container and where can I find the code. 
eg: I run the mnist test using official code. The determined will create a container by the image. What I want to do is that I want to inform  our local interface((http://xxxxx:xxx/inform) ) in the container when the resources are  released.

**Comment by caiduoduo12138** [comment]
Can you tell me how to start the db service, I cannot find the postgres.
