### ISSUE TITLE
🤔[question] can you provide me a example that use amp(mixed precision)

### ISSUE THREAD

**Issue by ShiroZhang** [determined-ai/determined#9817]
### Describe your question

```
class AmpTrial(PyTorchTrial):
    pass
```

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
We don't require any of our own code for the amp. Simply follow the [torch amp autocast docs](https://pytorch.org/tutorials/recipes/recipes/amp_recipe.html), here's [one example](https://github.com/determined-ai/determined/blob/main/harness/tests/experiment/fixtures/pytorch_amp/manual_amp_model_def.py#L34) from our tests.

**Comment by ShiroZhang** [comment]
> We don't require any of our own code for the amp. Simply follow the [torch amp autocast docs](https://pytorch.org/tutorials/recipes/recipes/amp_recipe.html), here's [one example](https://github.com/determined-ai/determined/blob/main/harness/tests/experiment/fixtures/pytorch_amp/manual_amp_model_def.py#L34) from our tests.

thank you
