### ISSUE TITLE
Docker compose installation

### ISSUE THREAD

**Issue by Dri4n** [determined-ai/determined#982]
Hello greetings from Chile.

I'm new to determinated, honestly I've gotten a bit lost in the docker install documentation, and I've decided to create a docker-compose.yml to make new users a little easier.

I do not know if I am doing the right thing when creating a case, on the contrary, please specify how to continue with the contribution.

URL Descarga docker-compose.yaml [https://drive.google.com/file/d/1PbLXV_ooxlgc1HIArsGa7hVIemwgJ1lD/view?usp=sharing](url)

thank you.

**Comment by neilconway** [comment]
@Dri4n Welcome! And thank you for putting that Docker compose file together. Under the covers, `det-deploy local` is also using Docker Compose in a fairly similar way, so what you're doing looks reasonable to me.

> honestly I've gotten a bit lost in the docker install documentation, and I've decided to create a docker-compose.yml to make new users a little easier.

Do you have any suggestions on how we can improve the installation documentation, or any specific things that you found to be confusing?

**Comment by vishnu2kmohan** [comment]
@Dri4n Following up here to see if you're unblocked and if we may close out this issue.

**Comment by vishnu2kmohan** [comment]
Closing this issue out @Dri4n, please reopen, if needed.
