### ISSUE TITLE
💡[feat] how to avoid node GPU fragmentation

### ISSUE THREAD

**Issue by GrS-AA** [determined-ai/determined#9861]
### Describe the problem

I'd need to submit 8 1-GPU jobs or shells to the queue and have them use the same DGX node in order to avoid fragmentation of the available ressources in the queue.

How can I at submission-time specified the node to run on?

### Describe the solution you'd like

Add to the determined config a parameter for the "Agent ID" (which I'd get from `det slot list`)  to use.

In a more elaborate solution I could give a LIST of nodes to use in priority.

### Describe alternatives you've considered

send the same jobs many many times and immediately kill all the ones that randomly landed on the "wrong" nodes

**Comment by ioga** [comment]
hello, we don't have a feature to put a job onto the specific node. however, 
1. on Agent RM you could kinda fake it by setting up a resource pool for each of your nodes, and then selecting the specific resource pool when submitting a job. 
2. on kubernets, you could probably use one of k8s ways to achieve the same.

as for job packing,
1. On AgentRM, with `fitting_method: best` (default), the jobs should already be packed together: https://docs.determined.ai/latest/reference/deploy/master-config-reference.html#best 
2. on Kubernetes, you can add podAffinity to the pod spec, or setup something like a kyverno policy which'd add podAffinity to all pods.

**Comment by ioga** [comment]
feel free to reopen the question if or when you have a follow-up.
