### ISSUE TITLE
🤔[question] How to Completely Uninstall Determined AI and Reset Admin User?

### ISSUE THREAD

**Issue by Flukeds129** [determined-ai/determined#9961]
### Describe your question

Please help me with the following scenario:

1. I installed Determined AI using pip install in my conda environment.
2. When I first ran det deploy local cluster-up, it created an admin user and gave me a password.
3. I forgot the password and can’t reset it because it asks for the current password.
4. I tried to fix this by uninstalling Determined (pip uninstall determined) and removing the Docker images and containers.
5. After reinstalling, it’s still using the old admin user, and it didn’t create a new one.

I would like to completely uninstall Determined AI, including any old settings, and do a fresh install where it creates a new admin user and password. How can I fully wipe everything and start over?

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by rb-determined-ai** [comment]
`det deploy local cluster-up` is going to create a docker volume to persist the database.

The default name for the database is `determined_determined-db-volume` (or `CLUSTERNAME_determined-db-volume` if you did `det deploy local cluster-up --cluster-name CLUSTERNAME`).

So you can run `det deploy local cluster-down` to turn off the containers, and while no containers are using the volume, you can run `docker volume rm determined_determined-db-volume`.

Then next `det deploy local cluster-up` command will create a new volume with an empty database.
